### ISSUE TITLE
vim-polyglot breaks matchit.vim '%' operator (navigation between opening and closing XML tags)

### ISSUE THREAD

**Issue by ninrod** [sheerun/vim-polyglot#100]
I verified that commit 0dc7696 breaks [matchit.vim][matchit_link] behaviour. So it affects vim-polyglot since release [v2.3.0][tag_link].

Steps to reproduce: 
* checkout any version of vim-polyglot after commit 0dc7696 (inclusive);
* open an html file and try to use the `%` operator to navigate between opening and closing tags. 
* It will not work. 

If i checkout the commit immediatelly before 0dc7696, which is commit 5658b62, then [matchit.vim][matchit_link] works again on html tags as expected.

Here's my [.dotfile][dotfile_link] configuration that includes your plugin.

[matchit_link]: <https://github.com/vim/vim/blob/master/runtime/macros/matchit.vim>
[tag_link]: <https://github.com/sheerun/vim-polyglot/releases/tag/v2.3.0>
[dotfile_link]: <https://github.com/ninrod/unix-shell-config.git>

**Comment by sheerun** [comment]
Could you check v2.7.2 and if it doesn't work, attach your vim configuration (either .vimrc or zip)

**Comment by ninrod** [comment]
@sheerun It works with v2.7.2. Thank you.
