### ISSUE TITLE
list in README is out of date

### ISSUE THREAD

**Issue by wi1d5ky** [sheerun/vim-polyglot#101]
The list of supported languages in README doesn't include some languages in `/syntax` folder.
For example:
There is a `scss` in `/syntax` folder, but I can't find it in README.
It might make people missunderstand that some languages are not support :S

**Comment by sheerun** [comment]
README is always up to date, because it's written by a script.

scss seems to be a part of haml package.

If you find a way to automate such documentation, please send a PR.

**Comment by wi1d5ky** [comment]
So it is! Thank you for telling me that scss is a part of haml!
I didn't know that before :-S
