### ISSUE TITLE
.jade setting filetype as html with scrooloose/syntastic

### ISSUE THREAD

**Issue by guyhughes** [sheerun/vim-polyglot#104]
With just https://github.com/digitaltoad/vim-jade (upstream) installed or vim-polyglot, when I open *.jade files ft=jade, no problem.

But with https://github.com/scrooloose/syntastic installed as well, I get ft=html, even if I run the build bash script.

Seems reproducible. Not sure where the conflict is.

**Comment by sheerun** [comment]
I'm afraid you need to resolve it with upstream repositories or suggest alternative one.
