### ISSUE TITLE
Proper Installation?

### ISSUE THREAD

**Issue by donileo** [sheerun/vim-polyglot#105]
I went ahead and added vim-polyglot by cloning the source into my .vim/bundle/vim-polyglot directory. Then added to my .vimrc file:

```
Plugin 'vim-polyglot'
```

But when loading vim with a go file for example im not getting the go-fmt that fatih/vim-go provides on save for example. This leads me to believe vim-polyglot is not properly installed. I dont see Swift file syntax coloring either. I made sure to run :PluginInstall so what am I missing?

I alternatively  did a:

```
Plugin: 'sheerun/vim-polyglot.git'
```
Removed the .vim/bundle/vim-polyglot folder and then did a :PluginInstall and still nothing.

**Comment by sheerun** [comment]
Proper way to include it is `Plugin 'sheerun/vim-polyglot`

**Comment by sheerun** [comment]
or if you use Plug `Plug `sheerun/vim-polyglot``

**Comment by donileo** [comment]
I have done Plugin 'sheerun/vim-polyglot' and am failing to get the autoformating (gofmt) that the go plugin provides on saving go files.

**Comment by sheerun** [comment]
vim-polglot handles only syntax and indent, not autoformatting

**Comment by donileo** [comment]
fatih/vim-go which is bundled by vim-polyglot does the goftmt on save of go files yet vim-polyglot cant do it even though it bundles fatih/vim-go ?

**Comment by sheerun** [comment]
yes, we filter out unnecessary stuff

**Comment by donileo** [comment]
I dont see why you believe gofmt is unneccessary :) gofmt is a core part of writing go code. I would suggest including it in vim-polyglot as many gophers would not use vim-polyglot simply because this is missing.

**Comment by sheerun** [comment]
To get full support for go-lang you can use go plugin directly. vim-polyglot deals only with syntax and indent so it can load quickly. We don't plan to fully support all languages including tooling.

**Comment by juanjux** [comment]
You should be more explicit about that (only dealing with syntax an indent) in the README.md file. I was wondering why a bunch of things (among them gofmt) stopped working with this plugin even while it bundles the plugins I was using previously.

**Comment by sheerun** [comment]
I've updated the readme
