### ISSUE TITLE
How long will you update this project?

### ISSUE THREAD

**Issue by QMonkey** [sheerun/vim-polyglot#112]
I make this issue just because I have some questions to ask.
How long will you update this project?
Do you update this project when any of those 70+ projects are updated?

**Comment by sheerun** [comment]
Every few weeks or so. I don't update every time any project is updated

**Comment by sheerun** [comment]
As for how log - as long as I use vim, so forever :)

**Comment by sheerun** [comment]
By the way, you can update locally if you want to, just run `./build` script.

**Comment by QMonkey** [comment]
> By the way, you can update locally if you want to, just run ./build script.

Nice, I really like it! :)
