### ISSUE TITLE
include godlygeek/tabular for plasticboy/vim-markdown, voxpupuli/vim-puppet, and any other desired utilization?

### ISSUE THREAD

**Issue by justfielding** [sheerun/vim-polyglot#136]
With the recent commit opting to switch to [plasticboy/vim-markdown](https://github.com/plasticboy/vim-markdown), https://github.com/sheerun/vim-polyglot/commit/7a32eec6d17ec6de269753b8ef7b11d27b562853, I was curious if you thought [godlygeek/tabular](https://github.com/godlygeek/tabular) and it's functionality would be a useful addition?

[plasticboy/vim-markdown](https://github.com/plasticboy/vim-markdown) as well as [voxpupuli/vim-puppet ](https://github.com/voxpupuli/vim-puppet) mention including it for a more robust experience with their plugins.

Perhaps it isn't required anymore for the functionality it served the individual plugins when they were operating without access to the rest of the polyglot code base? Sorry if my lack of intimacy with the plugin's code base caused me to jump to conclusions, and it isn't needed/wasn't ever an issue.

If you did feel it was needed, where would you implement plugins that add features/support for multiple language plugins on vim-polyglot's list? I was going to fork and add it to a branch for my own personal evaluation, but haven't looked at the code base enough to get a feel for how it would be implemented following current project style.

-Fielding

**Comment by sheerun** [comment]
Hey,

My focus with vim-polyglot is on reliable syntax support, not advanced features like auto-indentation. If you often need to auto-indent tabular data in markdown, you can use plasticboy's plugin directly on top of vim-polyglot :) While I find plasticboy's syntax files superior to tpope's (for example they better handle `*` character), I intentionally stripped it from tabular.
