### ISSUE TITLE
Highlighting not working

### ISSUE THREAD

**Issue by jmsherry** [sheerun/vim-polyglot#137]
Hi guys,
Sorry, I looked all over to find another place another place to ask this.

I've installed vim-polyglot (it shows up with `:ListPlugins` ) but it's not highlighting when I open files. 

I realise that's not a lot to go on, but is there any configuration work? Or should it all be automatic?

I do see yellow and blue tag indicators though - is it possible that terminal theming breaks the syntax highlighting?

Thanks. :)

(I've opened a question here - http://vi.stackexchange.com/questions/8488/syntax-highlighting-not-working-vim-polyglot)

**Comment by sheerun** [comment]
Could you try to install any individual package instead? I think it's problem with your setup, not vim-polyglot

**Comment by jmsherry** [comment]
Thanks @sheerun ,
It transpires that in my `.vimrc` I needed `syntax on` near the start of the file.

I don't know if that's a setting of vim-polyglot or vim in general. If it's for this then maybe putting this somewhere in a troubleshooting guide or the installation guide would be helpful to people? :)

**Comment by sheerun** [comment]
Good idea, I've added info about syntax on to the README. Feel free to add any extra info in PR :)
