### ISSUE TITLE
Add Graphviz syntax

### ISSUE THREAD

**Issue by c9rgreen** [sheerun/vim-polyglot#14]
Could you add support for the [Graphviz](http://www.graphviz.org) language?
I would suggest using [wannesm/wmgraphviz.vim](https://github.com/wannesm/wmgraphviz.vim).

**Comment by sjuxax** [comment]
Hello. Graphviz syntax highlighting is available in many Vim installations under the filetype "dot".

I added this to my `vimrc` to get automatic detection:

    "set *.gv files to dot syntax
    au BufRead,BufNewFile *.gv set filetype=dot

Replying here mainly for people doing searches, but I have `vim-polyglot` installed, and still had to make this change manually. It may be worth considering adding to the plugin.

**Comment by leycec** [comment]
**You rock,** @sjuxax.

The layout-specific `.dot` filetype has long been deprecated in favour of the layout-agnostic `.gv` filetype. It saddens the graph theoretician in me that Vim only associates the former with the GraphViz filetype. Bram should transparently support both out-of-the-box. Thankfully, Florida Man saves the day... *yet again.*

**Comment by LuisBL** [comment]
does it make sens to reopen this issue ?
