### ISSUE TITLE
[Javascript] Template Literals syntax highlighting not working with ES6 and JSX

### ISSUE THREAD

**Issue by huynhquancam** [sheerun/vim-polyglot#143]
The syntax highlighting seems not working with ES6 and JSX for template literals which enclosed by ``back-tick ` ``

Screen shot attached.

<img width="618" alt="screen shot 2016-07-05 at 17 26 56" src="https://cloud.githubusercontent.com/assets/5930347/16581871/e6e35d82-42d5-11e6-8256-964c7c9ca537.png">

The code example:

```javascript
export default class Carousel extends Component {
  render() {
    const { urls, activeIndex, onRotate } = this.props

    const list = urls.map(url => <img className={`img${1}`} src={url} />)

    return (
      <div className="carousel">
        { list }
        <button className="left-btn" onClick={ () => onRotate(-1) }>Left</button>
        <button className="right-btn" onClick={ () => onRotate(1) }>Right</button>
      </div>
    )
  }
}

```

**Comment by sheerun** [comment]
If you'll find better syntaxes for javascript, please let me know :) I cannot modify anything directly here, as vim-polyglot is just bundle of other syntax plugins.

**Comment by huynhquancam** [comment]
Fixed with https://github.com/pangloss/vim-javascript/issues/527
