### ISSUE TITLE
rust.vim is missing the plugin directory (and some functionality)

### ISSUE THREAD

**Issue by michael-younkin** [sheerun/vim-polyglot#146]
If you take a look at the actual `rust.vim` repo, you'll see that it has some code in the `plugin` directory which needs to run in order for the plugin to work correctly. You seem to have omitted this directory.

**Comment by sheerun** [comment]
Not sure what doesn't work for you, but we don't include `plugin` as it is loaded even if someone doesn't use rust. `ftplugin` on the other hand is executed only when you open rust file.

Startup time is a priority for vim-polyglot, so unfortunately I won't include it.

**Comment by michael-younkin** [comment]
Okay, thanks for the response. You should consider noting this in the README because omitting parts of plugins can keep them from working properly.

**Comment by sheerun** [comment]
Syntax & indentation works for rust files, I review the changes

**Comment by michael-younkin** [comment]
Right, but there are other features that don't work, such as the ability to automatically run rustfmt when a file is saved. I imagine many of the other plugins you have also are missing some functionality because of this. I realize this was an explicit decision you made, but you may want to consider noting in your README that only some parts of plugins are included and that this isn't a drop-in replacement. I didn't realize it was intentional and not a bug until I made this issue, and other people might too.

**Comment by sheerun** [comment]
Gotcha, I've added a comment about it in the readme. Thanks :)
