### ISSUE TITLE
Leanpub custom Markdown

### ISSUE THREAD

**Issue by taq** [sheerun/vim-polyglot#149]
Hi! I'm using Vim to write my books on Leanpub, and they have a tip to a custom way to insert code files on https://leanpub.com/help/manual on "Vim Syntax Fix for Code Markup". They ask to insert this code on `.vim/after/syntax/markdown.vim`:

```
1 syn match markdownLeanCode '^<<(.*)$'
2 
3 hi def link markdownLeanCode   markdownH1
```

It was not working, and I found that when I delete the vim-polyglot `markdown.vim` file, it works.

Any tips about this?

Thanks! :-)

**Comment by sheerun** [comment]
Hey. Probably this snippet is compatible only with native markdown syntax. You can disable syntaxes individually like described in the README.md. I cannot help here otherwise.
