### ISSUE TITLE
On opening a Javascript file, `E121: Undefined variable: b:undo_ftplugin`

### ISSUE THREAD

**Issue by metakirby5** [sheerun/vim-polyglot#150]
Caused by [this line](https://github.com/sheerun/vim-polyglot/blob/master/after/ftplugin/javascript.vim#L10).

**Comment by sheerun** [comment]
Hey. Unfortunately I cannot reproduce this. I am JS developer myself and I never had issue with vim-polyglot. If you still experience this issue, please make sure it's `vim-polyglot`'s bug, and send your `.vimrc` configuration and sample `.js` file to reproduce.

**Comment by metakirby5** [comment]
I just tried updating and the issue seems to be gone now. Thanks!
