### ISSUE TITLE
Update source repo for `vim-twig`

### ISSUE THREAD

**Issue by whitelynx** [sheerun/vim-polyglot#156]
[As of October 9, 2015](https://github.com/evidens/vim-twig/commit/4e8e678f0f46bd75db4530fbe1ec05dd941764da), the README for `evidens/vim-twig` has been updated saying that it's discontinued; [as of August 16th, 2016](https://github.com/evidens/vim-twig/commit/cd936524f34fc47bcb1f46a03c5614208c42383e), it now points to [lumiliet/vim-twig](https://github.com/lumiliet/vim-twig) for more recent development.

**Comment by sheerun** [comment]
Fixed :) Thanks for report!
