### ISSUE TITLE
YAML syntax disables default Vim highlights

### ISSUE THREAD

**Issue by jlebon** [sheerun/vim-polyglot#157]
I'm not savvy enough in Vim syntax to know where to look and how to fix this, but I've noticed that after installing `vim-polyglot`, Vim no longer automatically highlights words such as TODO and XXX when editing yaml, which was an awesome feature. I believe the syntax group is called `todo`, but I don't see anywhere in the config files where this gets overridden. Other filetypes are not affected.

**Comment by sheerun** [comment]
You could either disable polyglot provided yaml syntax (see README), or fix upstream package vim-polyglot uses. Vim-polyglot just gathers different syntax packages.

**Comment by jlebon** [comment]
Thanks!
