### ISSUE TITLE
Elm indentation problem

### ISSUE THREAD

**Issue by yigitozkavci** [sheerun/vim-polyglot#161]
When using the plugin, it overrides my tabstop config by setting it to `8`.

`vim-polyglot` uses [lambdatoast/elm.vim](https://github.com/lambdatoast/elm.vim) for elm files but disabling `vim-polyglot` and enabling [lambdatoast/elm.vim](https://github.com/lambdatoast/elm.vim) solves the issue.

**Comment by CrashyBang** [comment]
@yigitozkavci second link points to wrong place.

**Comment by yigitozkavci** [comment]
Updated, thanks @CrashyBang

**Comment by sheerun** [comment]
I've updated elm bundle in vim-polyglot, hope it helps. If not, please try to resolve with upstream
