### ISSUE TITLE
jsx plugin marks all JavaScript files as ft javascript.jsx

### ISSUE THREAD

**Issue by moonglum** [sheerun/vim-polyglot#162]
Hey 👍 Thanks for your amazing work on polyglot 😄 

I have a problem with the jsx plugin: It sets the ft of all `*.js` files as `javascript.jsx` instead of `javascript`. This causes problems with other plugins, as they do not activate when they do not see the `javascript` ft.

I solved this by disabling the `jsx` in polyglot (which is no problem for me, as I don't use jsx anywhere). But can this be solved differently?

**Comment by sheerun** [comment]
I guess it can be if jsx syntax uses javascript filetype instead. I'd need to be solved in respective plugins, though. Not here.

**Comment by codeinabox** [comment]
I noticed that this change https://github.com/sheerun/vim-polyglot/commit/7dd62806a06af3cf2410cd8a4f83205269f279de causes .js files to be treated as JSX which isn't the default behaviour for https://github.com/mxw/vim-jsx but a simple fix is to add the following to your .vimrc

```viml
let g:jsx_ext_required = 1
```

**Comment by moonglum** [comment]
Thanks to you both! Added @codeinabox's snippet to my vimrc, fixes it for me.

**Comment by isobit** [comment]
Can this issue be reopened to revert 7dd6280? It's clear the issue here is with that change rather than the respective plugins. Why should `vim-polyglot` change `mxw/vim-jsx`'s default behavior?

**Comment by ciases** [comment]
`javascript.jsx` filetype is really annoying. Please fix it.

**Comment by sheerun** [comment]
I want jsx to be supported by default in .js files by default in vim-polyglot. It is very uncommon to name files .jsx if they contain jsx syntax. Usually they are just named .js.

Currently including `jsx:mxw/vim-jsx` and enabling mentioned flag is the easiest way to achieve it. If you'll have a solution that enables jsx syntax by default without changing filetype, please let me know.

Probably it would involve changing `jsx:mxw/vim-jsx` upstream so it doesn't change filetype.

**Comment by thisguychris** [comment]
@sheerun 
This plugin was inspired by vim-jsx but it doesn't change the filetype of the js files, I think it'll fix a lot of linters which breaks when having a different filetype is added (tern_for_vim) for example.

There's an open issue as well, suggesting this plugin, hoping this could be add soon:
https://github.com/sheerun/vim-polyglot/issues/400

**Comment by sheerun** [comment]
Thank you it makes sense. I’ll work on it soon

W dniu niedz., 26.05.2019 o 07:38 Chris <notifications@github.com>
napisał(a):

**Comment by jklepatch** [comment]
I am very confused by this issue. I cant see the correct syntax highlighting for jsx. have to uninstall `vim-polyglot` for now :(

.js => curly braces of jsx are red like if its an error
.tsx => even more weird behavior, all the colors are different from js for in jsx section

- I have removed all the other syntax plugins
- tried to add `let g:jsx_ext_required = 1` before pathogen load everything

It didn't fix the problem...

**Comment by sheerun** [comment]
@jklepatch I'm afraid the issue is with your setup, not vim-polyglot. Here's proof:

https://asciinema.org/a/jvZaDNHUpvkI54s5osdKc2xc6

If you experience some issue with js or jsx please open new issue with steps to reproduce

**Comment by sheerun** [comment]
Also, please update vim-polyglot to newest version

**Comment by jklepatch** [comment]
:(
I just used it for the first time a few hours ago.

Does Polyglot works with Pathogen as well?

**Comment by sheerun** [comment]
it should work with any plugin manager
