### ISSUE TITLE
Patch 7.4.1142 Error

### ISSUE THREAD

**Issue by lanzenotter** [sheerun/vim-polyglot#176]
If we want to highlight up nginx files, the following error occurs.
E410: Ungültiger :syntax Befehl: iskeyword 
This means that the command was not found
```
" Patch 7.4.1142
 if has("win32")
    syn iskeyword @,48-57,_,128-167,224-235,.,/,:
else
   syn iskeyword @,48-57,_,192-255,.,/,:
endif
```
After I have commented out the patch, it works again.

I tryd it on Debian 7 and Debian 8 with plug.vim as Pluginmanager.

**Comment by sheerun** [comment]
Hey. I suggest raising this issue in upstream repository. We just aggregate other plugins. See:
https://github.com/othree/nginx-contrib-vim
