### ISSUE TITLE
elixir defmodule name color

### ISSUE THREAD

**Issue by iansowinski** [sheerun/vim-polyglot#179]
color highlight for module name in "defmodule" is the same as "defmodule" and "do" after it, it shouldn't work like that:
<img width="633" alt="zrzut ekranu 2017-01-26 16 39 51" src="https://cloud.githubusercontent.com/assets/7414533/22337915/63f81a4a-e3e6-11e6-922c-e1dc02c2be97.png">

**Comment by sheerun** [comment]
I'm afraid this needs to be resolved in upstream repository
