### ISSUE TITLE
Add SWIG support

### ISSUE THREAD

**Issue by dajuno** [sheerun/vim-polyglot#181]
Hi all,
would you consider adding syntax for [SWIG](SWIGhttp://www.swig.org/) files (*.i)?
Here is a syntax file, just cpp augmented with some SWIG keywords: https://github.com/vim-scripts/SWIG-syntax/

Regards!

PS: admittedly the syntax file is pretty bad though.. In swig files there is normally C/C++ code mixed with, e.g., python code, in
```
%pythoncode %{
 ...
%}
```
blocks, which is not taken into account..

**Comment by sheerun** [comment]
Is https://github.com/blockloop/vim-swigjs better?

**Comment by sheerun** [comment]
Any other options?

**Comment by dajuno** [comment]
Apparently that's for a javascript package (https://github.com/paularmstrong/swig) with the same name. I was referring to this: http://swig.org/ (an interface between C/C++ and high level languages).
The only other option I found is this: http://www.vim.org/scripts/script.php?script_id=1247, but doesn't seem better.

**Comment by sheerun** [comment]
It seems it's pointless to add swig syntax if none of existing plugins support mixed code.. Please let me know if you find something else, or manage to patch https://github.com/vim-scripts/SWIG-syntax/
