### ISSUE TITLE
Add API Blueprint support

### ISSUE THREAD

**Issue by anhari** [sheerun/vim-polyglot#182]
Hi, would you consider adding support for API Blueprint?

A plugin exists here: https://github.com/kylef/apiblueprint.vim

**Comment by sheerun** [comment]
I'm little hesistant, as it tries to autodetect filetype based on contents, which slows down every file open in vim: https://github.com/kylef/apiblueprint.vim/commit/8fbefdb2e397b130a86ab3929321ce698ca45cce

Let's see if they are willing to change it, at last we can fork it..
