### ISSUE TITLE
The plugin overrides spell highlight in ruby files

### ISSUE THREAD

**Issue by dominikduda** [sheerun/vim-polyglot#184]
Title says all, the misspelled words highlighing doesnt work when vim-polyglot is on.

Without plugin:
![image](https://cloud.githubusercontent.com/assets/14922999/22748804/930447b0-ee2b-11e6-9180-deb49339bd59.png)

With plugin:
![image](https://cloud.githubusercontent.com/assets/14922999/22748852/bd07e26a-ee2b-11e6-8a22-fdc8a293ad81.png)

I found relevant topic on stack exchange:
http://vi.stackexchange.com/questions/2119/can-i-make-vims-spell-check-not-syntax-aware-and-check-everything
I can not make any use of it.

Would it be possible to fix it? From my understanding adding `@Spell` and `@NoSpell` in syntax files here could do the job. Am I right?

**Comment by sheerun** [comment]
Do you experience the same issue when using just vim-ruby/vim-ruby without vim-polyglot?

**Comment by dominikduda** [comment]
Yes

**Comment by sheerun** [comment]
Then please raise this issue there. Vim-polyglot is just bundling other plugins
