### ISSUE TITLE
Better nginx plugin

### ISSUE THREAD

**Issue by myfreeweb** [sheerun/vim-polyglot#187]
https://github.com/hexchain/vim-openresty is a fork of the nginx syntax plugin that supports nested Lua blocks.

**Comment by sheerun** [comment]
othree/nginx-contrib-vim we currently use has far better keyword support. I suggest merging hexchain/vim-openresty into it, so we can get best of both worlds

**Comment by chr4** [comment]
Referencing https://github.com/sheerun/vim-polyglot/issues/205
