### ISSUE TITLE
Pandoc markdown support

### ISSUE THREAD

**Issue by Armavica** [sheerun/vim-polyglot#190]
Pandoc uses a special flavor of markdown, that is much more comfortably edited with the help of the [dedicated plugin](https://github.com/vim-pandoc/vim-pandoc-syntax). Would it be possible to install this plugin alongside the currently available markdown plugin, and be able to select one or the other default for markdown files?

**Comment by sheerun** [comment]
It seems vim 8 supports pandoc and rmd by default. Could you try to upgrade?

As for the concealing features, unfortunately I don't want to include it as more often than not users don't like it
