### ISSUE TITLE
Support full Dockerfile syntax

### ISSUE THREAD

**Issue by dpiccone** [sheerun/vim-polyglot#191]
Some keywords are not available in the current package, such as `SHELL`

The current package `https://github.com/honza/dockerfile.vim` has been deprecated and merged to the main docker repo `https://github.com/docker/docker/tree/master/contrib/syntax/vim`

I see the current build script fetching the master branch of the github repos specified in `PACKS`

Is there a way to modify this function here (https://github.com/sheerun/vim-polyglot/blob/master/build#L19) to load a `tar` archive of a subfolder instead of downloading the full repo?

**Comment by sheerun** [comment]
I don't think it's possible in git in general, isn't it?

**Comment by dpiccone** [comment]
As far as I know I don't think it's possible to fetch only a part of the repo, but this could be a general case to support in `vim-polyglot` since the assumption in the download function is that each pack is basically a repo which is not always the case

**Comment by sheerun** [comment]
vim-polyglot already supports extracting just subdirectories, the syntax to put in build script is like so:

```
doceker:honza/dockerfile::contrib/syntax/vim
```

**Comment by dpiccone** [comment]
That is exactly what I was looking for, if you don't mind I'll open a PR to update the docker plugin and the source
