### ISSUE TITLE
Degrades buffer switching performance on MacVim

### ISSUE THREAD

**Issue by cmcginty** [sheerun/vim-polyglot#196]
I don't know when it started, but I realized switching between buffers in Vim was taking more than 500ms and started to become an annoyance. Once I disabled the polyglot plugin the switch time returned back to the normal speed, <50ms. 

I think there might be some issues with the new versions of Vim and your plugin. FWIW I was testing with relatively small python and yaml files.

**Comment by sheerun** [comment]
Could you describe how are you switching between buffers exactly, and maybe post example files that affect this? Could you also try to reproduce with only vim-polyglot enabled and no other plugins?

Also, I've updated all the packages recently, could you try to update first?
