### ISSUE TITLE
Don't disable JSON double quote concealing if the JSON plugin itself is disabled

### ISSUE THREAD

**Issue by chauncey-garrett** [sheerun/vim-polyglot#200]
I have the JSON plugin disabled and add in my own fork of it so it took me a while to find where concealing was being disabled. I've had to manually set the global variable to one, which is counter-intuitive to the default setting of vim-json.

I understand the reasoning behind disabling concealing for the majority of users of vim-polyglot and agree with this approach; however, if the JSON plugin is disabled I don't think this variable should be handled by polyglot at all.

https://github.com/sheerun/vim-polyglot/blob/8002795088067e5b9f578b748f9be0089621dc30/config.vim#L6-L9

**Comment by sheerun** [comment]
Isn't it what this code does? It checks whether someone set this variable, and only if it's not set, it defaults to `0`. If I'm wrong, can you suggest different approach by submitting a PR?

**Comment by chauncey-garrett** [comment]
It looks like vim-json has similar logic: https://github.com/elzr/vim-json/blob/f5e3181d0b33a9c51377bb7ea8492feddca8b503/ftplugin/json.vim#L9-L12

Thus it would depend on which plugin was loaded first as to what the variable ends up being. I load polyglot before anything else.

**Comment by sheerun** [comment]
I think we could disable setting this variable if `let g:polyglot_disabled = ['json']`, so you can use original plugin with the defaults. Do you want to send a PR?

Of course you can also load polyglot after json, or set the variable at the top of .vimrc
