### ISSUE TITLE
Vim8 built in package manager support.

### ISSUE THREAD

**Issue by gdance** [sheerun/vim-polyglot#201]
Hello,

I was just wondering if there was anyway to get this working with the builtin vim8 package manager. I followed the following article to switch to the vim8 package manager:

https://shapeshed.com/vim-packages/

After doing that I installed vim-polyglot into the start directory so that it would autostart and then I noticed that it really made vim slow. I then tried moving it into the opt directory so it wouldn't be auto-started but now I have to type :packadd vim-polygot to load it everytime I want to use it.

Is there anyway to get it to work properly or do you have to use Vundle or Plug or one of the other package managers?

**Comment by sheerun** [comment]
Seems to work for me without any slowdown:

```sh
mkdir -p ~/.vim/pack/default/start
git clone https://github.com/sheerun/vim-polyglot ~/.vim/pack/default/start/vim-polyglot
```

Please make sure there's no .vimrc or .vim folder before that.
