### ISSUE TITLE
How to use plugins for non-default languages?

### ISSUE THREAD

**Issue by partounian** [sheerun/vim-polyglot#203]
For example, I use the smarty templating engine for work and would like to use html5.vim for it along with M4R7iNP/smarty.vim . Another example is wanting to use the current pug plugin for files that end in ".pug.blade.php" .

**Comment by sheerun** [comment]
You just use package manager for vim like [vim-plug](https://github.com/junegunn/vim-plug), and include them normally. Something like `Plug "digitaltoad/vim-pug"` in your .vimrc
