### ISSUE TITLE
Include chr4/nginx.vim

### ISSUE THREAD

**Issue by chr4** [sheerun/vim-polyglot#205]
I've [just released](https://chr4.org/blog/2017/04/14/better-syntax-highlighting-and-snippets-for-nginx-in-vim/) the improved syntax highlighting plugin [chr4/nginx.vim](/chr4/nginx.vim). It is based upon current `nginx-1.12.0/contrib/vim` and adds more features on top of it:

- Highlight IPv4 and IPv6 addresses
- Mark insecure ssl_protocols as errors
- Inline template syntax highlight for ERB and Jinja
- Inline syntax highlight for LUA
- Improve integer matching
- Syntax highlighting for proxy_next_upstream options
- Syntax highlighting for sticky options
- Syntax highlighting for upstream server options

@myfreeweb suggested including it into `vim-polygot`, so I'm opening this. Thoughts?

**Comment by sheerun** [comment]
Sure thinks, looks awesome :)

**Comment by chr4** [comment]
Thanks!
