### ISSUE TITLE
Pug syntax highlighting doesn't work

### ISSUE THREAD

**Issue by sandrodz** [sheerun/vim-polyglot#208]
<img width="1382" alt="screen shot 2017-05-06 at 7 08 17 pm" src="https://cloud.githubusercontent.com/assets/8479569/25773499/67c240cc-328f-11e7-9640-beb91997a941.png">

**Comment by sheerun** [comment]
want to debug this?

**Comment by sandrodz** [comment]
Of course! tell me what you need.

**Comment by sheerun** [comment]
whether pug plugin that polyglot uses works for you, without polyglot

also if not, what is the plugin I should use

**Comment by sandrodz** [comment]
with or without polyglot result is the same.

The only thing I noticed though:
`:set ft? -> filetype=pug `
but if I manually set `:set ft=pug ` on open file syntax comes back

**Comment by sheerun** [comment]
it isn't the issue with polyglot then. maybe try to remove all plugins except polyglot

**Comment by sandrodz** [comment]
I removed plugins and reinstalled them and problem got resolved.
