### ISSUE TITLE
Please provide ConTeXt Typesetting Syntax support 

### ISSUE THREAD

**Issue by IbnSaeed** [sheerun/vim-polyglot#210]
Hello

can you provide ConTeXt Syntax support as well. It is similar to LaTeX typesetting but has different syntax.

here is the commands list:

http://wiki.contextgarden.net/Category:Commands

Here is the structure commands:

http://wiki.contextgarden.net/Structurals

**Comment by sheerun** [comment]
Hmm. I cannot find syntax plugin for this on GitHub. Could you find something?
