### ISSUE TITLE
Include sslsecure.vim

### ISSUE THREAD

**Issue by chr4** [sheerun/vim-polyglot#211]
After `nginx.vim` I've created [sslsecure.vim](https://github.com/chr4/sslsecure.vim) to highlight insecure SSL settings independently of the context. 

- Mark insecure SSL ciphers as errors
- Mark insecure SSL protocols as errors
- Works with all configuration files (web servers, mail servers, …)
- Works with all source code (independently on the used programming language)
- Works on top of regular syntax highlighting

See [this blog post](https://chr4.org/blog/2017/04/27/sslsecure-dot-vim/) for further information.

Thanks!

**Comment by sheerun** [comment]
Sorry I don't do it. It seems that this plugin runs for every opened file, and the promise vim-polyglot makes is to not slowdown loading of files in general case. A great plugin nonetheless!
