### ISSUE TITLE
Jinja/Nunjucks syntax 

### ISSUE THREAD

**Issue by partounian** [sheerun/vim-polyglot#214]
Please support Jinja and Nunjucks, the plugin below should be sufficient.

https://github.com/Glench/Vim-Jinja2-Syntax

**Comment by sheerun** [comment]
it should be in master now

**Comment by ciases** [comment]
Hello!
It doesn't work for me for unknown reason. I've try `*.njk, *.nunjucks, *.jinja` extensions, no success. Then I've install [lepture/vim-jinja](https://github.com/lepture/vim-jinja) and it works as expected.

**Comment by halkeye** [comment]
The other option so you don't need to install another plugin is `autocmd BufNewFile,BufRead *.njk setf htmldjango`
