### ISSUE TITLE
Question: Do I have to remove other syntax highlighters / ident plugins?

### ISSUE THREAD

**Issue by StevenXL** [sheerun/vim-polyglot#217]
If I already have / and am using 'vim-jsx', should I get rid of that first and then follow the installation instructions for `vim-polyglot`?

**Comment by ahmedelgabri** [comment]
**Short answer:** yes
**Long answer:** It depends, if you don't like what comes with `vim-polyglot` then you can disable that & use whatever you like instead. Or if the language is not supported in `vim-polyglot` then you will need to install that yourself or even better maybe open a PR to add it.

**Comment by sheerun** [comment]
also vim-polyglot adds just basinc syntax and highlighting. if you'd like advanced language support you'd need to install specific plugins
