### ISSUE TITLE
Update to pangloss/vim-javascript package?

### ISSUE THREAD

**Issue by fozcodes** [sheerun/vim-polyglot#218]
Hi There,

I'm seeing the same issue described here:

https://github.com/pangloss/vim-javascript/issues/356

Are those updates currently in the latest release? Would be great to have them. Thanks!

**Comment by chris-fa** [comment]
Is this still a thing?

**Comment by sheerun** [comment]
It's now updated :) btw. You can use `./build` to update manually (maybe even as a hook to Plug).

**Comment by fozcodes** [comment]
I had tried to do it manually but didn't seem to have any effect. Awesome, thanks!
