### ISSUE TITLE
twig syntax not working properly 

### ISSUE THREAD

**Issue by ahmedelgabri** [sheerun/vim-polyglot#229]
Commenting this block out makes it work fine https://github.com/sheerun/vim-polyglot/blob/master/syntax/twig.vim#L22-L24 

`:echo b:main_syntax` returns `twig` but when I comment this block out it returns `html` & works fine.

Now:
<img width="339" alt="screen shot 2017-09-09 at 13 34 56" src="https://user-images.githubusercontent.com/63876/30239781-c2b6220a-9563-11e7-80bf-8abbd3b5d664.png">

After commenting out that block:
<img width="322" alt="screen shot 2017-09-09 at 13 35 18" src="https://user-images.githubusercontent.com/63876/30239782-c99b1508-9563-11e7-9bf5-83f06bd5322c.png">

**Comment by sheerun** [comment]
this needs to be fixed in upstream package, isn't it?

**Comment by ahmedelgabri** [comment]
You are right, I opened an issue there https://github.com/lumiliet/vim-twig/issues/7

**Comment by ahmedelgabri** [comment]
This was fixed here https://github.com/lumiliet/vim-twig/pull/8
