### ISSUE TITLE
Add support for openscad

### ISSUE THREAD

**Issue by Armavica** [sheerun/vim-polyglot#232]
https://github.com/sirtaj/vim-openscad

**Comment by naggie** [comment]
As far as I can see this is no longer in master. Am I missing something?

**Comment by Armavica** [comment]
@naggie this: #249 
As far as I am concerned I haven't used openscad since then, so I haven't tried to get it back.

**Comment by naggie** [comment]
OK thanks -- I will try to fix the issue so it can be re-introduced when I have time..
