### ISSUE TITLE
commit 5b77877 breaks golang

### ISSUE THREAD

**Issue by ik5** [sheerun/vim-polyglot#237]
The big commit of 5b778778881 breaks the support to golang, making not only the syntax to have less colors, but also random error reporting that some variables does not exists.

It also breaks some parts of vim-go because of it.

I'm unable to capture the errors, because they are gone after few seconds.

**Comment by Carpetsmoker** [comment]
> I'm unable to capture the errors, because they are gone after few seconds.

Are they shown when you use `:messages`?

**Comment by brendanjerwin** [comment]
`let g:polyglot_disabled = ['go']` didn't seem to fix it for me. had to disable polyglot to get it to stop breaking things.

**Comment by Carpetsmoker** [comment]
Not related, but the `syntax/go.vim` file has:

    if !exists('g:polyglot_disabled') || index(g:polyglot_disabled, 'vim') == -1

Shouldn't that be `go` instead of `vim`?

**Comment by sheerun** [comment]
I've reverted inlining upstream vim syntax files, it should be fine now.

**Comment by ik5** [comment]
@Carpetsmoker sorry for the late response.

thank you @sheerun
