### ISSUE TITLE
JS syntax messed up

### ISSUE THREAD

**Issue by kristijanhusak** [sheerun/vim-polyglot#238]
I opened PR here https://github.com/pangloss/vim-javascript/issues/1055 since i thought it's bug on their side, but they don't want to do anything about it, so i'm opening the same thing here, since i'm not sure on which side bug happens.

From yesterday syntax messed up. Here's a screenshot from before:

![screenshot-before](https://i.imgur.com/Mc2lPXZ.png)

And after:
![screenshot-after](https://i.imgur.com/G6oQNoo.png)

When i checkout vim polyglot to this commit https://github.com/sheerun/vim-polyglot/commit/9bfde7574aa89a91b80ed9c993fc000cfc11aae7 everything works fine.

**Comment by sheerun** [comment]
I've reverted inlining upstream vim syntax files, it should be fine now.

**Comment by kristijanhusak** [comment]
Thanks!
