### ISSUE TITLE
CSV.vim plugin and LargeFile plugin missing, why?

### ISSUE THREAD

**Issue by Henri-Lo** [sheerun/vim-polyglot#239]
I would like to understand why this bundle does not contain CSV.vim plugin and LargeFile plugin.

**Is there something to edit CSV files or disable extensions when editing large files?**

**Comment by sheerun** [comment]
I think we had csv.vim but it caused performance issues when editign csv, and generally didn't to much good. As for LargeFile, nobody suggested it yet.

**Comment by heoa** [comment]
That is a reason to have LargeFile extension. With LargeFile extension, CSV.vim won't cause performance issues.

**Comment by Henri-Lo** [comment]
With LargeFile, you won't encounter performance issues with resource-intensive extensions such as CSV.vim. CSV.vim is brilliant but you need to know how to use it, like not using intensive commands such as ArrangeColumn with large files.

**Comment by sheerun** [comment]
I tried to add chrisbra/csv.vim but it makes loading big csv files considerably slower.

Also, I tries LargeFile plugin for 800mb csv file, but it doesn't make any difference.

**Comment by chrisbra** [comment]
author here. That solely depends on your csv file and the feature (e.g. auto-arranging) you use for it. But in general, it has to parse the csv file to setup the syntax rules, so depending on your data (and attributes) this is kind to be expected. But this should only affect csv files and no other ones.

**Comment by sheerun** [comment]
Sorry, I can't include in vim-polyglot that makes file loading considerably slower by default. Ideally you'd (@chrisbra) modify csv syntax plugin so it checks whether file has more than few megabytes and prevent parsing in such case. Then I'd have no problems including it.

CSV is an unfortunate exception from other languages as their files tend to be huge, you don't store tenths megabytes of data in .py or .rb file for example. That's why we need this "feature".

**Comment by chrisbra** [comment]
I forgot to document how to make the plugin faster, done [now](https://github.com/chrisbra/csv.vim/commit/efc41cadba1df6263d420654b0c8ce51c489e5b1). Setting at least `g:csv_end` to e..g 100 will considerably improve the loading performance of a file.
Also if you have enabled the LargeFile plugin, it will disable the csv plugin for huge files.

**Comment by sheerun** [comment]
OK, let me check

**Comment by whitelynx** [comment]
@sheerun just curious if this one fell through the cracks 😉

**Comment by sheerun** [comment]
I tried it with:

```
if !exists('g:csv_start')
  let g:csv_start = 1
endif
if !exists('g:csv_end')
  let g:csv_end = 10
endif
```

and largefile plugin, but loading of large csv files is still slow, sorry

**Comment by sheerun** [comment]
Hmm on second thought it's something different than these two as without them loading is slow as well...

**Comment by sheerun** [comment]
Okay, I've checked once more and it doesn't slow down anything, I've merged csv plugin :) thank you
