### ISSUE TITLE
Replace LaTeX-BoX (Latest commit in 2015) with a modern aproach

### ISSUE THREAD

**Issue by pezr** [sheerun/vim-polyglot#240]
LaTeX-BoX seems deprecated (Latest commit 3c2901e on Jun 1, 2015)
I suggest something like [vimtex](https://github.com/lervag/vimtex)

**Comment by ivegotasthma** [comment]
I'd also be interested in this

**Comment by lervag** [comment]
Me too (developer of vimtex here). I've been helping quite a lot of people, at least 5 or 6 (according to my issue tracker), with problems related to plugin conflicts between vimtex and LaTeX-Box.

**Comment by sheerun** [comment]
Hey @lervag awesome work :)

Please remember that the `build` script tries to strip things that are not syntax highlighting, indentation config, or compiler config.

I'd love to switch vim-polyglot to vimtex, but currently the blocker is a lot of warnings vimtex gives while latex-box shows none: https://i.imgur.com/B4f7eLF.png

Please consider not showing these warning and treating extra features as opt-in.

Also, the startup for .latex files is quite slow (especially ftplugin/tex.vim and first screen update), as shown by `vim --startuptime start.log foo.latex`

```
149.737  004.049  004.049: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex.vim
150.758  000.155  000.155: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/util.vim
170.958  000.719  000.719: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/state.vim
172.204  000.255  000.255: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/re.vim
172.430  000.882  000.627: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/parser.vim
193.118  000.141  000.141: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/paths.vim
193.532  000.190  000.190: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/view.vim
193.865  000.174  000.174: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/view/general.vim
194.409  000.326  000.326: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/view/common.vim
195.404  000.728  000.728: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/compiler.vim
197.853  002.290  002.290: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/compiler/latexmk.vim
198.243  000.233  000.233: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/log.vim
198.885  000.205  000.205: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/debug.vim
227.781  000.249  000.249: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/echo.vim
287.088  000.318  000.318: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/qf.vim
287.476  000.289  000.289: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/qf/latexlog.vim
288.506  000.753  000.753: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/toc.vim
289.087  000.473  000.473: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/toc/matchers.vim
289.595  000.401  000.401: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/index.vim
289.949  000.249  000.249: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/labels.vim
290.300  000.234  000.234: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/fold.vim
290.712  000.292  000.292: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/fold/envs.vim
290.987  000.115  000.115: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/fold/cmd_single_opt.vim
291.204  000.088  000.088: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/fold/markers.vim
291.381  000.069  000.069: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/fold/preamble.vim
291.791  000.242  000.242: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/fold/sections.vim
292.185  000.145  000.145: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/fold/cmd_addplot.vim
292.436  000.102  000.102: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/fold/env_options.vim
292.643  000.093  000.093: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/fold/cmd_multi.vim
292.901  000.120  000.120: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/fold/cmd_single.vim
296.558  000.380  000.380: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/cmd.vim
298.151  001.149  001.149: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/complete.vim
322.744  000.112  000.112: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/debug.vim
325.313  002.397  002.397: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/delim.vim
326.319  000.484  000.484: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/doc.vim
328.035  000.085  000.085: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/echo.vim
328.393  000.197  000.197: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/env.vim
328.850  000.254  000.254: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/format.vim
329.150  000.195  000.195: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/imaps.vim
332.940  000.100  000.100: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/include.vim
333.427  000.327  000.327: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/index.vim
333.873  000.268  000.268: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/info.vim
334.123  000.075  000.075: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/kpsewhich.vim
334.503  000.120  000.120: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/matchparen.vim
335.076  000.153  000.153: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/pos.vim
335.911  000.139  000.139: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/misc.vim
336.270  000.192  000.192: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/motion.vim
336.975  000.311  000.311: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/parser.vim
337.209  000.081  000.081: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/paths.vim
337.467  000.112  000.112: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/pos.vim
337.877  000.254  000.254: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/process.vim
338.226  000.145  000.145: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/re.vim
338.495  000.107  000.107: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/scratch.vim
339.019  000.305  000.305: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/text_obj.vim
339.893  000.193  000.193: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/autoload/vimtex/util.vim
344.797  199.356  176.897: sourcing /Users/sheerun/.vim/plugged/vim-polyglot/ftplugin/tex.vim
345.573  000.040  000.040: sourcing /Users/sheerun/.vim/plugged/splitjoin.vim/ftplugin/tex/splitjoin.vim
618.267  119.185: VimEnter autocommands
618.296  000.029: before starting main loop
1520.463  000.215  000.215: sourcing /Users/sheerun/.vim/plugged/vim-airline/autoload/airline/extensions/wordcount/formatters/default.vim
1551.687  000.344  000.344: sourcing /Users/sheerun/.vim/plugged/vim-airline/autoload/airline/async.vim
1589.430  971.575: first screen update
1589.451  000.021: --- VIM STARTED ---
```

**Comment by lervag** [comment]
First, I know nothing of the polyglot build script, so your first comment does not really mean anything to me.

So, the warnings from vimtex are actually quite important. Removing them would mean that relatively essential features will not work, and most people would start to complain and ask what is wrong with vimtex. However, I could accept to add a minor option to allow the messages not to be printed. This setting should _not_ be used by default for users, but could be useful for testing scripts.

Note that not showing warnings is not in itself a good thing. That LaTeX-Box does not show warnings about system properties that will prevent the plugin from working properly is IMHO a bad thing. If you want to use vimtex without all the features, you can disable them as desired. This will also remove the related warnings.

And yes, I am aware that there is a slightly high startup time. This is one of my current concerns, but I still feel that the features provided are worth this delay. It also, of course, only affects LaTeX files. One of the reasons for this delay is that I parse the loaded LaTeX project during initialization in order to set an initial state. This is necessary in order to e.g. provide LaTeX package specific options.

**Comment by sheerun** [comment]
OK then

What I mean that vim-polyglot is meant to provide syntax and indentation support, nothing more.

I could add your plugin and set extra options like `vimtex_complete_enabled = 0`, but it would mean when users install your plugin for full latex support they'd need to explicitly enable these options again, as vim-polyglot would set the defaults to disable these advanced features.

Instead I prefer to cherrypick only parts of packages that are responsible for syntax and indentation, and that's what `build` script tries to do.

Unfortunately I cannot determine subset of directories for your package as:
1. indent support depends on variables set in autoload
2. autoload loads features I don't want to load in vim-polyglot. Also, I'd prefer to even include it, as `autoload` directory is executed for every file type (not only latext) which means that loading of every file type is slowed down a bit

Ideally I'd be able to cherry-pick following directories: `syntax compiler indent after` and everything would work. And then if someone would like to have full latex support then she could install your package with VimPlug.

All to all, not sure if switch to vimtext is worth the effort from your side. 

Maybe setting `let g:polyglot_disabled = ['latex']` in your plugin would help to resolve any clashes with LaTeX-BoX vim-polyglot includes? Even better you could detect that Latex-box is loaded and show a warning that something probably won't work.

**Comment by lervag** [comment]
First, thanks for clearing up for me how polyglot works. I was not aware of the details, and things make more sense now.

In this case, I also agree with your conclusion that it seems not worth the effort to change vimtex to fit the polyglot build script, so I won't. However, I will add a new warning as you suggest which explains how to disable LaTeX-Box if one uses polyglot.

Do you have a surefire way of detecting polyglot?

**Comment by sheerun** [comment]
it's the issue with latex-box itself, and not vim-polyglot? in this case you need to recognize latex-box instead, probably by reading one of the variables it sets.

**Comment by lervag** [comment]
Thanks, I've found a way that seems good. Just need to test it some more before I push. In any case, thanks for the discussion. I think you could close this issue now.

**Comment by lervag** [comment]
I'm now adding a warning if LaTeX-Box is detected, and an additional hint if vim-polyglot is detected as well. The warnings look like this:

```
vimtex: Conflicting plugin detected: LaTeX-Box
        vimtex does not work as expected when LaTeX-Box is installed!
        Please disable or remove it to use vimtex!
vimtex: LaTeX-Box is included with vim-polyglot and may be disabled with:
        let g:polyglot_disabled = ['latex']
```

**Comment by sheerun** [comment]
I'm glad you've resolved it
