### ISSUE TITLE
VB.NET syntax highlighting not activated by default

### ISSUE THREAD

**Issue by Cheeser12** [sheerun/vim-polyglot#243]
I know, it's VB. But I decided to test it and it doesn't look like polyglot activates the [VB.NET plugin](https://github.com/vim-scripts/vbnet.vim) automatically; the plugin uses `vbnet` as the syntax option, but when you open a `.vb` file, vim is still using the `vb` syntax option.

`ftdetect/polyglot.vim` is not setting any syntax option:
```vim
augroup filetypedetect
" vbnet:vim-scripts/vbnet.vim
augroup END
```

I believe (not knowing much vim-script) that this should be:

```vim
augroup filetypedetect
" vbnet:vim-scripts/vbnet.vim
au BufRead,BufNewFile *.vb set filetype=vbnet
augroup END
```

**Comment by sheerun** [comment]
I've added it manually but ideally you could try to add it to the upstream project :)
