### ISSUE TITLE
Error when opening .erb file (ruby templating)

### ISSUE THREAD

**Issue by giganteous** [sheerun/vim-polyglot#247]
Hi,

I encountered an issue when opening a .erb file; it was hard to get hold of the error in a buffer for which I'd like a suggestion, but here it is:

```
Error detected while processing .vim/plugged/vim-polyglot/syntax/ruby.vim:
line  115:
E59: invalid character after \@
E475: Invalid argument: rubyASCIICode "\%(\w\|[]})\"'/]\)\@1<!\%(?\%(\\M-\\C-\|\
\C-\\M-\|\\M-\\c\|\\c\\M-\|\\c\|\\C-\|\\M-\)\=\%(\\\o\{1,3}\|\\x\x\{1,2}\|\\\=\S\)\)"
```

Seems to still be present after updating to the latest using PlugUpdate. Let me know if you need more details.

**Comment by sheerun** [comment]
I can't reproduce. Could you update once more? Is it still happening could you post .erb file?
