### ISSUE TITLE
Redundant menu item in gVim

### ISSUE THREAD

**Issue by webhive** [sheerun/vim-polyglot#249]
After this pugin installed I got a redundant menu item 

![redundant-menu](https://user-images.githubusercontent.com/1154997/32848374-5bdd6a5c-ca3d-11e7-8aa9-486c5292431a.png)

To get rid of it just need to comment this line https://github.com/sheerun/vim-polyglot/blob/27903c5b8656c796564ef073c1ebe77a2f0154e1/ftdetect/polyglot.vim#L301

I think this menu item is mistake and should not be displayed there.

**Comment by sheerun** [comment]
For now I'll remove this plugin. @Armavica if you'd like me to reintroduce it, please contribute upstream removal of this side effect, thanks :)
