### ISSUE TITLE
Adds 17 seconds to startup time

### ISSUE THREAD

**Issue by partounian** [sheerun/vim-polyglot#250]
Using https://github.com/bchretien/vim-profiler to profile neovim startup time and running about 10 tests I can see it averages adding about 17 seconds of load time. I understand if this is what it must be as it is an irreplaceable plugin, but the README is incorrect with the statement "It won't affect your startup time".
 
macOS 10.13.1 (newest stable)
neovim 0.2.1
python2 and python3 neovim 0.2.0

Test Setup:
Dotfiles as such https://github.com/partounian/dotfiles/tree/master/nvim/config
run `vim-profiler.py -r 10 nvim`

**Comment by sheerun** [comment]
What is exactly your test setup and output? What is the file you're trying to open? 17 seconds is too much for anything, but please mind that vim-polyglot will slow down load time a little bit for each file type individually (e.g. when loading .slim file vim will need to load slim syntax, obviously).

**Comment by sheerun** [comment]
btw. 17 seconds seems to be aggregated amount so slowdown is probably in a matter of milliseconds, not second. Also please notice I write in the readme: "To be completely honest, concatenated ftdetect script takes around 3ms to load.", which potentially could went little bit up since I wrote it.

**Comment by sheerun** [comment]
Here's startup log as measured with `vim --startuptime startup.log`: https://gist.github.com/sheerun/5c89eda37d4138fb97a21161aeb4d835

As you can see loading vim-polyglot takes 17ms which is indeed greather than 3ms I write about in the readme, but far less than 17 seconds. Of course if you run vim 17000 times it adds up to 17 seconds. I'll edit the README to tell 17ms instead of 3ms.

**Comment by partounian** [comment]
Here's my startup.log https://gist.github.com/partounian/47893da97c2a5418b1103ea7382a7f70

I have updated the OP with the test setup.

**Comment by sheerun** [comment]
Vim-polyglot takes 14ms  (not 17 seconds) to load on your computer, as expected. 99% of time is consumed by other plugins, noticably half a second by persistent-undo.vimrc

**Comment by partounian** [comment]
Thank you. I need to make a note that the time is ms not seconds haha my mistake.

**Comment by msva** [comment]
btw, @sheerun sorry for necroposting (I preferred to write here to not duplicate the issues), but can you advice me, please, what am I doing wrong, if polyglot takes about 60+ms drom startuptime in total:

```ShellSession
$  grep polyglot startup.log
020.546  000.017  000.017: sourcing /home/mva/.local/share/nvim/site/pack/packer/start/vim-polyglot/filetype.vim
021.644  000.039  000.039: sourcing /home/mva/.local/share/nvim/site/pack/packer/start/vim-polyglot/ftdetect/polyglot.vim
049.683  029.938  029.480: sourcing /home/mva/.local/share/nvim/site/pack/packer/start/vim-polyglot/autoload/polyglot/init.vim
049.711  030.226  000.288: sourcing /home/mva/.local/share/nvim/site/pack/packer/start/vim-polyglot/filetype.vim
057.288  003.353  003.353: sourcing /home/mva/.local/share/nvim/site/pack/packer/start/vim-polyglot/plugin/polyglot.vim
078.686  000.032  000.032: sourcing /home/mva/.local/share/nvim/site/pack/packer/start/vim-polyglot/filetype.vim
079.657  000.022  000.022: sourcing /home/mva/.local/share/nvim/site/pack/packer/start/vim-polyglot/filetype.vim
080.981  000.030  000.030: sourcing /home/mva/.local/share/nvim/site/pack/packer/start/vim-polyglot/filetype.vim
214.224  000.227  000.227: sourcing /home/mva/.local/share/nvim/site/pack/packer/start/vim-polyglot/plugin/polyglot.vim
257.451  001.261  001.261: sourcing /home/mva/.local/share/nvim/site/pack/packer/start/vim-polyglot/autoload/polyglot/sleuth.vim
```

as I can see, greatest time consumers are `autoload/polyglot/init.vim` and `/filetype.vim`.
And I have totally no idea why, and how can I fix that :shrug:

**Comment by sheerun** [comment]
@msva Could you add new issue? I'll look into it
