### ISSUE TITLE
better markdown syntax

### ISSUE THREAD

**Issue by ZSaberLv0** [sheerun/vim-polyglot#251]
in my opinion, https://github.com/rhysd/vim-gfm-syntax has better syntax than current one (`vim-markdown`)

for example:

* generally `vim-gfm-syntax` has better compatibility for my case,
    for example, this would cause error syntax in `vim-markdown`

    ```
    [http://aaa.com](http://aaa.com)
    ```

* fenced code block syntax highlight support

    `vim-markdown`'s latest version also support this, but this repo (`vim-polyglot`) doesn't

**Comment by sheerun** [comment]
It is also worse in few important ways:

- doesn't highlight html blocks in markdown
- doesn't properly handle nested inline code blocks like

```  * [`left` alignment](#left-alignment)```
- Doesnt' properly highlight multiline code blocks as strings
- requires `plugin` directory that is loaded when opening file of any extension in vim (a big no-no for vim-polyglot)

I'd suggest contributing changes you like to the current upstream plugin: plasticboy/vim-markdown
