### ISSUE TITLE
Errors when opening vim related to LaTeXtoUnicode#Refresh, LaTeXtoUnicode#Init & autocmd

### ISSUE THREAD

**Issue by ahmedelgabri** [sheerun/vim-polyglot#254]
```
Error detected while processing FileType Auto commands for "*":
E117: Unknown function: LaTeXtoUnicode#Refresh
```

These are the lines that are throwing errors https://github.com/sheerun/vim-polyglot/blob/11f53253ad9fd0cd3e7a44ed9f8c80a4f265b46e/ftdetect/polyglot.vim#L506-L507

Also, I'm getting errors for `LaTeXtoUnicode#Init` too

**Comment by stellarhoof** [comment]
I get the same. For me the problem is that `LatexToUnicode#*` are autoload functions from the `julia` filetype and I disabled `julia`

**Comment by sheerun** [comment]
Could you update vim-polyglot and send here example file that causes this issue when opening? If it doesn't happen immediately after opening, please post steps that lead to reproducing this issue.

**Comment by ahmedelgabri** [comment]
@sheerun it doesn't matter which file type.

Steps:

1. Updated `vim-polyglot` & exit `vim`
2. open vim or neovim (it doesn't matter which file type), `vim` or `nvim` or `vim foo` or `nvim foo`, etc... all will produce the same error

```
Error detected while processing BufEnter Auto commands for "*":
E117: Unknown function: LaTeXtoUnicode#Refresh
```

Here is an recording https://asciinema.org/a/rvkHQY0Gum2gJyAOvClDXX4Qo

And here are my settings for `vim-polyglot`:

```vim
Plug 'sheerun/vim-polyglot'
" These are enabled, the rest is disabled. Maybe I should install them separately instead
" https://github.com/sheerun/vim-polyglot#language-packs
" https://github.com/jackfranklin/dotfiles/blob/6c0ba96b20f70d63a8dbb2652d8ebe2241355552/vim/vimrc#L3-L22
" \ 'ansible', Needed for Jinja2?!
" \ 'clojure',
" \ 'coffee-script',
" \ 'dockerfile',
" \ 'elm',
" \ 'git',
" \ 'go',
" \ 'graphql',
" \ 'html5',
" \ 'javascript',
" \ 'json',
" \ 'jsx',
" \ 'lua',
" \ 'markdown',
" \ 'php',
" \ 'python-compiler',
" \ 'python',
" \ 'ruby',
" \ 'scss',
" \ 'tmux',
" \ 'twig',
" \ 'yaml',
let g:polyglot_disabled = [
      \ 'apiblueprint',
      \ 'applescript',
      \ 'arduino',
      \ 'asciidoc',
      \ 'blade',
      \ 'c++11',
      \ 'c/c++',
      \ 'caddyfile',
      \ 'cjsx',
      \ 'cql',
      \ 'cryptol',
      \ 'crystal',
      \ 'css',
      \ 'cucumber',
      \ 'dart',
      \ 'elixir',
      \ 'emberscript',
      \ 'emblem',
      \ 'erlang',
      \ 'fish',
      \ 'glsl',
      \ 'gnuplot',
      \ 'groovy',
      \ 'haml',
      \ 'handlebars',
      \ 'haskell',
      \ 'haxe',
      \ 'i3',
      \ 'jasmine',
      \ 'jst',
      \ 'julia',
      \ 'kotlin',
      \ 'latex',
      \ 'less',
      \ 'liquid',
      \ 'livescript',
      \ 'mako',
      \ 'mathematica',
      \ 'nim',
      \ 'nix',
      \ 'nginx',
      \ 'objc',
      \ 'ocaml',
      \ 'octave',
      \ 'opencl',
      \ 'perl',
      \ 'pgsql',
      \ 'plantuml',
      \ 'powershell',
      \ 'protobuf',
      \ 'pug',
      \ 'puppet',
      \ 'purescript',
      \ 'qml',
      \ 'r-lang',
      \ 'racket',
      \ 'ragel',
      \ 'raml',
      \ 'rspec',
      \ 'rust',
      \ 'sbt',
      \ 'scala',
      \ 'slim',
      \ 'slime',
      \ 'solidity',
      \ 'stylus',
      \ 'swift',
      \ 'sxhkd',
      \ 'systemd',
      \ 'terraform',
      \ 'textile',
      \ 'thrift',
      \ 'tomdoc',
      \ 'toml',
      \ 'typescript',
      \ 'vala',
      \ 'vbnet',
      \ 'vcl',
      \ 'vm',
      \ 'vue',
      \ 'xls',
      \ 'yard'
      \ ]
```

**Comment by sheerun** [comment]
It's not necessary to disable plugins as they don't affect load time until you open such a such filetype. If the slowdown occurs, it is considered a bug in vim-polyglot.

As for your issue, it seems julia plugin does something that I don't accept in vim-polyglot: `autocmd FileType *`  and `autocmd BufEnter *` that executes on every file and buffer open..
https://github.com/JuliaEditorSupport/julia-vim/blob/master/ftdetect/julia.vim

I'm going to disable ftdetect parts of all plugins that do such thing, it should resolve this issue

**Comment by sheerun** [comment]
@ahmedelgabri Please upgrade to v3.3.1 and check if it solves your issue

I also encourage you to remove all polyglot_disabled as they should not matter as far as performance is considered

**Comment by ahmedelgabri** [comment]
@sheerun last update looks like it fixed the issue yes, thanks! And I'll also remove `polyglot_disabled` too
