### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by andythedandyone** [sheerun/vim-polyglot#260]
I have absolutely no idea how to install this package seemed like the readme is vague on that compared to other packages readme about the installation process.
Can anyone point out on how to install this with Pathogen, Vundle, etc.
thanks.

**Comment by sheerun** [comment]
I've added an example in the readme

**Comment by andythedandyone** [comment]
Would that work with Vundle as well?

Plugin 'sheerun/vim-polyglot'
