### ISSUE TITLE
Swift file file detect not work

### ISSUE THREAD

**Issue by happiness9721** [sheerun/vim-polyglot#261]
vim version: 8.0.1400
vim-polyglot version: v3.3.1

When I update from v3.2.0 to v3.3.1, this feature is broken.

**Comment by lasseebert** [comment]
It is fixed in master (commit https://github.com/sheerun/vim-polyglot/commit/bfc6ed9fbafc0758aaab228df70a3656368d8497)

Related issue: https://github.com/sheerun/vim-polyglot/issues/262

**Comment by happiness9721** [comment]
thanks for reply, it works now🤘

**Comment by sheerun** [comment]
This might happen for hashbang file detection, but we have separate issue for it here: #274
