### ISSUE TITLE
Potential conflict with other language-specific syntax & indentation support plugins?

### ISSUE THREAD

**Issue by khashf** [sheerun/vim-polyglot#263]
Hi sheerun, 

* Would it conflict with other other language-specific syntax & indentation support plugins such as [haskell-vim](https://github.com/neovimhaskell/haskell-vim), [rust.vim](https://github.com/rust-lang/rust.vim), etc.?

 * Is the just as about the same as I install those plugins separately?

Thank you!

**Comment by sheerun** [comment]
Depending on plugin implementation you can install it either before or after vim-polyglot and it'll override the settings. If there's really a conflick, you can disable single language with flag, please see the README
