### ISSUE TITLE
No PHP indent file? 

### ISSUE THREAD

**Issue by taq** [sheerun/vim-polyglot#271]
Hey, I noticed that there is no PHP indent file, after saving a file with a PHP lint (and some customizations) and it complained about the indentation. I'd like to make one, is there a basic guideline or is about choosing another language indent file and use it as base?

Thanks!

**Comment by sheerun** [comment]
The language pack for PHP we use doesn't have indent files: https://github.com/StanAngeloff/php.vim

You can suggest better one if you want, but it should be simple and include mostly syntax, indent, and compiler configuration. Advanced IDE-like plugins aren't welcome in vim-polyglot to avoid bloat.

**Comment by taq** [comment]
Seems that on the language pack another plugin is specified to use with indent: https://github.com/2072/PHP-Indenting-for-VIm

Will try to install that plugin and see if works well, thanks!

**Comment by CH-DanReif** [comment]
Resolved by #294 ?

**Comment by taq** [comment]
Seems so, thanks!
