### ISSUE TITLE
Idea: Generate code to turn on foldmethod=syntax when available

### ISSUE THREAD

**Issue by idbrii** [sheerun/vim-polyglot#273]
polyglot includes a lot of syntax files and some of them define folding. But it's hard to tell how to take advantage of this folding since vim doesn't seem to expose a way to tell if the current syntax supports folding.

It would be nice to have something like `polyglot#try_use_syntax_folds()` that sets foldmethod=syntax if the current filetype supports it. Or `g:polyglot_enable_syntax_folds=1` that creates autocmds to set foldmethod=syntax for supported filetypes. Since polyglot processes a bunch of filetype plugins and does some script building, maybe it makes sense for polyglot to generate this code.

I wrote something like the first option [here](https://github.com/idbrii/daveconfig/blob/a2f5331f009d77331440d73d75bba0f839d7dbbe/multi/vim/autoload/david/indent.vim#L1-L30).

It generates [a file that looks like this](https://github.com/idbrii/daveconfig/blob/a2f5331f009d77331440d73d75bba0f839d7dbbe/multi/vim/autoload/david/gen/foldfiletypes.vim):

	let s:foldable["apiblueprint"] = 1
	" ...
	let s:foldable["zsh"] = 1

	function! david#gen#foldfiletypes#has_foldable_syntax(ft)
		return get(s:foldable, a:ft, 0)
	endf

Which I use kind of like this:

	function! david#indent#try_use_syntax_folds()
		" indent is my default foldmethod
		if &l:foldmethod == 'indent'
			if len(&filetype) > 0
				if david#gen#foldfiletypes#has_foldable_syntax(&filetype)
					setlocal foldmethod=syntax
				endif
			endif
		endif
    endf
	autocmd BufNewFile,BufRead * call david#indent#try_use_syntax_folds()

The downside of incorporating this into polyglot is that it wouldn't (shouldn't?) include the syntax files shipped with vim or a user's additional syntax files.

**Comment by sheerun** [comment]
I think it's fine to incorporate both in vim-polyglot (list of foldable syntaxes and automatically setting foldmethod=syntax if syntax supports it. Unfortunately the build script is in bash, not vim-script, maybe you'd like to prepare a PR? Only changes in `./build` script are necessary.

**Comment by sheerun** [comment]
btw. sometimes filetype isn't what vim-polyglot has as a key in configuration (e.g. javascript+jsx)

**Comment by sheerun** [comment]
After thinking more about this it isn't something vim-polyglot should do. It would require me to review each plugin to see if it supports folding or not and write proper code for enabling it. Better approach would be to open PRs to plugins so they automatically set `foldmethod=syntax` given some agreed on global variable like `let g:auto_foldmethod=1`
