### ISSUE TITLE
Build Script Name Change

### ISSUE THREAD

**Issue by ratorx** [sheerun/vim-polyglot#275]
There is a conflict between the build script in this plugin and the build folder of [onedark.vim](https://github.com/joshdick/onedark.vim) when using the [dein.vim](https://github.com/Shougo/dein.vim) plugin manager. It causes plugin updates to fail.

Would it be possible to rename it to something else to fix this?

**Comment by sheerun** [comment]
When you install plugins, you put each one in separate directory. I don't get how you  can get conflict.

Maybe try to use package manager like vim-plug?

**Comment by ratorx** [comment]
I managed to fix this for myself, so I'll close the issue. The file conflict still remains, but apparently it can be circumvented by specifying this plugins build script as a build script (an optional argument).

Although the plugins are initially cloned into different directories, at some point, the plugin manager tries to speed up loading by copying from the plugin directories into a generated init directory.

This fails when trying to copy the build script and replace the build folder of the other plugin with it.
