### ISSUE TITLE
Add support for LilyPond files

### ISSUE THREAD

**Issue by dread-uo** [sheerun/vim-polyglot#278]
The official vim files for lilypond are distributed with lilypond itself, and adding them to your setup usually means doing some `rtp += [...]`. It would be nice to have them supported here :)

**Comment by sheerun** [comment]
I think it's fine but someone would need to create github repository with vim plugin and maintain it, if anyone badly wants this syntax, please do so

**Comment by anowlcalledjosh** [comment]
@sheerun I have created a repository for Lilypond's Vim plugin files at https://github.com/anowlcalledjosh/vim-lilypond, with the files from the official Lilypond distribution. I intend to keep it up to date as new Lilypond versions are released, though obviously it's hard to demonstrate that when I've only just created it :)

Would you consider adding it to vim-polyglot?

**Comment by sheerun** [comment]
sure
