### ISSUE TITLE
Highlight Python function/method calls

### ISSUE THREAD

**Issue by silenc3r** [sheerun/vim-polyglot#283]
It would be nice if function and method calls be highlighted by default as is done in most other editors.

It can be achieved with something like that:

        syntax match pythonFunction /\v([^[:cntrl:][:space:][:punct:][:digit:]]|_)([^[:cntrl:][:punct:][:space:]]|_)*\ze(\s?\()/

Here's how it looks like:

before
![screenshot from 2018-03-16 11-59-46](https://user-images.githubusercontent.com/442039/37517577-3ab6a3dc-2912-11e8-8126-3f13207e5ebe.png)
after
![screenshot from 2018-03-16 11-59-28](https://user-images.githubusercontent.com/442039/37517596-41363efc-2912-11e8-8f82-e2ead8e5993c.png)

**Comment by CH-DanReif** [comment]
This belongs in https://github.com/vim-python/python-syntax .  Once it's updated there, open an issue here and we'll rebuild and pull in the changed version.  If @vim-python won't accept your update to make this change, the next step is to fork that repo, make the change in your fork, and then make a PR to change https://github.com/sheerun/vim-polyglot/blob/e2404449e4f961c5e6c0e2689078612b36d776c2/build#L220 .

Either way, there's not much I can do about this at the moment, here.

**Comment by antoinemadec** [comment]
@silenc3r @CH-DanReif , for info, this has been added in python-syntax after https://github.com/vim-python/python-syntax/commit/6ce77d0013690b8b44a8d088ba4b54ba549ae98e

More info in the pull request: https://github.com/vim-python/python-syntax/pull/63
