### ISSUE TITLE
vim-json cannot be disabled through vim-polyglot

### ISSUE THREAD

**Issue by thejohnfreeman** [sheerun/vim-polyglot#284]
I tried to set `let g:polyglot_disabled = ['json']` in my `.vimrc`, both before and after loading vim-polyglot. Then I open a JSON file, remove a double quote, and the string value goes black. This behavior only stops when I set `let g:vim_json_warnings = 0`. (The real giveaway is that filetype is `json` when it should be empty.)

**Comment by CH-DanReif** [comment]
The plugin appears to be gated properly (see https://github.com/sheerun/vim-polyglot/blob/master/syntax/json.vim).  Are you sure the syntax you're seeing is from polyglot?  An easy test: edit polyglot's `json.vim` to be empty.  Do you still see the behavior you describe here?

**Comment by thejohnfreeman** [comment]
Yes, I still see it, but it also goes away if I set `let g:vim_json_warnings = 0` and nothing else, even if vim-polyglot is missing from my `~/.vim`. I guess I have no idea what is going on.

**Comment by CH-DanReif** [comment]
@thejohnfreeman In that case, you have another copy of `json.vim` floating around somewhere, most likely.

One handy hack:

```
vim --startuptime "$(tf="$(mktemp)"; echo "$tf"; echo "$tf" >&2)" -c 'quit' foo.json
```

Then look in the tempfile that was printed out; you should see several lines like:
```
060.883  000.115  000.115: sourcing /usr/share/vim/vim80/ftplugin/json.vim
```

That'll tell you where it's finding that file.  Working backwards, you can see where _that_ is being referenced from, etc.

With that, closing this issue.  If it's reproducible without any content in the `vim-polyglot` syntax file, then disabling polyglot's copy of the file won't really do much; working as expected.
