### ISSUE TITLE
Tests fail to parse ftdetect lines using {} globs correctly

### ISSUE THREAD

**Issue by idbrii** [sheerun/vim-polyglot#287]
I noticed that the [tests are giving some weird output](https://travis-ci.org/sheerun/vim-polyglot/builds/332940121?utm_source=github_status&utm_medium=notification):

    should parse {build file
    should parse profile}.boot file
    should parse test.{js file
    should parse es6} file
    should parse test.{md file
    should parse mdwn} file
    should parse test.{md file
    should parse mdwn}.{des3 file
    should parse desx} file
    should parse {. file
    should parse }tmuxtest.conftest file

running the shell line from loading_spec.rb:

    cat ftdetect/polyglot.vim | grep '^au' | tr "\t" ' ' | cut -d ' ' -f 3 | grep -v / | grep -v '^\*$' | grep -v '^$'

    *.clj,*.cljs,*.edn,*.cljx,*.cljc,{build,profile}.boot
    *.{js,mjs,jsm,es,es6},Jakefile
    *.{md,mdown,mkd,mkdn,markdown,mdwn}
    *.{md,mdown,mkd,mkdn,markdown,mdwn}.{des3,des,bf,bfa,aes,idea,cast,rc2,rc4,rc5,desx}
    {.,}tmux*.conf*

Looks like it's not parsing those lines correctly. You probably only need one expansion of each {} since the test is for errors and not filetype detection?

**Comment by sheerun** [comment]
For now I've rejected all file names with non alphanumeric characters
