### ISSUE TITLE
CSS Variables Support

### ISSUE THREAD

**Issue by arante** [sheerun/vim-polyglot#289]
I recently tried using my vim editor to edit a CSS file with CSS Variables. I noticed that vim-polyglot does not have the complete support for the said CSS feature.

For example:

```
:root {
    --primary-color: red;
}
```

Please, update your feature support for the vanilla CSS, Sass, and Less languages. I would appreciate it so much. Thank you!

**Comment by sheerun** [comment]
Sorry you need to contact upstream plugin, vim-polyglot just gathers them
