### ISSUE TITLE
slow loading of markdown files

### ISSUE THREAD

**Issue by phorust** [sheerun/vim-polyglot#290]
Running `nvim README.md --startuptime vim.log` in my repo phorust/phorust.github.io gives me a 15s startup time:

```
287.407  000.296  000.296: sourcing /Users/phorust/.vim/plugged/ale/ale_linters/markdown/write-good.vim
5175.369  000.024  000.024: sourcing /Users/phorust/.vim/plugged/html5.vim/ftplugin/html.vim
...
5254.662  000.046  000.046: sourcing /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/syntax/markdown.vim
10328.471  000.027  000.027: sourcing /Users/phorust/.vim/plugged/html5.vim/ftplugin/html.vim
...
10404.185  000.020  000.020: sourcing /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/syntax/markdown.vim
15331.148  000.202  000.202: sourcing /Users/phorust/.vim/plugged/ale/autoload/ale/pattern_options.vim
```

It looked to be an issue with ale so I opened w0rp/ale/issues/1478, but after commenting out polyglot from my vimrc, my startup times returned back to normal. I recently upgraded nvim and ran a fresh +PlugUpgrade. Also experiencing similar slowdown in vim.

Rest of startup time here:
https://gist.github.com/phorust/2855d4915747b37bc4790663d0b451fc

**Comment by dylan-chong** [comment]
@alecdwm Thank you! Disabling sleuths save three hundred milliseconds i start up time! Is a shame that we can't tell that it's this plugin from the start up time log

**Comment by seeARMS** [comment]
vim-polygot is slow loading markdown files for me too, and I don't use vim-sleuth.

**Comment by idbrii** [comment]
This issue can be resolved by updating polyglot to use the latest version of vim-markdown.

**Comment by dylan-chong** [comment]
@idbrii  thank you for your hard work investigating and fixing this issue :)

**Comment by frioux** [comment]
Even if I run `./build` in a checkout of the latest polyglot I still find that markdown files are really slow to load.  You can see the time being taken in this small bit of a profile:

```
FUNCTION  <SNR>4_SynSet()
    Defined: /usr/share/vim/vim81/syntax/synload.vim line 33
Called 7 times
Total time:   0.392857
 Self time:   0.011350

count  total (s)   self (s)
                              " clear syntax for :set syntax=OFF  and any syntax name that doesn't exist
    7              0.003539   syn clear
    7              0.000043   if exists("b:current_syntax")
                                unlet b:current_syntax
    7              0.000009   endif
                            
    7              0.000034   let s = expand("<amatch>")
    7              0.000016   if s == "ON"
                                " :set syntax=ON
                                if &filetype == ""
                                  echohl ErrorMsg
                                  echo "filetype unknown"
                                  echohl None
                                endif
                                let s = &filetype
    7              0.000012   elseif s == "OFF"
                                let s = ""
    7              0.000005   endif
                            
    7              0.000010   if s != ""
                                " Load the syntax file(s).  When there are several, separated by dots,
                                " load each in sequence.
   14              0.000248     for name in split(s, '\.')
    7   0.388787   0.007280       exe "runtime! syntax/" . name . ".vim syntax/" . name . "/*.vim"
   14              0.000015     endfor
    7              0.000004   endif
```

**Comment by idbrii** [comment]
@frioux 
I'd guess it's because it loads a syntax file for each code block in your markdown. For a quick test, try `let g:vim_markdown_fenced_languages = {}` in your vimrc. I think that should disable the corresponding code in vim-markdown.

You're profiling vim code, so it doesn't reveal that anything in polyglot is causing problems.

Do you get the slowdown if you have a blank vimrc and only polyglot installed?

What if you remove vim-markdown from polyglot?  Then report a bug (including your markdown file's contents) on vim-markdown.

**Comment by sheerun** [comment]
vim-polyglot now uses newest vim-markdown :) thank you!

**Comment by sheerun** [comment]
Hmm, OK I've re-read that some people still have this issue, reopening

**Comment by lytedev** [comment]
I'm seeing this issue when I open multiple markdown files, the Nth time I enter a buffer, I see N^2 load times.

**Comment by idbrii** [comment]
@lytedev Does that occur if you remove polyglot and install vim-markdown?

**Comment by lytedev** [comment]
@idbrii It does! I guess it's safe to say that this bug is with `vim-markdown`. Good call. I'll file an issue over there.
