### ISSUE TITLE
Problem with vue files

### ISSUE THREAD

**Issue by tyok** [sheerun/vim-polyglot#292]
Hi, thanks for the convenient plugin. I've been using this for about two years without problem.

Recently I've been trying vue.js and stumbled upon posva/vim-vue#69 (the <script> tag is highlighted incorrectly). As one of the commenter suggests, disabling vim-polyglot fix the problem. Setting `let g:polyglot_disabled = ['vue', 'coffee', 'javascript', 'html'] and installing separate plugins for each doesn't seem to fix it.

Any idea what could be causing it?

**Comment by sheerun** [comment]
Sorry no idea, this seems like an upstream issue, not vim-polyglot's

**Comment by tyok** [comment]
Sorry, I know it was ages ago but I want to mention that disabling `coffee-script` (not `coffee`) fixed it:
```
let g:polyglot_disabled = ['coffee-script']
```

In case anyone has the same problem.

**Comment by willchao612** [comment]
> Sorry, I know it was ages ago but I want to mention that disabling `coffee-script` (not `coffee`) fixed it:
> 
> ```
> let g:polyglot_disabled = ['coffee-script']
> ```
> 
> In case anyone has the same problem.

That is helpful, though the color is still a bit unpleasant.
