### ISSUE TITLE
PHP syntax maintainer not interested in fixing bugs. Please move to another fork.

### ISSUE THREAD

**Issue by dsifford** [sheerun/vim-polyglot#294]
See https://github.com/StanAngeloff/php.vim/issues/81

I'll create a fork and maintain it for now if need be. I also maintain the vim dracula theme.

**Comment by sheerun** [comment]
I'd rather avoid such case, let's see if there's a way to resolve this differently first.

**Comment by sheerun** [comment]
@dsifford It seems this plugin has hard focus on backward compatibility. Vim-polyglot is more about updates so I think it's reasonable to create different repository for php synax. Idaelly it would use the one that is shipped with newest vim: https://jasonwoof.com/gitweb/?p=vim-syntax.git;a=blob;f=php.vim;hb=HEAD

Maybe you could prepare this repository? It can be from scratch, no need to fork.

**Comment by dsifford** [comment]
Sure. I'll try to get something started when I get some extra free time.

Ideally, I'd like to hand off the maintenance to someone else more interested in the language if possible though. I don't particularly like PHP. I'm mostly just a uniformity nut when it comes to syntax highlighting.

I'll chime back here with updates once I'm able to get something started / halfway decent :+1:

**Comment by sheerun** [comment]
Closing this for now
