### ISSUE TITLE
Consider switching from leafgarland/typescript-vim to HerringtonDarkholme/yats.vim

### ISSUE THREAD

**Issue by dsifford** [sheerun/vim-polyglot#295]
Hello again :wave: 

Not sure if these sorts of issues are appropriate here (if not, please let me know), but I was wondering if you might consider swapping out the current typescript syntax for [HerringtonDarkholme/yats.vim](https://github.com/HerringtonDarkholme/yats.vim).

I've used both recently and while skimming through and fixing highlighting for the theme I maintain, it immediately became clear that yats was much more detailed and scrutinized.

Thanks for considering!

**Comment by sheerun** [comment]
Sure. Maybe you want collaborator access and do it yourself?

**Comment by dsifford** [comment]
Happy to collaborate if help is needed.

For this particular issue: disregard for now. The syntax is pretty great, but it unfortunately has some performance issues. 

I'll revisit this down the road if anything changes.
