### ISSUE TITLE
vim-go commands not working

### ISSUE THREAD

**Issue by raviqqe** [sheerun/vim-polyglot#296]
Commands from `vim-go` like `GoBuild` doesn't work.

**Comment by devinalvaro** [comment]
If I'm not wrong, `vim-polyglot` only integrates syntax, compiler, and indent from `vim-go`. You can look it up in the [README](https://github.com/sheerun/vim-polyglot#language-packs), at go section.

**Comment by sheerun** [comment]
Yes, for more advanced go features you need to install appropriate plugin. We just handle syntax indentation and compilers.
