### ISSUE TITLE
Suggestion: Remove the custom yaml syntax and extras

### ISSUE THREAD

**Issue by dsifford** [sheerun/vim-polyglot#297]
Hi there,

Hoping I might be able to add a quick suggestion to the suggestion bin to completely remove the yaml syntax and extras that are currently provided in favor of the vim builtins.

If you compare the [builtin yaml syntax](https://github.com/vim/vim/blob/master/runtime/syntax/yaml.vim) to the [stephpy/vim-yaml syntax](https://github.com/stephpy/vim-yaml/blob/master/after/syntax/yaml.vim#L1:54), you'll notice that the stephpy variant is only a small monkey patch that is meant to be laid out over top of the builtin syntax. 

Even more important: The monkey patches are all supported already in the builtin syntax file, so there is literally no reason to even have it.

Thanks for considering :+1:

**Comment by dsifford** [comment]
@sheerun Thank god you're around to maintain a level head, because that is a gooooooood point that I hadn't even considered.

Thanks for the info. I'll dive into #237 here later this afternoon and take a look.

I'm wondering if there might be a way to implement a standardized set of tests using vader or something that could be ran on all syntax updates through CI that might make managing some of these backwards compat issues more streamlined.

I just finished up my winter semester and have about a month of downtime before the next one begins. So, maaaaaybe if I'm feeling particularly bold I'll see if I can look into getting something like that fleshed out and shoot a PR over... (stressing the word maybe).

**Comment by sheerun** [comment]
There are already some CI tests but they just check if each syntax is able to load. It's really hard to catch errors like in #237 so not sure if it's possible to create any more generalized tests. When I change something I just fiddle a bit with language and if everything seems OK I commit. As soon as someone complains I rollback instead of fixing. It works so far.

**Comment by dsifford** [comment]
Noted. Thanks for clarifying.

Got the contribution invitation. Thanks. I'll try to dig into this specific issue later this week. :+1:

**Comment by sheerun** [comment]
Closing this feel free to open another issue
