### ISSUE TITLE
Golang support is broken by config changes from upstream

### ISSUE THREAD

**Issue by CH-DanReif** [sheerun/vim-polyglot#299]
https://github.com/fatih/vim-go/commit/366996662f9cea2361b38e5f2217c82040d4caed introduced a new way of controlling config for the go plugin, but our packaging of that results in:

```
Error detected while processing ~/vim-polyglot/syntax/go.vim:
line   66:
E117: Unknown function: go#config#FoldEnable
E15: Invalid expression: go#config#FoldEnable('comment')
E117: Unknown function: go#config#FoldEnable
E15: Invalid expression: go#config#FoldEnable('comment')
```

**Comment by sheerun** [comment]
I think it's best to first remove go from vim-polyglot and then try to re-introduce it, when time allows
