### ISSUE TITLE
Blade indent not work after update

### ISSUE THREAD

**Issue by muziqiushan** [sheerun/vim-polyglot#304]

**Comment by sheerun** [comment]
It seems like upstream issue, please post this issue to jwalton512/vim-blade

**Comment by muziqiushan** [comment]
![image](https://user-images.githubusercontent.com/3956434/39903740-4fe0f764-5507-11e8-830a-25599fe49993.png)

**Comment by muziqiushan** [comment]
commmit 30c87b73deff05c7dd9590228c0615a3299f39ff is ok,but the latest version  please reopen it
