### ISSUE TITLE
Add asymptote support

### ISSUE THREAD

**Issue by minijackson** [sheerun/vim-polyglot#319]
Asymptote is a language for vector graphics creation. Website: http://asymptote.sourceforge.net/

Official vim syntax file is here: https://github.com/vectorgraphics/asymptote/blob/master/base/asy.vim

and official ftdetect is here: https://github.com/vectorgraphics/asymptote/blob/master/base/asy_filetype.vim

Thanks for the great work!

**Comment by sheerun** [comment]
Vim support for this woul dneed to be extracted to separate repository with standard structure

**Comment by sheerun** [comment]
If someone needs badly this syntax, please create standalone plugin as github repository
