### ISSUE TITLE
Vim polyglot much slower than using the plugins directly

### ISSUE THREAD

**Issue by cBournhonesque** [sheerun/vim-polyglot#321]
I have a Python file which is roughly lines long.

When I use the vim-polyglot plugin only, adding a new line is extremely slow (maybe 1.5 to 2 seconds of delay).
When I use the following plugins:

- https://github.com/Vimjas/vim-python-pep8-indent.git

- https://github.com/vim-python/python-syntax

the delay is reduced to maybe 0.25 seconds.

I don't understand how that is possible, since those two are the only plugins that vim-polyglot loads for python syntax and indent. Maybe there is an issue where the syntax is computed several times?

For now, I think I am just going to disable vim-polyglot and use the two python plugins separately.

**Comment by cBournhonesque** [comment]
Actually it was the python-pep8-indent plugin that was extremely slow, I was mistaken.

**Comment by sheerun** [comment]
maybe we should remove this plugin then... can you find faster alternative?

**Comment by LnL7** [comment]
The older https://github.com/vim-scripts/indentpython.vim has similar indentation functionality from what I can tell, and doesn't seem to have any performance issues.
