### ISSUE TITLE
Add support for tsx

### ISSUE THREAD

**Issue by farazcsk** [sheerun/vim-polyglot#330]
Hey!

Thanks for the really great language pack. The JSX support is great, would it be possible to get the same support for tsx?

Cheers

**Comment by vincentzhezhang** [comment]
Maybe just add **peitalin/vim-jsx-typescript** to the package?

**Comment by talha131** [comment]
This issues is solved via https://github.com/sheerun/vim-polyglot/pull/318

**Comment by sheerun** [comment]
tsx should now be supported

**Comment by svilenb** [comment]
For me adding jsx into the filetype for .tsx files like in [#318](https://github.com/sheerun/vim-polyglot/pull/318) is nowhere near as good as using something like `ianks/vim-tsx`. Won't it be better if we just had that plugin in the set of language packs @sheerun?

**Comment by sheerun** [comment]
I guess

**Comment by sheerun** [comment]
I'm changing support for jsx in typescript to https://github.com/MaxMEllon/vim-jsx-pretty which seems it has implemented jsx syntax fully instead of half-ass xml parsing :)
