### ISSUE TITLE
GraphQL error in Javascript files

### ISSUE THREAD

**Issue by tonywoode** [sheerun/vim-polyglot#331]
moving here from #303 see https://github.com/sheerun/vim-polyglot/issues/303#issuecomment-411704280

@CH-DanReif:
1) yes its any `*.js` file
2) https://github.com/tonywoode/dotfiles/blob/master/.vimrc
3) 
```
> vim --version
VIM - Vi IMproved 8.1 (2018 May 17, compiled Jul  9 2018 12:39:30)
macOS version
Included patches: 1-72
Compiled by Homebrew
Huge version with MacVim GUI. 
```

thanks

**Comment by CH-DanReif** [comment]
Can you see if you can repro with https://github.com/CH-DanReif/dotfiles/blob/disable-everything/.vimrc active?  I'm not able to.

**Comment by tonywoode** [comment]
with that .vimrc, no error
but vim-polyglot is disabled in that .vimrc
if I re-enable it, and re-enable the basics of vundle so it can load, I get the error

**Comment by sheerun** [comment]
It's been a long time so maybe it's now fixed if you update vim & all plugins including vim-polyglot. I tried to reproduce it once more, but no luck: https://asciinema.org/a/VB0yrocRoeK2SmVjsvN9pGUHW

I guess if someone experiences it, I'd need Dockerfile to reproduce it. It's not possible if you provide just .vimrc, sorry!
