### ISSUE TITLE
How to disable highlighting trailing whitespace ?

### ISSUE THREAD

**Issue by hulucc** [sheerun/vim-polyglot#333]
![image](https://user-images.githubusercontent.com/4343900/44145708-3e5f38da-a0bf-11e8-8ab1-bb1b4a16e7b5.png)

**Comment by maln0ir** [comment]
There are many config variables in the Python syntax file. Just set [this one](https://github.com/sheerun/vim-polyglot/blob/055f7710b65dfa2df52fc0b5be2486ae36ac5751/syntax/python.vim#L55) to `0` in your `vimrc`.
