### ISSUE TITLE
Add language pack for MDX

### ISSUE THREAD

**Issue by trevordmiller** [sheerun/vim-polyglot#342]
MDX is a new language that combines Markdown and JSX. [It's becoming very popular in the JavaScript + React community lately](https://www.npmtrends.com/@mdx-js/loader). Per the discussion in https://github.com/mdx-js/mdx/issues/119, [vim-mdx-js](https://github.com/jxnblk/vim-mdx-js) is going to be the main MDX language pack for Vim. Could it be added to `vim-polyglot` for `.mdx` files?

cc: @jxnblk

**Comment by trevordmiller** [comment]
Although for this to be in `vim-polyglot`, @jxnblk should probably remove https://github.com/jxnblk/vim-mdx-js/blob/4bf61b0728a387a241b48691f5b5adf0b03e1ea2/ftdetect/mdx.vim#L8, so only `.mdx` files are detected as `markdown.mdx` filetype.

**Comment by sheerun** [comment]
For now I've overwritten ftdetect part

**Comment by trevordmiller** [comment]
Awesome! I’m looking forward to this being released. cc @jxnblk

**Comment by sheerun** [comment]
This is released, just update your plugins

**Comment by trevordmiller** [comment]
@sheerun I removed `vim-mdx-js` from my plugins, upgraded my `vim-polyglot` plugin, restarted Vim, and now `.mdx` files are not being recognized correctly. `:set filetype?` in an `.mdx` file shows `filetype=conf`.

**Comment by sheerun** [comment]
Yes I did something stupid, but it should work now. Also upstream accepted my PR with fixed ftdetect  vim-polyglot uses this plugin unmodified

**Comment by trevordmiller** [comment]
Works great! Thanks :)
