### ISSUE TITLE
Function go#config#FoldEnable already exists, add ! to replace it

### ISSUE THREAD

**Issue by hujianxin** [sheerun/vim-polyglot#343]
When I hit `Ctrl-x + Ctrl-o`, I got:

Error detected while processing /home/hujianxin/.vim/plugged/vim-polyglot/autoload/go/config.vim:
line  426:
E122: Function go#config#FoldEnable already exists, add ! to replace it
Press ENTER or type command to continue
Error detected while processing function go#complete#Complete:
line    3:
E171: Missing :endif

**Comment by mgutz** [comment]
what was the fix? I'm having same issue
