### ISSUE TITLE
E122: Function go#config#FoldEnable already exists, add ! to replace it 

### ISSUE THREAD

**Issue by JCepedaVillamayor** [sheerun/vim-polyglot#345]
Hi!

When I try to use autocompletion in my Go code, appears this error:
```
Error detected while processing /home/user/.vim/plugged/vim-polyglot/autoload/go/config.vim:                                                               
line  426:                                                                                                                                                    
E122: Function go#config#FoldEnable already exists, add ! to replace it                                                                                       
Press ENTER or type command to continue      
```
Then, after pressing ENTER,  appears this:
```
Error detected while processing function go#complete#Complete:                                                                                                
line    3:                                                                                                                                                    
E171: Missing :endif                                                                                                                                          
Press ENTER or type command to continue     
```
I use polyglot with vim-go.

If you need more information regarding this error tell me.

Thanks!

**Comment by lerrua** [comment]
Same issue here, also using `:GoInfo` command.

**Comment by thatjames** [comment]
Same issue when using `:GoInfo`

**Comment by thatjames** [comment]
@JCepedaVillamayor @lerrua by chance are you guys running vim-go as well?

**Comment by JCepedaVillamayor** [comment]
Yes, I'm using it @thatjames

**Comment by thatjames** [comment]
@JCepedaVillamayor I have a feeling there's a conflict with the two plugins but I'm not familiar with vim script :/ 

I've managed to get guru working by adding `let g:go_info_mode='guru'` to my init file, but I'm pretty certain that's a function defined by vim-go. YMMV

**Comment by JCepedaVillamayor** [comment]
Seems that lately there have been changes in vim-go repository. I'm sure this has something to do with this.

**Comment by JCepedaVillamayor** [comment]
Ok, I've made some insights about this. In your vim-configuration, is vim-go before or after vim-polyglot? @thatjames 

I've just changed the order in my .vimrc and now it works perfectly.

**Comment by JCepedaVillamayor** [comment]
Since nobody has answered and the error (at least for me) has been solved, I proceed to close the issue. 

Thank you for all the help given!
