### ISSUE TITLE
markdown conceal feature does not work properly?

### ISSUE THREAD

**Issue by jdhao** [sheerun/vim-polyglot#350]
I opened a markdown file in Neovim and find that inline code, inline link and code blocks are rendered so that actual text is hidden. This is acceptable when I am in normal mode. But when I start editing the file, the actual source is still not shown, which is annoying (see image below).

![out](https://user-images.githubusercontent.com/16662357/47263420-f5e0d100-d533-11e8-82a3-35f308d6b9a4.jpg)

If I disable this plugin and open the markdown, I can the actual source txt. How to fix this issue?

**Comment by sheerun** [comment]
please raise this issue in upstream plugin or suggest better plugin for markdown

**Comment by karlhepler** [comment]
I'm having the same problem. @sheerun - would you please provide a link to the upstream plugin so I can check it out?

**Comment by sheerun** [comment]
links are in the readme

**Comment by karlhepler** [comment]
Found it! Thanks. https://github.com/plasticboy/vim-markdown
