### ISSUE TITLE
Add Ogre Support

### ISSUE THREAD

**Issue by Neur1n** [sheerun/vim-polyglot#355]
Hello. Just wondering if this repo will include [ogre material script](https://wiki.ogre3d.org/Vim+ogre+dotmaterial) support by any chance. Thanks.

**Comment by Neur1n** [comment]
Err... The link I attached is the only place I found them. And it is more like a "FYI" than a requirement. So it's fine to not include it if you think it is inappropriate or it is required by few people. (Even I am using using it so frequently.) Thanks.

**Comment by sheerun** [comment]
I'm fine with including it but it would need to be extracted as github repository and maintained

If someone would badly like support for this, please become maintainer of this syntax and create repository with plugin
