### ISSUE TITLE
jsx plugin break matchit after reloading file multiple time

### ISSUE THREAD

**Issue by mars90226** [sheerun/vim-polyglot#364]
When using `:edit` to reload jsx file, the b:match_words variable is appended with the jsx match words again. After multiple reloads, vim will complain `E51: Too many '('` when using `%` to jump to matching parenthese.

**Comment by moon-stripe** [comment]
I'm also running into this issue. It looks like https://github.com/mxw/vim-jsx is no longer maintained, might need to find an alternative.

**Comment by sodiumjoe** [comment]
I'm also running into this issue. It looks like https://github.com/mxw/vim-jsx is no longer maintained, might need to find an alternative.

**Comment by mars90226** [comment]
I've created a merge request to fix this issue in [https://github.com/mxw/vim-jsx/pull/187](https://github.com/mxw/vim-jsx/pull/187). After merging, I'll create another merge request to fix this issue here.

**Comment by afk-mcz** [comment]
A fork was made by @amadeus https://github.com/amadeus/vim-jsx

**Comment by mars90226** [comment]
I also notice this fork, but I'm not sure if it's good to create a merge request that replace vim-jsx with this fork. Currently, I think the best way is disabling jsx in vim-polyglot and manually using this fork.

**Comment by sheerun** [comment]
vim-polyglot switched to @amadeus fork and his xml plugin for now, hope it fixes some things. I hope @mxw will find time to merge changes to original repository, then we'll probably switch back

**Comment by mars90226** [comment]
Thanks!
