### ISSUE TITLE
YAML comments with no starting space are highlighted incorrectly

### ISSUE THREAD

**Issue by anowlcalledjosh** [sheerun/vim-polyglot#375]
In this YAML document, `#baz: quux` is a comment, but vim-polyglot highlights it as `yamlKey`:

```yaml
# this is a comment
foo: bar
#baz: quux
```

![image](https://user-images.githubusercontent.com/9433472/53413385-bb94ae00-39c3-11e9-8e6f-ea6da89175f7.png)

**Comment by sheerun** [comment]
This needs to be fixed in upstream repository, please raise this issue there:
https://github.com/stephpy/vim-yaml

**Comment by anowlcalledjosh** [comment]
Reported as stephpy/vim-yaml#19
