### ISSUE TITLE
HELP ME: Make travis build always passing

### ISSUE THREAD

**Issue by sheerun** [sheerun/vim-polyglot#380]
For some reason travis hangs on random files while testing different extensions of vim files, like this:

https://travis-ci.org/sheerun/vim-polyglot/builds/504406365

I would be grateful if someone had time to debug and fix this. PR is welcome

**Comment by Zebradil** [comment]
Hey, could you please explain what is the logic of the test? As far as I can see it's just creating a file with particular extension, write there some dummy string and save it back. Is that correct?

**Comment by Zebradil** [comment]
I re-implemented testing logic in bash, just a few adjustments an I'll send a PR.
