### ISSUE TITLE
It regard a markdown file(ended with .md) as fileType: liquid

### ISSUE THREAD

**Issue by magodo** [sheerun/vim-polyglot#384]
**Does this bug happen when you install plugin without vim-polyglot?** NO

**Describe the bug:**

I have a markdown file(ended with `.md`) with following format:

```
---
layout: "post"
title: "foo"
categories: "blog"
tags: []
published: False
comments: true
script: [post.js]
excerpted: |
    ...
---

* TOC
{:toc}

Content goes from here.
```

And the output of `: set filetype?` is `filetype=liquid`. My expectation is `filetype=markdown`.

**To Reproduce:**

Just do as description...

**Comment by sheerun** [comment]
it actually is liquid filetype

**Comment by dylan-chong** [comment]
I've encountered this problem too.

@sheerun why is it actually liquid filetype? It is markdown

**Comment by dylan-chong** [comment]
I am having difficulties with this bug because the plugin nerd-commenter uses the filetype to determine which type of comments to use when commenting out a line. The plugin uses liquid comments not HTML style comments which should be used in a markdown file

**Comment by dylan-chong** [comment]
i have filed a bug report to vim-liquid [here](https://github.com/tpope/vim-liquid/issues/18). I recommend closing this issue and stating that the solution for now would be to use `let g:polyglot_disabled = ['liquid']` as per [this](https://github.com/sheerun/vim-polyglot#troubleshooting)

**Comment by magodo** [comment]
> i have filed a bug report to vim-liquid [here](https://github.com/tpope/vim-liquid/issues/18). I recommend closing this issue as it is a bug with that plugin, not polyglot, and stating that the solution for now would be to use `let g:polyglot_disabled = ['liquid']` as per [this](https://github.com/sheerun/vim-polyglot#troubleshooting)

@dylan-chong it doesn't work for me...

**Comment by dylan-chong** [comment]
Did you put that line at the very start of your vimrc?

**Comment by magodo** [comment]
@dylan-chong I put it at very end of my vimrc.

**Comment by dylan-chong** [comment]
The line needs to be placed somewhere before the plug-in is loaded, otherwise polyglot will load the liquid files before reading the `g:polyglot_disabled`  variable.

**Comment by sheerun** [comment]
Okay, I'm removing liquid syntax from vim-polyglot because it's from commercial and non-opensource product anyway

**Comment by dylan-chong** [comment]
Awesome, thanks @sheerun!

**Comment by myfreeweb** [comment]
> it's from commercial and non-opensource product anyway

o_0

Liquid is MIT licensed https://github.com/Shopify/liquid and there are other implementations than the original ruby one

**Comment by sheerun** [comment]
liquid is mainly used for shopify and it isn't
