### ISSUE TITLE
Error when opening Java script files.

### ISSUE THREAD

**Issue by amkarthik** [sheerun/vim-polyglot#387]
**Does this bug happen when you install plugin without vim-polyglot?**
Yes.
**Describe the bug:**
Error log.
Error detected while processing /home/harmony/.vim/bundle/vim-polyglot/after/syntax/javascript/graphql.vim:
line   14:
E121: Undefined variable: g:graphql_javascript_tags
E116: Invalid arguments for function join(g:graphql_javascript_tags, '\|') . '\)'
line   16:
E121: Undefined variable: s:tags
line   17:
E121: Undefined variable: s:tags

**To Reproduce:**
Open .js files

**Comment by sheerun** [comment]
I've removed graphql until this is resolved

**Comment by blunckr** [comment]
I would be nice if this was optional or something. I've been using this with graphql with no issues. For anyone else that wants it, use the 'v3.7.0' tag.

**Comment by jeffvandyke** [comment]
Aww, just noticed my graphql syntax highlighting stopped working, traced it back here, now I'm sad. :( Hope this gets fixed soon on master. Maybe its time for me to learn vimscript basics...

**Comment by mcmillion** [comment]
https://github.com/jparise/vim-graphql has been working fine for me
