### ISSUE TITLE
Can't get syntax highl

### ISSUE THREAD

**Issue by drjosephliu** [sheerun/vim-polyglot#395]
**Does this bug happen when you install plugin without vim-polyglot?**

**Describe the bug:**

Vim-polyglot doesn't activate syntax highlighting. I have made sure that `syntax on` is included at the beginning of `.vimrc`.

**To Reproduce:**
Install vim-polyglot with vim-plug via `Plug 'sheerun/vim-polyglot'`.
Add `syntax on` at start of `.vimrc`.
Run `:PlugInstall` and `:PlugUpdate`.
Then `:source ~/.vimrc`

**Comment by Zebradil** [comment]
What show `:set syntax` and `:set filetype` commands?
What is opened in vim? Is it an existing file or a new buffer?

**Comment by Sanhajio** [comment]
I had the same issue, the outputs were `syntax=` and `filetype=`:

I added to myvimrc:
```vimscript
au! BufNewFile,BufReadPost Jenkinsfile set filetype=Jenkinsfile foldmethod=indent syntax=on
"au! BufNewFile,BufReadPost *.{yaml,yml} set filetype=yaml
autocmd FileType Jenkinsfile setlocal filetype=groovy foldmethod=indent ts=2 sts=2 sw=2 expandtab
```

**Comment by drjosephliu** [comment]
@Zebradil it shows `syntax=java` and `filetype=java`. As you can guess I have a java file opened. What exactly am I suppose to see when I use polyglot? Because I don't seem to get any highlighting (only highlighting I get is from my colour theme).

**Comment by sheerun** [comment]
Please share minimal `.vimrc` for reproduction, and filenames you try to open. I've tested vim-polyglot for `Jenkinsfile` on my computer and it works propelry.
