### ISSUE TITLE
Error entering elixir files, unknown helper function

### ISSUE THREAD

**Issue by mulias** [sheerun/vim-polyglot#399]
**Does this bug happen when you install plugin without vim-polyglot?** No.

**Describe the bug:** Entering an elixir `.ex` file triggers the error message
```
Error detected while processing BufReadPost Autocommands for "*.ex":
E117: Unknown function: <SNR>6_setf
```

**To Reproduce:** 
- Install `vim-polyglot` through plug
- `touch example.ex`
- `vim example.ex`

I was able to fix the issue by editing `ftdeetect/polyglot.vim` and moving the function `s:setf` to the top part of the file, above elixir file detection.

**Comment by sheerun** [comment]
I've force-included s:setf at the top of ftdetect file, hope it helps..
