### ISSUE TITLE
Consider vim-jsx-pretty instead of vim-jsx

### ISSUE THREAD

**Issue by ayoisaiah** [sheerun/vim-polyglot#400]
Putting this out there for discussion:

**GitHub repository url**: https://github.com/MaxMEllon/vim-jsx-pretty

**Is this plugin well maintained?**: Yes, last commit as at the time of creating this issue was 15 days ago compared to vim-jsx which is almost a year ago.

**Is this plugin lightweight? (no advanced functionality, just indent and syntax support)**: Yes, JSX syntax highlighting and indentation only. It also supports Typescript TSX files.

**Comment by tombh** [comment]
Just came here to say the same thing. I've switched to it because of problems with JSX in Typescript, works dramatically better in my use case.

**Comment by thisguychris** [comment]
also, having problems with coc-pretttier, since vim-jsx changes the file type to javascript.jsx while vim-jsx-pretty retains it.

**Comment by sheerun** [comment]
Indeed this syntax is much better, thank you for recommending
