### ISSUE TITLE
Neither :TerraformFmt or terraform#fmt() are available

### ISSUE THREAD

**Issue by sudoforge** [sheerun/vim-polyglot#411]
As far as I understand it (which is to say, perhaps, not a whole lot), `vim-polyglot` should be autoloading `vim-polyglot://autoload/terraform.vim`, which defines the Vim7-style function, `terraform#fmt()`. This is used in `vim-polyglot://ftplugin/terraform.vim`, both to make the command `TerraformFmt` available to the current buffer, and to conditionally call it on the buffer during `BufWritePre`, if `g:terraform_fmt_on_save = 1`.

This doesn't seem to be working for me. I get syntax highlighting, but nothing else. The `vim-polyglot` directory is in my `runtimepath`, and the filetype is being detected correctly.

Any ideas on how to debug this further?

**Comment by sheerun** [comment]
Works for me. I guess you need to have terraform binary available in path:

```
if !executable('terraform')
  finish
endif
```

**Comment by sudoforge** [comment]
I most definitely have `terraform` available in my path.

> Works for me.

This is never really a great way to determine that a reported issue doesn't exist 😄

**Comment by sudoforge** [comment]
```
:if executable('terraform')
:  echo "well, this isn't a surprise"
well, this isn't a surprise
```

**Comment by sudoforge** [comment]
Some notes to add to the above comments:

- The standard plugin by `hashivim` works as expected.
- Commenting out the failout conditional check for `terraform` in the current path on `vim-polyglot://ftplugin/terraform.vim:L139-141` does not magically make the function(s) available.

**Comment by sheerun** [comment]
Please attach minimal .vimrc file that reproduces this issue

**Comment by sudoforge** [comment]
I'm a dummy. There was an errant `after/ftplugin/tf.vim` file, outside of `vim-polyglot`, that was taking precedence over the included `vim-polyglot://ftplugin/terraform.vim`.

My apologies for the noise.
