### ISSUE TITLE
TSX still syntax highlighted when disabling typescript

### ISSUE THREAD

**Issue by drewschrauf-myob** [sheerun/vim-polyglot#414]
**Describe the bug:**

I use [yats](https://github.com/HerringtonDarkholme/yats.vim) for syntax highlighting typescript and polyglot for all other languages. Until recently, setting `let g:polyglot_disabled = ['typescript']` was enough to disable polyglot's detection of typescript.

TSX files have started seeing syntax highlighting issues. Upon investigation, [this file](https://github.com/sheerun/vim-polyglot/blob/master/after/syntax/typescript.vim) appears to get loaded for typescript and requires the disable flags to be updated to `let g:polyglot_disabled = ['typescript', 'jsx']`.

I don't know enough to understand whether that's intentional or is a copy/paste issue from its javascript counterpart. The comment block at the top refers to `javascript.jsx` so I suspect it's the latter.

**To Reproduce:**

Set `let g:polyglot_disabled = ['typescript']` and load a TSX file. JSX and styled-components regions are still highlighted.

**Comment by sheldonkwok** [comment]
This is breaking my regular typescript files as well.

**Comment by sheldonkwok** [comment]
This is fixed in #419

**Comment by sheerun** [comment]
I fixed it properly..
