### ISSUE TITLE
JavaScript: E117 Unknown function: styledcomplete#CompleteSC

### ISSUE THREAD

**Issue by cwfoo** [sheerun/vim-polyglot#418]
**Does this bug happen when you install plugin without vim-polyglot?**
No. The problem is caused by commit 445e0260108fbc5745d77b6e15b290eb55d4f1b2, which added [vim-styled-components](https://github.com/styled-components/vim-styled-components) but vim-polyglot's build script did not include [`styledcomplete#CompleteSC`](https://github.com/styled-components/vim-styled-components/blob/v2.11/after/autoload/styledcomplete.vim#L6-L17).

**Describe the bug:**
Writing anything in JavaScript buffers causes `E117 Unknown function: styledcomplete#CompleteSC`.

**To Reproduce:**
* Open a JavaScript file
* Write code or comments.

If you remove these lines
https://github.com/sheerun/vim-polyglot/blob/445e0260108fbc5745d77b6e15b290eb55d4f1b2/after/ftplugin/javascript.vim#L85-L88
the error disappears.

The problem is probably caused by the omission of `after/autoload` from https://github.com/sheerun/vim-polyglot/blob/3ddca5da461ebfaa82104f82e3cbf19d1c326ade/build#L5

**Comment by Rigellute** [comment]
I am also getting this error.

**Comment by TPLinux** [comment]
I am also getting the same error

**Comment by aanari** [comment]
The fix in #423 fixed it for me 👍

**Comment by cwfoo** [comment]
@aanari Apparently that's not the proper way to fix the problem. The mistake is in vim-polyglot's build script. Reference: https://github.com/sheerun/vim-polyglot/pull/423#issuecomment-523103058

**Comment by sheerun** [comment]
this should be fixed now, please verify

**Comment by john-kurkowski** [comment]
I re-enabled styled-components yesterday. So far I haven't seen the error in JS again. 👍 (Note I don't use styled-components.)

**Comment by sheerun** [comment]
Yeah me too and I I'm also not sure they should be supported... On the other hand their implementation shoudn't make syntax highlighting much slower so whatever
