### ISSUE TITLE
r-lang plugin (R.vim) includes intrusive mappings

### ISSUE THREAD

**Issue by exic** [sheerun/vim-polyglot#420]
I was wondering why a weird xterm window opened when I was pressing F3 (saying "Can't execvp funnel.pl: No such file or directory"). It turned out to be coming from vim-polyglot/ftplugin/r.vim.
Since I was expecting polyglot to basically provide syntax/ft-detection, I found this a little intimidating, I'd want to be sure that none of my ftplugins change my mappings like that.
What do you think about that?
Would it make sense to remove the lines starting at 53 here? https://github.com/sheerun/vim-polyglot/blob/master/ftplugin/r.vim#L53

**Comment by sheerun** [comment]
Indeed that's the premise. I'll switch r to basic syntax set so it won't include plugin stuff
