### ISSUE TITLE
jsx detection breaks highlighting js left shift

### ISSUE THREAD

**Issue by devsnek** [sheerun/vim-polyglot#439]
**Does this bug happen when you install plugin without vim-polyglot?**
Nop

**Describe the bug:**
In a JS left shift expression (`a << b`), if the rhs is an identifier, polyglot switches to jsx highlighting. It works fine if the rhs is not an identifier.

**To Reproduce:**

![](https://gc.gy/40447692.png)
![](https://gc.gy/40447705.png)
![](https://gc.gy/40447717.png)
![](https://gc.gy/40447740.png)

**Comment by devsnek** [comment]
for anyone else, this can be temporarily fixed by adding 'jsx' to polyglot_disabled

**Comment by sheerun** [comment]
Could you submit this issue to jsx plugin? We just bundle different ones.

**Comment by devsnek** [comment]
@sheerun vim-jsx-pretty was updated, should fix this.

**Comment by sheerun** [comment]
I've updated vim-polyglot as well
