### ISSUE TITLE
Error after update : Function RacketDetectHashLang already exists

### ISSUE THREAD

**Issue by notagoodidea** [sheerun/vim-polyglot#441]
**Does this bug happen when you install plugin without vim-polyglot?** No.

**Describe the bug:** After updating vim-polyglot throught vim-plug (:PlugUpdate) in Neovim, I got the following error : 

> Error detected while processing /home/foobar/.local/share/nvim/plugged/vim-polyglot/ftdetect/polyglot.vim : 
> line 1123
> E122: Function RacketDetectHashLang already exists, add ! to replace it.

**To Reproduce:** Update to last version of vim-polyglot(?)

**Comment by sheerun** [comment]
I don't experience it. Could you update vim-polyglot and check again? If it still does happen on newest version, please provide more specific instructions to reproduce this issue

**Comment by soli** [comment]
I'm not on a machine where I can test right now but:
- yes, it still does happen with the latest version
- I didn't have any problem when I was using a plugin manager, but the issue started when I switched to `packadd` stuff…

I'll try to give more precise feedback next week.

**Comment by sheerun** [comment]
I suggest using package manager or disabling polyglot syntax for racket with `let g:polyglot_disabled = ['racket']`, at the beginning of .vimrc and then loading plugin directly. I cannot reproduce this issue so if someone would like me to fix it, I need concrete steps to reproduce this problem (e.g. zip file with exact directory structure and .vimrc)
