### ISSUE TITLE
Need I to add the Julia-Plugin 

### ISSUE THREAD

**Issue by daxinnan** [sheerun/vim-polyglot#443]
Hi,I want use julia in Vim, so If I install `vim-polyglot` by `Vundle`, should I install [JuliaEditorSupport/julia-vim](https://github.com/JuliaEditorSupport/julia-vim) additionally?

**Comment by sheerun** [comment]
vim-polyglot has syntax highlighting capability for julia. if you want more advanced features you need to install this plugin separately, yes
