### ISSUE TITLE
ctags: cannot open option file "/root/.vim/bundle/vim-polyglot/ctags/typescript.ctags" : No such file or directory

### ISSUE THREAD

**Issue by gaofei1982** [sheerun/vim-polyglot#445]
Git checkout 66b769328c4511b2273f01c70de971c41f6964dd is ok.

But when i checkout master or 84ec4eedcdd2892249b5369f91a6dd1d12fef2fc is report error.

Like this:

Tagbar: Could not execute ctags for /root/xxxx/common.model.ts!
Executed command: "'ctags' '--extra=' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSaf' '--file-scope=yes' '--sort=no' '--append=no' '--options=/root/.vim/bundle/vim-polyglot/ctags/typescript.ctags'
'--language-force=typescript' '--typescript-kinds=catnfvlmie' '/tmp/vjGz7PF/3.ts'"
Command output:
ctags: cannot open option file "/root/.vim/bundle/vim-polyglot/ctags/typescript.ctags" : No such file or directory
Exit code: 1
Press ENTER or type command to continue

**Comment by sheerun** [comment]
Could you update vim-polyglot, test if this is still and issue, and if it is, provide a way for me to reproduce this error? Thank you

**Comment by gaofei1982** [comment]
It's OK! Thank you.

commit 4d8423c962e2b4172de48992bcfec965478f928b
Author: Adam Stankiewicz <sheerun@sher.pl>
Date:   Sat Dec 7 17:39:31 2019 +0100
Add v language, closes #437

**Comment by gaofei1982** [comment]
Open ***.ts(typescript) file report error.

**Comment by hikerpig** [comment]
I think it has something to do with this in [typescript.vim](https://github.com/sheerun/vim-polyglot/blob/master/ftplugin/typescript.vim):

```vim
" In case you've updated/customized your ~/.ctags and prefer to use it.
if get(g:, 'typescript_use_builtin_tagbar_defs', 1)
  let g:tagbar_type_typescript.deffile = expand('<sfile>:p:h:h') . '/ctags/typescript.ctags'
endif
```
I think by default it shoult not be 1 ? Or is there a `vim-polyglot/ctags/` directory that I should create ?

**Comment by anthmarques** [comment]
I have the same issue, just open .ts file.

**Comment by hikerpig** [comment]
@gaofei1982 @anthmarques  Currently, you can add this line to your vimrc:

```
let g:typescript_use_builtin_tagbar_defs=0
```

**Comment by sheerun** [comment]
I've added ctags file. I hope it fixes it
