### ISSUE TITLE
Markdown enhancement: add ftplugin to gain syntax highlighting in fenced code

### ISSUE THREAD

**Issue by bluz71** [sheerun/vim-polyglot#447]
Hello,

This is a followup to #152.
Basically the Markdown provider used does support syntax highlighting in fenced code, but via the `ftplugin`, specifically the `markdown.vim` file provided by the plugin.

Currently Polyglot does not ship `ftplugin` for this language. Hence, no highlighting in fenced code.
Certain other languages provided with Polyglot do ship with `ftplugin`.

Could platicboy's Markdown also be shipped with `ftplugin`? It would fix the non-highlighting in fenced code issue.

Regards.

**Comment by sheerun** [comment]
ok

**Comment by bluz71** [comment]
Thank you @sheerun.
