### ISSUE TITLE
[Request] Remove regexpengine workaround

### ISSUE THREAD

**Issue by Shougo** [sheerun/vim-polyglot#449]
Please see https://github.com/pearofducks/ansible-vim/pull/86 problem.

**Comment by pearofducks** [comment]
Fix merged - thanks for the PR @Shougo  :)

**Comment by Shougo** [comment]
Thank you!

@sheerun Can you merge the latest ansible-vim?

**Comment by sheerun** [comment]
Yup, everything is updated in v4.1.2

**Comment by Shougo** [comment]
Thanks.
