### ISSUE TITLE
Razor (.cshtml), Cake (.cake), and (.csx)

### ISSUE THREAD

**Issue by aymanbagabas** [sheerun/vim-polyglot#450]
**GitHub repository url**
https://github.com/adamclerk/vim-razor

**Is this plugin well maintained?**
It hasn't been updated in 7 years, so no

**Is this plugin lightweight? (no advanced functionality, just indent and syntax support)**
Yes

EDIT:
Created a fork with some fixes https://github.com/aymanbagabas/vim-razor

[1] https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1
[2] https://github.com/OrangeT/vim-csharp
[3] https://github.com/OmniSharp/omnisharp-vim/tree/master/ftdetect

**Comment by sheerun** [comment]
I've added original plugin. Could you send there your patch? If author doesn't merge it within month then I'll use your fork
