### ISSUE TITLE
VimWiki markdown link follow compatibility issue

### ISSUE THREAD

**Issue by merit-mthompson** [sheerun/vim-polyglot#452]
**Does this bug happen when you install plugin without vim-polyglot?**

No. This bug is not present when I install vim-markdown directly.

**Describe the bug:**

When using VimWiki, the enter key is used to follow internal wiki links. With the release of vim-polyglot 4.1.3 this has stopped working. This is not an issue with vim-polyglot 4.1.2 and does not seem to be an issue with vim-markdown.

**To Reproduce:**

Sample config using vim-plug to reproduce:
```vim
call plug#begin('~/.config/nvim/plugged')
  Plug 'sheerun/vim-polyglot'
  Plug 'vimwiki/vimwiki'
call plug#end()

set nocompatible
filetype plugin on
syntax on

let g:vimwiki_list = [{
  \'ext': '.md',
  \'path': '~/.config/nvim/wiki/',
  \'syntax': 'markdown',
\}]
```

Now open vim, hit \ww, enter `[some link](somelink)`, leave insert mode, try hitting the enter key. This should follow the link (and create the file) but with vim-polyglot 4.1.3 it will just move to the next line.

If, using vim-plug, I lock to version 4.1.2 things work as expected:

```vim
call plug#begin('~/.config/nvim/plugged')
  Plug 'sheerun/vim-polyglot', { 'tag': 'v4.1.2' }
  Plug 'vimwiki/vimwiki'
call plug#end()

" ... same stuff from previous block
```

If using vim-markdown directly, this also works as expected:
```vim
call plug#begin('~/.config/nvim/plugged')
  Plug 'plasticboy/vim-markdown'
  Plug 'vimwiki/vimwiki'
call plug#end()

" ... same stuff from previous block
```

**Comment by sheerun** [comment]
markdown syntax is killing me

**Comment by xsteadfastx** [comment]
ran into this problem today!

**Comment by xsteadfastx** [comment]
looks like commit cea0d08a062478503814e51aa21c6486a0dd1b21 has something to do with it.

**Comment by sheerun** [comment]
This should be fine now

**Comment by merit-mthompson** [comment]
Thanks for fixing! Works like a charm.

**Comment by incoggnito** [comment]
It seems the fix is not working for neovim nightly build.
