### ISSUE TITLE
Error when opening markdown file with yaml frontmatter

### ISSUE THREAD

**Issue by ferki** [sheerun/vim-polyglot#455]
**Does this bug happen when you install plugin without vim-polyglot?**

No. Directly using git master HEAD of either gabrielelana/vim-markdown or plasticboy/vim-markdown seems fine.

**Describe the bug:**

When opening a markdown file with yaml frontmatter, vim complains about the following error:

```
Error detected while processing /tmp/vgqrcww/1.utf-8.spl:
E763: Word characters differ between spell files
```

**To Reproduce:**

Use v4.1.4 of vim-polyglot and open a markdown file with a yaml frontmatter.

Any of the following works as a workaround:
 - downgrading to v4.1.3 (and therefore to use plasticboy/vim-markdown)
 - commenting out the [`silent spell!` lines in `syntax/markdown_jekyll.vim`](https://github.com/sheerun/vim-polyglot/blob/master/syntax/markdown_jekyll.vim#L20-L25)
 - adding `let g:markdown_include_jekyll_support = 0` to `~/.vimrc`

**Comment by sheerun** [comment]
This should be fine now
