### ISSUE TITLE
Jenkinsfile incorrect syntax highlight inside sh block

### ISSUE THREAD

**Issue by ftorres16** [sheerun/vim-polyglot#456]
**Does this bug happen when you install plugin without vim-polyglot?**
No.

**Describe the bug:**
When using a Jenkinsfile that includes an sh block in which the `/*` character combination is used the remaining of the file is highlighted as a comment instead of as actual code.

I have already opened [an issue](https://github.com/martinda/Jenkinsfile-vim-syntax/issues/13) at `martinda/Jenkinsfile-vim-syntax` and it looks [like it's related to vim-polyglot's groovy highlighting](https://github.com/martinda/Jenkinsfile-vim-syntax/issues/13#issuecomment-569977291).

**To Reproduce:**
This particular snippet is valid Jenkins syntax but gets everything after `mv reports-python/*` considered a comment.

```
post {
  always {
    sh '''
    echo "Tests generated"
    mv reports-python/* reports
    '''
  }
}
```

**Comment by nastevens** [comment]
The Groovy syntax file in vim-scripts (https://www.vim.org/scripts/script.php?script_id=945) has not been kept up to date with the Groovy syntax included in the mainline vim distribution (https://github.com/vim/vim/blob/master/runtime/syntax/groovy.vim). I'm not sure what the vim-polyglot policy is for situations like this - should vim-polyglot include its own copy of the newer version from vim-runtime? Or is there a mechanism to fall back to built-in for certain languages? I'm happy to open a PR, just need some guidance on what to PR 😄

**Comment by sheerun** [comment]
I've asked Bram from where he takes groovy syntax in vim, but he haven't replied yet

**Comment by sheerun** [comment]
No answer from Bram so I'm just removing groovy syntax from here
