### ISSUE TITLE
YAML: define 2/4/x spaces for indent

### ISSUE THREAD

**Issue by mgh87** [sheerun/vim-polyglot#457]
I would like to change the indentation from 2 to 4 spaces for yaml files or in general, have the possibility to select how many spaces an indent of languages uses. (At best generic for all languages)

Is this achievable within a vi plugin? -- or is the better approach that I create my own indent files which replace the spacing for the languages I need?

**Comment by sheerun** [comment]
Sorry, vim-polyglot just gathers different plugins in one place. You need to raise this issue on yaml plugin: https://github.com/stephpy/vim-yaml

**Comment by mgh87** [comment]
Ah, ty for the info.
