### ISSUE TITLE
keith/rspec and sheerun/rspec have diverged

### ISSUE THREAD

**Issue by cbandy** [sheerun/vim-polyglot#458]
There have been several [commits to the upstream](https://github.com/sheerun/rspec.vim/compare/master...keith:master) plugin since it was forked, and now some keywords are missing, e.g., [`aggregate_failures`](https://relishapp.com/rspec/rspec-core/docs/expectation-framework-integration/aggregating-failures), [`and_call_original`](https://relishapp.com/rspec/rspec-mocks/docs/configuring-responses/calling-the-original-implementation).

It appears that the [only change](https://github.com/keith/rspec.vim/compare/master...sheerun:master) in the fork moves the entire plugin to `after`.

**Comment by sheerun** [comment]
Could you send PR to keith/rspec that moves everything to after? Then I can use it directly

**Comment by cbandy** [comment]
I can. What's the reason/effect for the change?

**Comment by sheerun** [comment]
Rspec plugin must be applied after ruby plugin. We had some issues without
this change but I don’t remember exactly what

**Comment by cbandy** [comment]
I've also had `rspec.vim` load after `vim-ruby` since before I committed my Vim files to Git, but now I don't see any difference when loading them the other way around. Tested in Vim 8 and Neovim. 🤷‍♂ 

I also tried updating the `rspec.vim` files directly in vim-polyglot and everything I could think of seems fine. (I did not try to perform a full build. The upstream ftdetect is before ruby in polygot's ftdetect.)

```
 after/syntax/rspec.vim |  36 ----
 ftdetect/polyglot.vim  |   7 +
 syntax/rspec.vim       | 193 +++++++++++++++++++
 3 files changed, 200 insertions(+), 36 deletions(-)
```

I think the following should suffice:

```diff
diff --git build build
index 6ef3f5f..e651a9a 100755
--- build
+++ build
@@ -265,7 +265,7 @@ PACKS="
   ragel:jneen/ragel.vim
   raml:IN3D/vim-raml
   reason:reasonml-editor/vim-reason-plus
-  rspec:sheerun/rspec.vim
+  rspec:keith/rspec.vim
   rst:marshallward/vim-restructuredtext
   ruby:vim-ruby/vim-ruby
   rust:rust-lang/rust.vim
```

**Comment by sheerun** [comment]
The PR upstream is accepted so I'm changing it back to original one
