### ISSUE TITLE
After update from 4.1.1 to 4.2.0 jsx syntax color is not working

### ISSUE THREAD

**Issue by rogeriopvl** [sheerun/vim-polyglot#460]
**Does this bug happen when you install plugin without vim-polyglot?**

No
**Describe the bug:**

After updating from `v4.1.1` to `v4.2.0` whenever I open a JSX file (with `.jsx` extension) neovim fails to detect the correct filetype, showing no syntax colors.

This does not happen in VIM. Just Neovim.

**To Reproduce:**

Install latest vim-polyglot, and open a jsx file with latest neovim.

Note: I suspect that this commit might have something to do with it: https://github.com/sheerun/vim-polyglot/commit/43085dc02f34d7d54208e6e20989d4779bffe71c

Reverting back to `v4.1.1` fixes the issue.

**Comment by sheerun** [comment]
this should be fixed now
