### ISSUE TITLE
Rust: Why is tabstop set to 8?

### ISSUE THREAD

**Issue by MTBorg** [sheerun/vim-polyglot#467]
According to the [rust docs](https://doc.rust-lang.org/1.0.0/style/style/whitespace.html) indentation should use 4 spaces, but in ftplugin/rust.vim tabstop is set to 8
https://github.com/sheerun/vim-polyglot/blob/35ea4d2b9072594b6c0ccf87bde7978ed9f94755/ftplugin/rust.vim#L50-L54

This causes some code to look like
```rust
fn main(){
        println!("hello world");
}
```
when it should look like
```rust
fn main(){
    println!("hello world");
}
```

Also, should really the default value of `get(g:, 'rust_recommended_style', 1)` be 1? If the variable isn't set, i feel as though the default value should be to not use the default settings.

**Comment by sheerun** [comment]
Could you raise this issue on https://github.com/rust-lang/rust.vim ?
