### ISSUE TITLE
Disable spelling in JavaScript strings

### ISSUE THREAD

**Issue by LandonSchropp** [sheerun/vim-polyglot#468]
**Does this bug happen when you install plugin without vim-polyglot?**

No

**Describe the bug:**

I recently enabled the `spell` option in Neovim, and boy was I surprised at the number of spelling errors I found in my strings. While it's very useful to have them inside of comments, I personally think the number of normal use cases where strings do not conform to the spelling rules makes these settings less than helpful. I'd propose removing spell from the following syntax clusters:

```
jsString
jsTemplateString
jsObjectKeyString
jsObjectStringKey
```

The comment spell checking is very helpful.

**To Reproduce:**

Try any of these strings that are normal in JavaScript code.

```
"ramda"
"json"
"https"
"http"
"lodash"
```

**Comment by LandonSchropp** [comment]
[Here's](https://stackoverflow.com/questions/60594419/remove-spell-from-a-syntax-cluster/60595259#60595259) the StackOverflow issue I opened up on this topic. It looks like there's not an easy way to modify an existing group outside of redefining it. I'd really prefer not to do this if possible.

**Comment by sheerun** [comment]
vim-polyglot just gathers other plugins in one place. if you'd like this change, please open an issue on pangloss/vim-javascript repository

**Comment by LandonSchropp** [comment]
Will do. Thanks!
