### ISSUE TITLE
How to set option variables (e.g., python-syntax)?

### ISSUE THREAD

**Issue by ywpkwon** [sheerun/vim-polyglot#472]
I found that this plugin uses `vim-python/python-syntax` for python syntax.
In their introduction, they provide many options like `let g:python_highlight_all = 1`. Can I set it in `init.vim` (neovim) while I'm using this plugin? Or is there a way to forward such option?

**Comment by sagittaros** [comment]
Yes @ywpkwon, see [here](https://github.com/sheerun/vim-polyglot/blob/14dc82fc4e6c0c08078f97a24a6c1639c1cc5113/syntax/python.vim#L44).

This is how i configured mine.
```vim
let g:python_highlight_all = 0
let g:python_highlight_builtins = 1
let g:python_highlight_exceptions = 1
let g:python_highlight_string_formatting = 1
let g:python_highlight_string_format = 1
let g:python_highlight_string_templates = 1
let g:python_highlight_indent_errors = 1
let g:python_highlight_space_errors = 1
let g:python_highlight_doctests = 1
let g:python_print_as_function = 1
let g:python_highlight_func_calls = 1
let g:python_highlight_class_vars = 1
let g:python_highlight_operators = 0
```

**Comment by ywpkwon** [comment]
Thanks you so much! :)
