### ISSUE TITLE
Undesired highlight

### ISSUE THREAD

**Issue by delminskii** [sheerun/vim-polyglot#474]
**Does this bug happen when you install plugin without vim-polyglot?**
No

**Describe the bug:**
First of all, take a look at this screen: 
![2020-03-14--1584176871_372x202_scrot](https://user-images.githubusercontent.com/6321554/76678995-b796f680-65ed-11ea-805f-d0a488f2baf7.png)
You may see here this calls' highlight like this option is enabled by default (I checked it out with `vim-python/python-syntax` plugin and that's all right with that there).
I use current stable **neovim 0.4.3**

**To Reproduce:**
Test some methods' calls in *.py files.

**Comment by sheerun** [comment]
" calls' highlights like thos option" - sorry I don't understand, could you explain again?

**Comment by delminskii** [comment]
I am talking about `g:python_highlight_func_calls` option of `https://github.com/vim-python/python-syntax` plugin. If I try to use `python-syntax` directly it's OK with this option. But if I use this (polyglot plugin) - then I see a picture I posted above.

**Comment by sheerun** [comment]
If you update vim-polyglot, you can disable this by adding `let g:python_highlight_func_calls = 0` to your vimrc :)

**Comment by kevinhwang91** [comment]
@sheerun I think you should obey the `g:python_highlight_all`, it's default value is 0, If you think vim-polyglot should highlight all by default, you should make an option let the user disable it.

**Comment by sheerun** [comment]
@kevinhwang91 If you have time to fix it then the place is ftdetect/polyglot.vim, if not I'll probably get to it next week

**Comment by sheerun** [comment]
until then you can disable individual options

**Comment by sheerun** [comment]
btw. if you look how github highlights syntax, it's the same thing (it highlights method calls):
https://github.com/scipy/scipy/blob/master/scipy/misc/common.py
