### ISSUE TITLE
ElmCast/elm-vim no longer maintained

### ISSUE THREAD

**Issue by sparkcanon** [sheerun/vim-polyglot#475]
**GitHub repository url**
https://github.com/Zaptic/elm-vim

**Is this plugin well maintained?**
It appears [ElmCast/elm-vim](https://github.com/ElmCast/elm-vim) is not maintained anymore according to [elm-tooling docs](https://github.com/elm-tooling/elm-vim#what-about-elmcastelm-vim-and-zapticelm-vim) as well as [here](https://github.com/Zaptic/elm-vim#this-fork ) and does not support `0.19` version. I suggest moving to [Zaptic/elm-vim](https://github.com/Zaptic/elm-vim) which is maintained fork.

**Is this plugin lightweight? (no advanced functionality, just indent and syntax support)**
`Zaptic/elm-vim` is just a fork with `0.19` support and fixes.

**Comment by jpagex** [comment]
The is also `andys8/vim-elm-syntax` for Elm syntax highlighting.
