### ISSUE TITLE
LaTeX: Support nested syntax highlighting for Lua

### ISSUE THREAD

**Issue by hmenke** [sheerun/vim-polyglot#476]
LuaTeX is a popular alternative to pdfLaTeX and supports Lua code in TeX documents.  It would be great if you could add nested syntax highlighting to [`after/syntax/tex.vim`](https://github.com/sheerun/vim-polyglot/blob/master/after/syntax/tex.vim).  I already tried adding the following but couldn't get it to work.
```vim
syn include @luaSyn syntax/lua.vim
syn region luaZone matchgroup=texBeginEnd
                   \ start='\\begin{luacode\*\{,1}}\>'
                   \ end='\\end{luacode\*\{,1}}\>' keepend
                   \ contains=@luaSyn,@NoSpell
```

**Comment by sheerun** [comment]
I'm going to change provider to https://github.com/lervag/vimtex I hope it'll help because they say in readme nested luatex is supported

**Comment by wookayin** [comment]
This actually breaks vimtex -- see #484
