### ISSUE TITLE
Markdown folding with plasticboy/vim-markdown doesn't work

### ISSUE THREAD

**Issue by nicoqh** [sheerun/vim-polyglot#478]
I'm opening this issue for people who are wondering why folding isn't working for Markdown files.

This plugin (vim-polyglot) removes the file `after/ftplugin/markdown.vim` from [plasticboy/vim-markdown](https://github.com/plasticboy/vim-markdown) in order to "fix performance issue with markdown highlighting" (see commit: https://github.com/sheerun/vim-polyglot/commit/e8454d66ab8376cf9c7e42f09749d5bd17d98f89).

Relevant issue in plasticboy/vim-markdown: https://github.com/plasticboy/vim-markdown/issues/417

`after/ftplugin/markdown.vim` enables folding for Markdown files.

In order to use an unaltered version of `plasticboy/vim-markdown`, with folding enabled, you can replace your import of vim-polyglot with:

```
let g:polyglot_disabled = ['markdown']
Plug 'sheerun/vim-polyglot'
Plug 'plasticboy/vim-markdown'
```

@sheerun, your hands are probably tied, so feel free to close this issue. I just wanted to leave it here as a form of documentation.

**Comment by sheerun** [comment]
Yes, this was conscious decision due to performance issues

**Comment by alancaldas84** [comment]
One solution is to use builtin vim folder configured for markdown.
https://stackoverflow.com/questions/3828606/vim-markdown-folding

function! MarkdownLevel()
    if getline(v:lnum) =~ '^# .*$'
        return ">1"
    endif
    if getline(v:lnum) =~ '^## .*$'
        return ">2"
    endif
    if getline(v:lnum) =~ '^### .*$'
        return ">3"
    endif
    if getline(v:lnum) =~ '^#### .*$'
        return ">4"
    endif
    if getline(v:lnum) =~ '^##### .*$'
        return ">5"
    endif
    if getline(v:lnum) =~ '^###### .*$'
        return ">6"
    endif
    return "=" 
endfunction
au BufEnter *.md setlocal foldexpr=MarkdownLevel()  
au BufEnter *.md setlocal foldmethod=expr
