### ISSUE TITLE
Add better java syntax highlighting 

### ISSUE THREAD

**Issue by rickysaurav** [sheerun/vim-polyglot#479]
**GitHub repository url**
https://github.com/uiiaoo/java-syntax.vim

**Is this plugin well maintained?**
I don't think so. But it's still better than vim's default syntax highlighting.

**Is this plugin lightweight? (no advanced functionality, just indent and syntax support)**
Yes

**Comment by sheerun** [comment]
Unfortnately I'd rather avoid unmaintained plugins. I can suggest you to contribute changes from this repository to official java plugin in https://github.com/vim/vim/blob/master/runtime/syntax/java.vim
