### ISSUE TITLE
Neovim healthcheck failing for vimtex

### ISSUE THREAD

**Issue by ChristianChiarulli** [sheerun/vim-polyglot#484]
Clean install with just polyglot give the following when running checkhealth

```
health#vimtex#check
========================================================================
## vimtex
  - OK: Vim version should have full support!
  - WARNING: bibtex is not executable, so bibtex completions are disabled.
  - OK: General viewer should work properly!
  - ERROR: |g:vimtex_compiler_method| (`latexmk`) is not executable!
```

**Comment by ChristianChiarulli** [comment]
btw I don't use any latex stuff so I my health check shouldn't care

**Comment by sheerun** [comment]
vim-polyglot just imports basic syntax & indent support, if you want to use full capabilities, then you need to install plugin separately

**Comment by ChristianChiarulli** [comment]
I had just never noticed it before I'm assuming this is due to a new feature being added. The only issue I had with it was that it cluttered up my healthcheck a little. But if this is the new expected behavior we can close this.

**Comment by sheerun** [comment]
do you actively use tex? does the test pass if you include the plugin directly?

**Comment by ChristianChiarulli** [comment]
I don't use tex at all. I'm sure if I included it directly it would pass. But as I don't use it at all I just didn't expect this behavior.

**Comment by sheerun** [comment]
so why have you run this check? what's the command?

**Comment by ChristianChiarulli** [comment]
```:checkhealth```

In Neovim its a way to check the health of some plugins if they provide and interface.

**Comment by vtnpp** [comment]
I noticed the same after running `:checkhealth` today. It wasn't showing up before.

Most likely due to d757bfd I guess?

**Comment by atgmello** [comment]
I'm using [neovim](https://github.com/neovim/neovim) and I have both `vimtex` and `vim-polyglot` installed via [`vim-plug`](https://github.com/junegunn/vim-plug). After a `:PlugUpdate` today, `vimtex` would simple crash on start, when opening a `.tex` file.
Running a `:checkhealth` would give me this:

```
health#vimtex#check
  ========================================================================
    - ERROR: No healthcheck found for "vimtex" plugin.

  health#vimtex#check
  ========================================================================
    - ERROR: No healthcheck found for "vimtex" plugin.
```

So I had no ideia what could be causing this behaviour. A quick google search led me here. After uninstalling `vim-polyglot` with `:PlugClean`, `vimtex` started working again. So it seems like https://github.com/sheerun/vim-polyglot/commit/d757bfd643cc73c2d495355c153ed0257f5d5b47  is indeed breaking something. After reverting to 8ec73a3a8974a62a613680a6b6222a77a7b99546 with 
```Plug 'sheerun/vim-polyglot', { 'commit': '8ec73a3a8974a62a613680a6b6222a77a7b99546'}```
everything is back to working as expected.

**Comment by wookayin** [comment]
I think d757bfd643cc73c2d495355c153ed0257f5d5b47 is the suspect: this overrides autoload path, making `autoload/vimtex.vim` from vimtex never loaded. Did the author ever test it with having vimtex as well? This file should be removed.

**Comment by sheerun** [comment]
if you update vim-polyglot does it still happen? I don't get any errors with following .vimrc:

```
call plug#begin()

Plug 'sheerun/vim-polyglot'

call plug#end()

```

**Comment by sheerun** [comment]
I've removed latex from vim-polyglot, it causes to many issues. We need some simple plugin with basic syntax and indent instead.

**Comment by vtnpp** [comment]
Can confirm I no longer have the warning now that you removed latex.
