### ISSUE TITLE
C/Cpp files commentstring is wrongly set to #

### ISSUE THREAD

**Issue by antoinemadec** [sheerun/vim-polyglot#486]
**Does this bug happen when you install plugin without vim-polyglot?**
The bug only happens when vim-polyglot is loaded.

**Describe the bug:**
polyglot wrongly set ```commentstring=# %s``` by default.
This results in C/Cpp files having the wrong commentstring.

This bug is due to this line:
https://github.com/sheerun/vim-polyglot/blob/master/ftdetect/polyglot.vim#L1242

I think line 1241 and 1242 are missing a ```autocmd BufRead,BufNewFile *.rego``` before setting those options?

**To Reproduce:**

- open a C file
- type: ```:set commentstring```

**Comment by sheerun** [comment]
I've removed rego from vim-polyglot for the time being. This should fix it

**Comment by bzp99** [comment]
Since then, the issue has been resolved in [tsandall/vim-rego](https://github.com/tsandall/vim-rego), so I suppose rego support can be re-enabled.

https://github.com/tsandall/vim-rego/commit/c383f053acee421a1bd01b2351df52ab09d2323f
