### ISSUE TITLE
HTML not highlighted in Jinja2 templates

### ISSUE THREAD

**Issue by bbc2** [sheerun/vim-polyglot#489]
When I open `foo.html.j2`, the HTML is not highlighted, just the Jinja2 syntax.

To fix it, I have to do `set ft=jinja` (it was `jinja2` before).

I think it's a bug in Polyglot because there's an inconsistency in `ftdetect/polyglot.vim`:  One line sets `ft=jinja` for `*.j2` files, but another line sets `ft=jinja2` (in `setupTemplates`).  One of these lines should probably be changed, but I'm not sure which one.

**Comment by sheerun** [comment]
newest version should fix this

**Comment by bbc2** [comment]
Awesome, thanks!
