### ISSUE TITLE
Error in gdscript ftplugin

### ISSUE THREAD

**Issue by emersonmx** [sheerun/vim-polyglot#493]
**Does this bug happen when you install plugin without vim-polyglot?**
No.

**Describe the bug:**
The problem is caused by https://github.com/sheerun/vim-polyglot/blob/master/ftplugin/gdscript3.vim#L22
Because the `python/init.py` doesn't exists.

In #483 was said that the plugin has **no advanced functionality, just indent and syntax support**, but the ftplugin has a custom omnifunc that uses a python script.

I propose remove the `ftplugin/gdscript3.vim` file.
See #494 

**To Reproduce:**
Opening a gdscript file gives the error below.

```
Erro detectado ao processar function provider#python3#Call:
linha   18:
Error invoking 'python_execute_file' on channel 4 (python3-script-host):
error caught in request handler 'python_execute_file ['/home/emersonmx/code/dotfiles/nvim/plugged/vim-polyglot/ftplugin/../python/init.py', 1, 1]':
Traceback (most recent call last):
  File "/home/emersonmx/.config/nvim/plugged/python-support.nvim/autoload/nvim_py3/lib/python3.8/site-packages/pynvim/plugin/script_host.py", line 105, in python_execute_file
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/emersonmx/code/dotfiles/nvim/plugged/vim-polyglot/ftplugin/../python/init.py'
Aperte ENTER ou digite um comando para continuar
```

**Comment by sheerun** [comment]
thanks for PR, it should be fixed
