### ISSUE TITLE
Wrong filetype in markdown files from a Jekyll project

### ISSUE THREAD

**Issue by gerardbm** [sheerun/vim-polyglot#495]
I updated the plugin and when I work with my Jekyll files (posts in markdown), Vim is not setting the filetype that should be: `liquid` instead of `markdown`.

This bug is not related to the markdown plugin, because I'm using the option:

```viml
let g:polyglot_disabled = ['markdown']
```

This worked fine until this commit: [cdb8e233c2e01c835ec78ae453c9793ade224309](https://github.com/sheerun/vim-polyglot/commit/cdb8e233c2e01c835ec78ae453c9793ade224309)

So now I Install vim-polyglot specifying the previous commit:

```viml
Plug 'sheerun/vim-polyglot', { 'commit' : 'ff282f6' }
```

**Comment by sheerun** [comment]
what is the file path in project?

**Comment by gerardbm** [comment]
The jekyll project? The pwd is `/home/<user>/Workspace/<project>`

**Comment by sheerun** [comment]
I mean the path of file within project directory

Probably the error is because you include your plugin before vim-polyglot, not after

**Comment by sheerun** [comment]
yeah, it seems the case: https://github.com/gerardbm/vimrc/blob/master/vim/.vimrc#L189

vim-polyglot is meant to set default handling for all languages which can be overridden by other plugins. you need to move vim-polyglot at the beginning of your vimrc, or at least before other plugins that change ftdetect

**Comment by gerardbm** [comment]
Yes, it was the case! This works now! Thanks a lot, I close the issue.
