### ISSUE TITLE
Add vim help about vim-polyglot

### ISSUE THREAD

**Issue by jrwrigh** [sheerun/vim-polyglot#501]
~7 years ago, there was a request to add documentation to the plugin in #9. The main reason to not due that was the lack of documentation for syntax files and that most of documentation that exists documented functionality within a plugin directory.

Correct me if I'm wrong, but I'd say things have changed a decent bit in 7 years. This plugin is no longer limited to just the syntax files and even then many syntax files have associated options with them. I think it'd be a good idea to start incorporating the documentation into this plugin. Thoughts?

**Comment by sheerun** [comment]
Vim-polygot strips plugin directory from plugins and imports just syntax and indentation

**Comment by sheerun** [comment]
Maybe we could consider adding some documentation about vim-polyglot itself like g:polyglot_disabled option and credits like in readme
