### ISSUE TITLE
incorrect spellcheck in Python f-strings

### ISSUE THREAD

**Issue by legeana** [sheerun/vim-polyglot#504]
**Does this bug happen when you install plugin without vim-polyglot?**
`Plug 'sheerun/vim-polyglot'` triggers it, `Plug 'vim-python/python-syntax'` does not.

**Describe the bug:**
Python f-strings have incorrect spellcheck errors:
![image](https://user-images.githubusercontent.com/46652755/85559062-3680cf80-b5de-11ea-8690-77964b9f40ec.png)

Expected behavior (`vim-python/python-syntax`): 
![image](https://user-images.githubusercontent.com/46652755/85558832-fc173280-b5dd-11ea-900c-e15384288573.png)

**To Reproduce:**
Clean vim installation:
```
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 19 2019 14:03:20)
$ curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
$ cat ~/.vimrc
call plug#begin()
Plug 'sheerun/vim-polyglot'  " triggers the bug
"Plug 'vim-python/python-syntax'  " does not trigger the bug
call plug#end()
set spell
```

```
$ cat /tmp/123.py
a = 'some text wrd'
print(f'hello {a}')
```

**Comment by sheerun** [comment]
It seems to be working now
