### ISSUE TITLE
Markdown: color heading markers

### ISSUE THREAD

**Issue by nu8** [sheerun/vim-polyglot#508]
If you have Markdown like this:

~~~
# Sunday
~~~

it appears current syntax only allows coloring for the text and not the marker.
This is a workaround:

~~~vim
syn region md_h1_text matchgroup=md_h_mark start=/^# / end=/$/
~~~

**Comment by sheerun** [comment]
Please raise this issue in https://github.com/plasticboy/vim-markdown instead

**Comment by nu8** [comment]
https://github.com/plasticboy/vim-markdown/issues/400
