### ISSUE TITLE
tsx syntax error

### ISSUE THREAD

**Issue by ggsalas** [sheerun/vim-polyglot#509]
Hi, I have reported this bug to `yats.vim`:  https://github.com/HerringtonDarkholme/yats.vim/issues/181
![image](https://user-images.githubusercontent.com/8403993/86680725-3d8fe080-bfd5-11ea-9b48-7f246edcf293.png)

The way to avoid this bug is resourcing the vimrc config. I'm wondering if this bug is related to the way that vim-polyglot is loading the plugin. There is a way to avoid the async load for tsx files?

Thanks

**Comment by sheerun** [comment]
I don't think they are loaded asynchronously
