### ISSUE TITLE
Consider fork of vim-json

### ISSUE THREAD

**Issue by onemanstartup** [sheerun/vim-polyglot#51]
It is more improved and maintained https://github.com/elzr/vim-json

**Comment by renstrom** [comment]
My only objection is that the conceal feature is on by default. It's a bit weird if you don't know about it.

**Comment by onemanstartup** [comment]
But it possible to disable this in polyglot and making this default

**Comment by lfilho** [comment]
Sounds good! +1

**Comment by sheerun** [comment]
Concealing disabled would need to be a default :(

**Comment by sheerun** [comment]
I forked vim-json, removed concealing at all, and switched provider of JSON syntax.

vim-polyglot v1.13.0 is now released. Thanks guys :)

**Comment by naquad** [comment]
Looks like its not :( I'm on master and still can't turn the damn conceal level off.

**Comment by renstrom** [comment]
I don't have that problem, are you sure you don't have both installed?

**Comment by naquad** [comment]
```
[15:54:22] (001) naquad@nq.od.ua ~/.vim ❯❯❯ ls -l bundle | grep json | wc -l                                                                                                                                     ⏎
0
[15:54:22] (000) naquad@nq.od.ua ~/.vim ❯❯❯ 
```

after installing polyglot I've removed old repos.

**Comment by renstrom** [comment]
Scratch that, I'm also getting this. It seems like this is the culprit: https://github.com/sheerun/vim-polyglot/blob/master/syntax/json.vim#L20

Not sure if it snuck in during an update or something.

**Comment by sheerun** [comment]
Do you know what should be the solution? What works for you?

**Comment by sheerun** [comment]
Disabling concealing when using original plugin works for me. Here is what I use:

```
let g:vim_json_syntax_conceal = 0
Plug 'sheerun/vim-polyglot'
Plug 'elzr/vim-json'
```

If it doesn't work for you, please provide me a way to reproduce this bug.

**Comment by yoshuawuyts** [comment]
Alternatively `:set cole=0` will disable conceal for all plugins. `:set cole=2` will restore the original setting. I used this method to disable both markdown and json concealing.
