### ISSUE TITLE
markdown - conflict with vim-markdown-quote-syntax plugin

### ISSUE THREAD

**Issue by sunaku** [sheerun/vim-polyglot#512]
**Does this bug happen when you install plugin without vim-polyglot?**

No.

**Describe the bug:**

```vim
Error detected while processing /usr/share/vim/vim82/syntax/vim.vim:
line  825:
E403: syntax sync: line continuations pattern specified twice
Error detected while processing function <SNR>336_MarkdownRefreshSyntax[2]..<SNR>336_MarkdownHighlightSour
ces:
line   31:
E171: Missing :endif
Error detected while processing function <SNR>336_MarkdownRefreshSyntax:
line    2:
E171: Missing :endif
Press ENTER or type command to continue
```

**To Reproduce:**

First, install this additional markdown plugin:
- https://github.com/joker1007/vim-markdown-quote-syntax

Then edit any Markdown file, such as `vim README.md`.

Now observe the Vim error message illustrated above.

**Comment by sheerun** [comment]
vim-polyglot supports it out of the box, you can remove this plugin
