### ISSUE TITLE
Recent update breaks Dhall filetype

### ISSUE THREAD

**Issue by cideM** [sheerun/vim-polyglot#519]
[A recent commit](https://github.com/sheerun/vim-polyglot/commit/56121b4e27cb48efb17be55a969b2f0d725266f8#diff-7de199a8f849cd6390a96334f5904509L11-L12) updated the Dhall `ftplugin`. The new version of that filetype plugin refers to an autocommand group which is [created in the `ftdetect` file for that plugin](https://github.com/vmchale/dhall-vim/blob/master/ftdetect/dhall.vim). As a result, opening a `.dhall` file with the most recent `vim-polyglot` leads to `E216: No such group or event: dhall`

I don't know enough about vim/neovim to have an opinion on if the usage of a "bare" `autocmd!` is considered good or not. So this can either be fixed in that plugins source, by wrapping the reset call in an `augroup dhall` or if this should be handled by `vim-polyglot`.

I'd be more than happy to file an issue on that plugin's tracker if that's the right place to make the change.

**Comment by sheerun** [comment]
This is bug on dhall side. They are resetting augroup which makes `:e something.dhall` to not detect filetype

**Comment by sheerun** [comment]
I've sent PR fixing it there: https://github.com/vmchale/dhall-vim/pull/12
