### ISSUE TITLE
C++ Folding Blocks Bug

### ISSUE THREAD

**Issue by theNerd247** [sheerun/vim-polyglot#52]
The c++ fold syntax behaves buggy with block folds. Any block fold seems to end on the last fold found in the file. E.g: 

    func1()
    { //<--- fold starts here

    }

    func2()
    {

    }//<---- fold ends here
This error does not occur is C files (only C++). Also this bug seems to only apply to a newly written c++ file when it has been written to for the first time which seems to imply that the error happens during some parsing stage when the file buffer is newly loaded. Also comment folds have no affect on this bug (as far as I've observed)

**Comment by theNerd247** [comment]
A temporary fix for this issue is removing all c and cpp.vim files from the after/ and syntax directories (at least those installed by polyglot). I'm not sure why this works as I'm not familiar with the vim language nor the syntax files.

**Comment by sheerun** [comment]
Could you try to find cpp syntax that doesn't experience this issue?

**Comment by theNerd247** [comment]
Do you mean a cpp syntax file? or cpp source code?

**Comment by sheerun** [comment]
github repository with cpp syntax

**Comment by theNerd247** [comment]
I'm not sure what you mean. I haven't found any CPP source code (.h, .cpp files etc.) that this doesn't experience this issue, if that's what your looking for. I did notice that nested function calls does not generate this bug: 

    int func1()
    {
        int func2()
        { //<--- when folding here ...
        } //<-- the fold ends here as  it should.
    }

**Comment by sheerun** [comment]
I'll put it another way. Currently we use vim-jp/cpp-vim for CPP syntax. Could you find replacement that has correct folding behavior?

**Comment by theNerd247** [comment]
I'll look for a replacement. It appears that the default syntax files (in my ../vim74/{syntax/, after/} work properly

**Comment by sheerun** [comment]
vim-polyglot cpp syntax seems exactly the same as vim's official...

- https://raw.githubusercontent.com/b4winckler/vim/master/runtime/syntax/cpp.vim
- https://raw.githubusercontent.com/sheerun/vim-polyglot/master/syntax/cpp.vim

**Comment by sheerun** [comment]
NVM, there are different after syntaxes..

**Comment by theNerd247** [comment]
ok, maybe it's the c.vim as well? since both files import c.vim

**Comment by sheerun** [comment]
I tried to reproduce this issue and I unable to do so.

vim-polyglot also uses: https://github.com/octol/vim-cpp-enhanced-highlight

Please try to uninstall vim-polyglot, install vim-cpp-enhanced-highlight, and check if it introduces error.

If so, you can try to fix it and send them PR or we can try to find better package..

**Comment by theNerd247** [comment]
Oddly that did not generate any errors.I un-installed vim-cpp-enhanced-highlight and reinstalled polyglot and the errors were regenerated.

**Comment by sheerun** [comment]
I updated all packages and released new version. Please try now.

Any help with pinpointing this bug is appreciated, as I cannot reproduce.

**Comment by theNerd247** [comment]
If the error can't be reproduced with vim-polyglot alone could it be something in another package or my vimrc? here is mine: https://github.com/theNerd247/vimrc

**Comment by sheerun** [comment]
Maybe. Try to install vim-polyglot as the only plugin and check if it works.

**Comment by theNerd247** [comment]
Alrighty. I've confirmed after removing everything but Vundle (which shouldn't be an issue any way). It is polyglot - or something in my .vim/

**Comment by sheerun** [comment]
What is your vim version?

**Comment by theNerd247** [comment]
vim 7.4.580-1 I'm on ArchLinux

**Comment by sheerun** [comment]
Sorry, really I cannot reproduce: https://v.usetapes.com/PIdygAOJAa

Something is wrong with your environment...

**Comment by theNerd247** [comment]
try using
    namespace 
    {
       func1()
       {
       }
      func2()
      {
      }
    }

the above example doesn't seem to be reproducing the error as well. I apologize for that. Also I removed polyglot and saved the after/syntax and syntax/ c.vim and cpp.vim (installing them as if they were installed without Vundle) and this reproduced the error. In this case I think it is something within these files (or an order of operations -- something is getting loaded when it shouldn't or vis-versa)

**Comment by sheerun** [comment]
Still, cannot reproduce: https://v.usetapes.com/MN0J0oK7Pj

**Comment by theNerd247** [comment]
you didn't indent your functions

**Comment by theNerd247** [comment]
try it with this file

https://github.com/theNerd247/NoteCleaner/blob/master/NoteCleaner.cpp

**Comment by theNerd247** [comment]
I'm noticing that this is also causing the issue

    namespace
    {
        class
        {
            func()
            {

             }
        }
    }

**Comment by sheerun** [comment]
Thanks. I finally managed to reproduce issue..

I pinpointed issue to [c-extensions](https://github.com/sheerun/vim-polyglot/blob/6745c49110838db9ac39e85bbcf690b40bc20f83/after/syntax/c.vim#L556) plugin. I removed it entirely from vim-polyglot.

Your example seems to work now.  New version is available. Cheers!

**Comment by theNerd247** [comment]
Excellent! Thanks!
