### ISSUE TITLE
Jenkinsfile groovy 

### ISSUE THREAD

**Issue by run2cmd** [sheerun/vim-polyglot#520]
**Does this bug happen when you install plugin without vim-polyglot?**
No.

**Vim version**
IM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 30 2020 22:02:11)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1328

**Describe the bug:**
I get error when loading Jenkinsfile and Gradle files. Seems that it has to do with loading groovy.vim and latest changes that where made there.

```
"Jenkinsfile" [unix] 98L, 2906B
Error detected while processing BufRead Autocommands for "Jenkinsfile"..FileType Autocommands for "*"..Syntax Autocommands for "*"..function <SNR>8_SynSet[25]..script C:\Users\pbugala\.vim\pack\run2cmd\start\vim-polyglot\syntax\Jenkinsfile.vim[3]..C:\tools\vim\vim82\syntax\groovy.vim:
line  256:
E945: Range too large in character class
```

**To Reproduce:**
I have noticed that this is not happening every time. Sometimes I open the file and I do not get that error. To reproduce try to open any Jenkinsfile or *.gradle file.

**Comment by sheerun** [comment]
Then probably it should be reported there? I guess https://github.com/martinda/Jenkinsfile-vim-syntax or https://github.com/tfnico/vim-gradle
