### ISSUE TITLE
F# syntax collapse with GLSL syntax

### ISSUE THREAD

**Issue by adelarsq** [sheerun/vim-polyglot#523]
**Does this bug happen when you install plugin without vim-polyglot?**
No.

**Describe the bug:**
Both [Ionide-vim](https://github.com/ionide/Ionide-vim) and [vim-glsl](https://github.com/tikhomirov/vim-glsl) has support for `*.fs`files, so the filetypes collapse.
It's possible to add F# support default and a new config to enable `vim-glsl` without `*.fs` filetype?

**To Reproduce:**
Open a `*.fs` file and will be defined as `glsl` file.

**Comment by sheerun** [comment]
As quickfix I have priority for fs files to #F, proper fix will be in #498
