### ISSUE TITLE
Some Perl files are recognized as Raku

### ISSUE THREAD

**Issue by ferki** [sheerun/vim-polyglot#524]
**Does this bug happen when you install plugin without vim-polyglot?**

As far as I can tell, no.

**Describe the bug:**

Some Perl files, like `*.pm`, `*.pl`, and `*.t`, are recognized as Raku instead of Perl since v4.5.0 of vim-polyglot. There might be other extensions affected.

v4.4.3 seems to be working fine. Perhaps it's a side effect of switching to linguist, and/or changed priorities?

As far as I can tell, the same extensions are used by both plugins, and they might not be easy to remove from vim-raku, since [older Raku code might still use them](https://github.com/Raku/vim-raku/pull/12#issuecomment-627630129) (instead of `*.pm6` and `*.t6`, if I understand correctly).

I speculate that there might be still more Perl code out there, than Raku code, so leaning towards Perl over Raku in these ambiguous cases might have a higher chance of correct detection (and seemingly [linguist does that too](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml#L351-L358)).

**To Reproduce:**

Open a `*.pm`, `*.pl`, or `*.t` file that contains Perl code.

**Comment by sheerun** [comment]
vim-polyglot now lets vim decide for ambiguous extensions like .pm, .pl, or .t so this should be fixed.

If you'd like better heuristics that will be implemented soon, please send PR to https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml For now Raku is not covered there as far as I see

**Comment by ferki** [comment]
Thanks! It does solve my issue for now :+1:
