### ISSUE TITLE
g:polyglot_disabled is not working properly in the latest version

### ISSUE THREAD

**Issue by yaegassy** [sheerun/vim-polyglot#525]
## Describe the bug:

g:polyglot_disabled does not work correctly after this [commit](https://github.com/sheerun/vim-polyglot/commit/d821de3142fc67592686cba3f09ce91eac7cee0d).

Let's take the file `setup.cfg` as an example.

Setting `g:polyglot_disabled` to `['haproxy']` will still set the file type to `haproxy`. :(

If it works correctly, the file type should be `cfg`.

I'm attaching a GIF of a minimal vimrc and a DEMO(NG and OK).

### minimal.vimrc

```vim
"""""""""""""""""""""""""""""
"  minimal.vimrc (vim-plug) "
"""""""""""""""""""""""""""""

call plug#begin('~/tmp/plugged-polyglot-check')
  Plug 'sheerun/vim-polyglot'

  " It works correctly until this commit.
  "Plug 'sheerun/vim-polyglot', { 'commit': 'a3bdbcdb3c60a9563fb90e02b28ae46cee5ef974' }
call plug#end()

syntax on
filetype plugin indent on
set laststatus=2

let g:polyglot_disabled = ['haproxy']
```

### [NG]DEMO

![polyglot-ng-960](https://user-images.githubusercontent.com/188642/90997687-2e083d80-e5fd-11ea-87bb-16962414a13e.gif)

### [OK]DEMO

I tried with this [commit](https://github.com/sheerun/vim-polyglot/commit/a3bdbcdb3c60a9563fb90e02b28ae46cee5ef974) and it was fine.

![polyglot-ok-960](https://user-images.githubusercontent.com/188642/90997698-395b6900-e5fd-11ea-8919-5dc9dca29b85.gif)

**Comment by timacdonald** [comment]
Not sure if it completely related at this point, but I lost "blade" highlighting with the latest version. Just pinned to the previous version...

```
Plug 'sheerun/vim-polyglot', { 'tag': 'v4.4.3' }
``` 

and it restored highlighting

**Comment by yaegassy** [comment]
@sheerun @timacdonald 

Same.

The latest version of polyglot "does not" recognize the `blade` and has a `php` filetype... :(

**Comment by yaegassy** [comment]
@sheerun @timacdonald

As for the `blade`, I found the cause.

1. First match to `blade` in `ftdetect/polyglot.vim` -> `filetype=blade`
    - https://github.com/sheerun/vim-polyglot/blob/master/ftdetect/polyglot.vim#L81-L84
2.  After that, it also matches the `php` block and the filetype is php -> `filetype=php`
    - https://github.com/sheerun/vim-polyglot/blob/master/ftdetect/polyglot.vim#L723-L738

It seems to be caused by a symptom of multiple matches in `ftdetect/polyglot.vim`, where the last matched autocmd is the one whose filetype is determined.

I think it needs to be fixed and adjusted.

**Comment by josecanhelp** [comment]
@yaegassy and @timacdonald this looks more like an issue with a divergence of `master` and `v4.5.0`. 

`Plug 'sheerun/vim-polyglot', { 'tag': 'v4.5.0' }`

This works for me ☝️ 

In `master`, I see some scripts (including build) have been moved into a `scripts` directory, but there is no `build.py` in `master` as there is in `v4.5.0`.

**Comment by sheerun** [comment]
There was a big refactor, unfortunately some bug are unavoidable, please report them.

@yaegassy Your issue with blade should be fixed. I've checked `g:polyglot_disabled` and it works properly for me, the `let g:polyglot_disabled = ['haproxy']` should be at the top of the file.

**Comment by sheerun** [comment]
Also syntax on, etc. should be before your plug code

**Comment by sheerun** [comment]
Here's .vimrc that should work for you. I'll also disable for now resolving ambiguous extensions like `.cfg`, so you don't need to disable haproxy

**Comment by yaegassy** [comment]
@sheerun 

Thanks for the reply.

Setting `let g:polyglot_disabled` prior to calling the plugin worked fine.

Sorry. I see that was documented. https://github.com/sheerun/vim-polyglot#troubleshooting

> " ~/.vimrc, declare this variable before polyglot is loaded`

My problem is solved.

----

@timacdonald 

The `blade` issue is a separate issue, please create a new issue.

**Comment by sheerun** [comment]
@yaegassy You should be able to use vim-polyglot now without disabling haproxy (we let vim decide what to do for .cfg files)

**Comment by sheerun** [comment]
@timacdonald blade issue should be fixed now as well

**Comment by yaegassy** [comment]
In my environment, after updating to the latest version of vim-polyglot, the `blade` is recognized correctly. Thanks @sheerun
