### ISSUE TITLE
jsonnet does not auto format when save 

### ISSUE THREAD

**Issue by samhvw8** [sheerun/vim-polyglot#526]
Hi, when i edit jsonnet file then save but it does not auto format 

**Does this bug happen when you install plugin without vim-polyglot?**
No, this does not happed 
**Describe the bug:**
Following the doc , i set `let g:jsonnet_fmt_on_save = 1 `, but noting happend when save jsonnet file
**To Reproduce:**
set `let g:jsonnet_fmt_on_save = 1 ` then save some jsonnet file

Note: may be polygot missing this file https://github.com/google/vim-jsonnet/blob/master/plugin/jsonnet.vim#L12 from jsonnet 

Please Help, 
Thanks

**Comment by sheerun** [comment]
that's expected, if you want advanced features like this you need to install plugin itself

**Comment by samhvw8** [comment]
oh, thank you
