### ISSUE TITLE
JSX detection no longer working after upgrade

### ISSUE THREAD

**Issue by danbroooks** [sheerun/vim-polyglot#528]
I upgraded this plugin to the latest version yesterday, and since then JSX syntax highlighting is nolonger working. I had a look through previous issues and found https://github.com/sheerun/vim-polyglot/issues/460, which I initially presumed was the same issue. However my issue related to `vim` and not `neovim`, and checking out the plugin at the commit for the fix here: https://github.com/sheerun/vim-polyglot/commit/16774887a3fe26a09326585f871748ddf158905e gets highlighting to work again.

I traced through subsequent commits, and pinpointed this commit which is the point where `jsx` highlighting stops working again:

https://github.com/sheerun/vim-polyglot/commit/cdb8e233c2e01c835ec78ae453c9793ade224309

My workaround for the time being will be to run this plugin at the commit previous to this, by adding this command to `.vimrc`:

```
silent! let g:plugs['vim-polyglot'].commit = 'ff282f610f871114fc5fa51f8c43d8b371aebbaf'
```

**Comment by sheerun** [comment]
works for me. what's your vimrc?

**Comment by sheerun** [comment]
also, what happens when you leave just vim-polyglot (and upgrade it) and disable all other plugins?

**Comment by taylon** [comment]
I'm running into the same issue but with different file types (reason and dune were the ones I noticed)

Reverting to the same commit mentioned in the original report fixed the issue for me as well

**Comment by sheerun** [comment]
which filetypes?

**Comment by sheerun** [comment]
which extensions?

**Comment by sheerun** [comment]
@taylon ocaml (including dune) and reason should work again

**Comment by danbroooks** [comment]
@sheerun yeah, I am still seeing this issue with only this plugin enabled in my vimrc file:

```
call plug#begin()
Plug 'sheerun/vim-polyglot'
call plug#end()
```

**Comment by sheerun** [comment]
I made sure that all ftdetect extensions and paths that were covered, are covered.

@danbroooks Such vimrc works perfectly well for me for example for following `link.js` file (jsx is highlighted)

```
import React from 'react'
import { inject, observer } from 'mobx-react'
import { Link as AppLink } from '../app'

@inject('i18n')
class Link extends React.Component {
  render () {
    return <AppLink language={this.props.i18n.language} {...this.props} />
  }
}

@inject('search')
@observer
class SearchLink extends React.Component {
  static defaultProps = {
    replace: false
  }

  render () {
    const { search, filters = {}, children, replace } = this.props
    const { query, pathname, hash } = search.filtersToUrl(filters)

    return (
      <AppLink
        pathname={pathname}
        query={query}
        replace={replace}
        hash={hash}
        language={false}
      >
        {children}
      </AppLink>
    )
  }
}

export { SearchLink, Link }
```

Does it work for you?

**Comment by danbroooks** [comment]
@sheerun it seems like the highlighting is fine for `.js` files, the issue is files with the `.jsx` extension, see the file you pasted above loaded with the `.js` (left) and `.jsx` (right) extensions:

![Screenshot from 2020-08-27 15-15-20](https://user-images.githubusercontent.com/2951404/91454151-88610280-e878-11ea-9462-3521bdd3644f.png)

Sorry, my description of this issue is confusing, that is my fault (it would seem the JSX highlighting itself is actually working here) the issue is that the JS highlighting isn't working for `.jsx` files, whereas it was on `ff282f610f871114fc5fa51f8c43d8b371aebbaf`. Sorry about that!

**Comment by sheerun** [comment]
If I name this file .jsx it works as well, could you try to update vim-polyglot and try again?

**Comment by sheerun** [comment]
There were some changes, maybe it works now?

**Comment by wzrdtales** [comment]
same problem. There is some highlighting active, but certainly the wrong one and not the one that should be selected for javascript.

**Comment by wzrdtales** [comment]
so not just jsx, pure javascript is broken as well, the mentioned commit in the description of the issue works well for me. Latest version as well broken still

**Comment by sheerun** [comment]
what is displayed when you run `:set ft`?

**Comment by wzrdtales** [comment]
![image](https://user-images.githubusercontent.com/1786821/91853472-89bc7180-ec62-11ea-9704-d96ede61b61a.png)

**Comment by sheerun** [comment]
it looks correct... I think some other plugin is interfering, it probably should work when you leave just vim-polyglot

**Comment by wzrdtales** [comment]
As said, there is some syntax highlighting, but it is broken: Broken in regards:

https://github.com/statico/vim-javascript-sql

That this plugin does not work anymore. tagged js string literals with SQL in front of it will end up in a never ending string and screw up the whole highlighting for the whole file. This is not related to vim-javascript at all tested it standalone without vim-polyglot already and it is only in the latest version of vim-polyglot a problem. So I guess it is using the wrong syntax tooling.

**Comment by wzrdtales** [comment]
Nope, did deactivate everything already once except vim-polyglot and sql tag, it is still broken then.

**Comment by wzrdtales** [comment]
I will stick with that commit from the description for now and refrain from any upgrades, if you need anymore information to get this fixed feel free to reach out.

**Comment by wzrdtales** [comment]
Ok, here is the max I can do for this right now @sheerun 
This seems to be related to the sql highlighting and a malfunctioning plugin loaded by polyglot

The regression is here: https://github.com/sheerun/vim-polyglot/commit/7e38f4288a4f7199240d8a8fce87c8d0cc0198c3

So the introduced sql plugin breaks it. However this SQL plugin does no tag highlighting at all, so it normally shouldn't interfere.

This is how it looks with only polyglot latest:

![image](https://user-images.githubusercontent.com/1786821/91855652-be7df800-ec65-11ea-8d81-41f6d2efafe5.png)

This is before polyglot broke and with the this plugin https://github.com/statico/vim-javascript-sql and how it should look like

![image](https://user-images.githubusercontent.com/1786821/91855745-dce3f380-ec65-11ea-9bce-ff1fca14bc35.png)

**Comment by sheerun** [comment]
@wzrdtales Thank you! I've removed this plugin and notified the author: https://github.com/shmup/vim-sql-syntax/issues/3

**Comment by sheerun** [comment]
@wzrdtales By the way vim-javascript-sql is now shipped in vim-polyglot

**Comment by sheerun** [comment]
I'll consider this issue closed, if someone still has some issues with javascript, please open another issue with steps to reproduce (minimal .vimrc)

**Comment by wzrdtales** [comment]
@sheerun Great, one less plugin to load for me :)
