### ISSUE TITLE
Performance regression when opening Ansible YAML files

### ISSUE THREAD

**Issue by ybc37** [sheerun/vim-polyglot#529]
First, thanks for vim-polyglot! :smile: 

**Does this bug happen when you install plugin without vim-polyglot?** No

**Describe the bug:**
With the latest ftdetect changes/refactoring, Ansible (YAML) files take too long to open (~5s on my machine, but without measuring it precisely). Maybe related: https://github.com/sheerun/vim-polyglot/pull/518

**To Reproduce:**
Open a YAML file in an Ansible project. I don't have a public repo, but used Arch Linux infra repo to reproduce:
1. `git clone https://gitlab.archlinux.org/archlinux/infrastructure.git && cd infrastructure`
2. `nvim roles/common/tasks/main.yml`

**Comment by sheerun** [comment]
It loads immediately for me. Could you please attach load logs produced with:

`nvim roles/common/tasks/main.yml --startuptime startup.log`

**Comment by ybc37** [comment]
Thanks for checking @sheerun!

You're right, after disabling all plugins but vim-polyglot it starts immediately. Turns out it only occurs, when https://github.com/tpope/vim-sleuth/ is enabled. I'm not sure whats wrong, but still, before creating this issue I checked without vim-polyglot and only https://github.com/pearofducks/ansible-vim and that worked. So I wonder what's the root of this (vim-sleuth or vim-polyglot). Maybe they just don't play well together :) 

Anyway I attache the startup log with only vim-polyglot and vim-sleuth enabled:
[startup.log](https://github.com/sheerun/vim-polyglot/files/5129808/startup.log)

**Comment by sheerun** [comment]
vim-sleuth is really slow so it's not in my plugins as well. I guess it's because new setup doesn't setup shiftwidth and expandtab manually so sleuth tries to detect it which is really slow. I'll check this, but I suggest you just remove sleuth

**Comment by ybc37** [comment]
The weird thing is that I the performance only drops, if both plugins are enabled. If I disable vim-polyglot, vim-sleuth doesn't cause such performance issues.

I can also reproduce the same behavior with a `package.json` in one of my projects, but it's not a general issue with json files.

vim-sleuth may be a bit slow, but still is really helpful in projects without Editorconfig or similar :wink: 

Maybe I find some time soon to debug it and get more details.

**Comment by sheerun** [comment]
It seems to be because

a) surprisingly vim-sleuth is able to detect only 8-characters-long soft tabs which is why it fails to detect softtabs for yaml file which has no lines indented with less than 8 spaces
b) if vim-sleuth fails to detect soft tabs in current files, it tries other files of the same filetype. to do so it reads autocommands table which is very long if you use vim-polyglot
c) them sleuth does the same for each of neighboring files

I think the best solution is to embed optimized version of sleuth in vim-polyglot

**Comment by ybc37** [comment]
Thank @sheerun! I didn't expect this and I really appreciate it! As far as I can tell, it works like a charm :smile:
