### ISSUE TITLE
Powershell Filetype Detection is Broken Because of `filetype` Mismatch

### ISSUE THREAD

**Issue by Furkanzmc** [sheerun/vim-polyglot#531]
**Does this bug happen when you install plugin without vim-polyglot?**

No.

**Describe the bug:**

With commit 00015bd10507181797dd74cbba375f9e88c61e51, the file type for PowerShell files is changed to `powershell` from `ps1`. The plugin that is used looks for `ps1`. I'm not sure where is a good place to fix this. Should this repository revert to `ps1` as `filetype` or should the upstream repository be updated to use `powershell` for `filetype`.

**To Reproduce:**

Just opening a `*.ps1` file does the trick. Syntax highlighting etc is broken.

**Comment by Neur1n** [comment]
Same issue here. The filetype was set by
https://github.com/sheerun/vim-polyglot/blob/d4fcef1aa835f20f4f9df41eceb406b66f446f70/ftdetect/polyglot.vim#L766

**Comment by sheerun** [comment]
v4.6.0 should work (just update), mind to check?

**Comment by Neur1n** [comment]
It works like before now.

But, just asking, is `ft=powershell` used by anything? Or was it simply a mistake? :)

**Comment by sheerun** [comment]
there was huge refactor of filetypes, simply a mistake :)
