### ISSUE TITLE
Terraform filetype detection on Neovim

### ISSUE THREAD

**Issue by katsika** [sheerun/vim-polyglot#533]
**Does this bug happen when you install plugin without vim-polyglot?**

Nope, does not happen when `hashivim/vim-terraform` is installed (without `vim-polyglot`) directly.

**Describe the bug:**

On Neovim 0.4.4, terraform files are not getting correct filetype set. Neovim's `/usr/local/Cellar/neovim/0.4.4/share/nvim/runtime/filetype.vim` has in line 1682

```
  " TF mud client
  au BufNewFile,BufRead *.tf,.tfrc,tfrc>> setf tf
```

which is also used by terraform. `vim-polyglot` should set filetype to `terraform` based on [this](https://github.com/sheerun/vim-polyglot/blob/63119f09d1390b61155cc0dc3ff497356d2fc7e5/ftdetect/polyglot.vim#L1268) but it doesn't.

**To Reproduce:**
Install polyglot for Neovim 0.4.4, open any .tf file, filetype will be `tf` instead of desired `terraform`.

**Comment by sheerun** [comment]
thanks for noticing, it should be fine now

**Comment by katsika** [comment]
Works great, thanks!
