### ISSUE TITLE
[Add language] Add support for Idris 2 as Idris 1 is slowly reaching EOL

### ISSUE THREAD

**Issue by CodingCellist** [sheerun/vim-polyglot#534]
The current release of vim-polyglot contains support for Idris 1. With Idris 2 being released on 1 April this year, Idris 1 will slowly be reaching its EOL.

There is a new vim plugin for Idris 2, hosted here: https://github.com/edwinb/idris2-vim

Since Idris 2 is meant as a successor to Idris 1, there is no difference in the file extensions, leading to the wrong plugin being loaded when working on Idris 2 files. Unfortunately, Idris 2 [is not backwards compatible](https://idris2.readthedocs.io/en/latest/updates/updates.html) with Idris 1 and we're currently in the awkward phase where both Idris 1 and Idris 2 are used since Idris 2 is not fully ready to succeed Idris 1 yet. I don't know if it is possible, but something like a prompt to ask which plugin to load when opening `.idr`-files would be very neat.

**Comment by sheerun** [comment]
do you mind to prepare heuristics in https://github.com/sheerun/vim-polyglot/blob/master/heuristics.yaml ?

**Comment by sheerun** [comment]
you can develop vim-polyglot by running "make dev" and editing yaml files

**Comment by sheerun** [comment]
you can add tests in scripts/test_extensions.vim

**Comment by CodingCellist** [comment]
I think I've done it, but I had no experience with developing vim-polyglot, so sorry if I got something wrong. There's a pull request: #535
