### ISSUE TITLE
Neovim: gO doesn't work in help pages anymore

### ISSUE THREAD

**Issue by nanotee** [sheerun/vim-polyglot#536]
Neovim has a slightly modified version of the `help.vim` ftplugin. It defines a `gO` mapping that populates the location list with a table of contents: https://github.com/neovim/neovim/blob/master/runtime/ftplugin/help.vim#L24-L94

A recent vim-polyglot update pulled Vim's version of that file, meaning the mapping doesn't work unless I use `let g:polyglot_disabled = ['help']`

(FWIW, the Neovim version seems to work just fine in Vim)

**Comment by sheerun** [comment]
Good find, I've switched polyglot to neovim version of help filetype

**Comment by nanotee** [comment]
Perfect, thank you for your work!
