### ISSUE TITLE
Add feature to disable language specific tab settings

### ISSUE THREAD

**Issue by esandoval99** [sheerun/vim-polyglot#537]
I recently updated this plugin, and I noticed that my default tab spacing settings are being modified by this plugin. Instead of 4 spaces, it is setting it to 2 in Javascript. I've since disabled it for Javascript, and I'm now using vim-javascript for this, which keeps tabs at 4 spaces. Would it be possible it add a feature that disables tab settings for all or specific languages?

**Comment by sheerun** [comment]
Could you post the file that causes it? I'd rather fix detection algorithm

**Comment by sheerun** [comment]
Also, could you post how you configure 4 spaces in your vimrc? I'll try to detect that and prevent modification

**Comment by sheerun** [comment]
By the way, until this is fixed I've implemented `let g:polyglot_disabled = ['autoindent']` flag that you can use to temporarily disable this feature. Ultimately I'd like this feature to work correctly and respect custom user settings

**Comment by sheerun** [comment]
@esandoval99 I think detection of indentation should work now, could you confirm?

**Comment by esandoval99** [comment]
Looks like its working. If you still need the Javascript file its 
```
var Datastore = require('nedb')
var collection = new Datastore({ filename: 'collection.db', autoload: true });

var template = {
    options: {
        "someOption1": [ "word1", "word2" ],
        "someOption2": [ "word1", "word2" ]
    },
    profile_id: "",
}

collection.insert(template, function (err, newDoc) {});

```
And I'm setting 4 spaces with 
```
set smartindent " apply indentation after { symbols
set tabstop=4 " show existing tab with 4 spaces width
set shiftwidth=4 " when indenting with >, <, and = use 4 spaces width
set softtabstop=4 " when indenting with tab and backspace use 4 spaces width
set expandtab " use softtabstop number of spaces when indenting 
set autoindent " apply indentation of current line to next line	
```

**Comment by sheerun** [comment]
good :) and thank you for .vimrc, it helps
