### ISSUE TITLE
Consider vim-better-css-completion and vim-better-javascript-completion

### ISSUE THREAD

**Issue by gummesson** [sheerun/vim-polyglot#54]
[vim-better-css-completion](https://github.com/1995eaton/vim-better-css-completion) adds support for CSS3 while [vim-better-javascript-completion](https://github.com/1995eaton/vim-better-javascript-completion) adds support for newer JavaScript globals and methods.

**Comment by sheerun** [comment]
Hey. Thanks for suggestion, but this is syntax-only plugin.

I'll consider creating another one for completions, though :)
