### ISSUE TITLE
New indentation detection flaws

### ISSUE THREAD

**Issue by zedtang** [sheerun/vim-polyglot#540]
**Does this bug happen when you install plugin without vim-polyglot?**
No.

**Describe the bug:**
I think the new indentation detection may be flawed, but I'm not sure because I don't know much about it. 

So I have a global setting of tabstop=4, shiftwidth=4, and a local setting for c/c++ of tabstop=8, shiftwidth=3. After updating to the latest  polyglot, when editing a c file, my shiftwidth is changed to 6, and that makes indentation 6 spaces.

I think the "bug" was introduced in  b2640b5b760e6fc68b8cc49d3c8bab6cdef4f889 after doing a git bisect.

After running `:verbose set shiftwidth`
  ```vim script
shiftwidth=6
        Last set from ~/.vim/plugged/vim-polyglot/plugin/polyglot.vim line 118
```
which is 
```Vim script
105     if line[0] == "\t"
106       setlocal noexpandtab
107       return 1
108     elseif line[0] == " "
109       let indent = len(matchstr(line, '^ *'))
110       if indent % 2 == 0 && indent < minindent
111         let minindent = indent
112       endif
113     endif
114   endfor
115
116   if minindent < 10
117     setlocal expandtab
118     let &shiftwidth=minindent
119     return 1
120   endif
121
122   return 0
123 endfunction
```
I tried to find the root cause, so I added some echom and surely it was picking up a line No.32 from another file, that basically contains this line
```C
30 #define some_macro() \
31    do { \
32       static int a; \
32   ...
```
The L32 here is indented 2 levels which is 6 spaces.
I think L108 in `polyglot.vim` picked up L32 here, and `len(matchstr(line, '^ *'))` returned 6, so minindent was set to indent and later shiftwidth was set to minindent.
I don't really know about the algorithm so I'm not sure how to fix it.

**To Reproduce:**
Here is a minimal repro. 
#### **`vimrc`**
```Vim script
call plug#begin(expand('~/.vim/plugged'))

Plug 'sheerun/vim-polyglot'

call plug#end()

filetype plugin indent on

set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

augroup vimrc-c/c++
  autocmd!
  autocmd FileType c,cpp setlocal tabstop=8 shiftwidth=3
  autocmd BufNewFile,BufRead *.h setlocal filetype=c
augroup END
```
#### **`foo.c`**
```C
/* **********************************************************
 * comments
 * comments
 * comments
 * comments
 * comments
 * comments
 * comments
 * comments
 * comments
 * comments
 * comments
 * comments
 * **********************************************************/

/*
 * comments
 * comments
 * comments
 * comments
 * comments
 * comments
 * comments
 */

#include <foo.h>
#include <foo.h>
#include <foo.h>

#define foo() \
   do {              \
      static int a;  \
   } while (0)
```
The `static int a; \` is on L32. When opening this file, shiftwidth will be set to 6.

**Comment by sheerun** [comment]
I assumed nobody would use 3-spaces indentation but I guess I was wrong. I've fixed vim-polyglot so it should respect your settings for c and cpp files in .vimrc, but also it should properly detect indentation so theoretically you can remove it from your augroup from vimrc and everything should work

**Comment by zedtang** [comment]
Thx for the fast fix! I think I get what it's trying to do now.
