### ISSUE TITLE
Error while opening yaml file

### ISSUE THREAD

**Issue by andrewpavlenko** [sheerun/vim-polyglot#542]
**Does this bug happen when you install plugin without vim-polyglot?**
No
**Describe the bug:**
When I opening yaml file using neovim with polyglot installed I getting the next error:
```
Error detected while processing /home/andrei/.local/share/nvim/plugged/vim-polyglot/ftplugin/yaml.vim
line 22:
E15: Invalid expression ..= " sw< sts<"
E488: Trailing characters
```
**To Reproduce:**
Run `nvim some-file.yml`

Also my neovim version is 0.3.4

**Comment by sheerun** [comment]
it seems you're using old version of neovim

**Comment by sheerun** [comment]
it whould work now even for old neovim, can you check?

**Comment by andrewpavlenko** [comment]
Yes, error no longer appears. Thanks @sheerun
