### ISSUE TITLE
JSX indentation breaks

### ISSUE THREAD

**Issue by asermax** [sheerun/vim-polyglot#543]
**Does this bug happen when you install plugin without vim-polyglot?**
No

**Describe the bug:**
Indentation works correctly for the first JSX file opened, but on any file opened subsequently the indentation stops working as expected: any time you start a newline it gets indented back to the root element level. 
This happens specifically within the JSX blocks of the file (indentation seems to work correctly in other blocks like javascript or styled components) and on any new *file* opened after the first one (even if opened within the same buffer).

Here's a gif with the reproduction of the issue using a config with only `vim-polyglot` activated:
![vim-polyglot-jsx-issue](https://user-images.githubusercontent.com/1452164/92659906-ad6d6080-f2cf-11ea-938e-911c235d4b52.gif)

This seems to have started happening with version v4.6.0

**To Reproduce:**
- Open a JSX file and work within the JSX portion of it; indentation works as expected.
- Open a second JSX file and work within the JSX portion of it; indentation stops working as expected and always indent to the lowest element level.

**Comment by sheerun** [comment]
should work now, thanks for reporting

**Comment by asermax** [comment]
Works great now, thanks for the quick reply!
