### ISSUE TITLE
Option to enable C++ enhanced syntax

### ISSUE THREAD

**Issue by p1131** [sheerun/vim-polyglot#545]
Enhanced C++ syntax was removed due to being slow, however I hadn't noticed any slow down in my computer and I liked the highlighting of often-used words. It would be nice if we had the option to enable it instead of removing it altogether. Currently I have created a brach from a previous commit, but I'll basically have to maintain it (resolving merge conflicts etc.) in order to keep up with future updates. Would it be possible to implement such functionality?

**Comment by sheerun** [comment]
you can just install it separately

**Comment by AndysonDK** [comment]
Okay, but how do I do that then?

**Comment by sheerun** [comment]
It depends what package manager you're using. If you use vim-plug, then put `Plug 'octol/vim-cpp-enhanced-highlight'` in your .vimrc.

**Comment by AndysonDK** [comment]
Seems Syntax support for c/c++ is back in version v4.13.0 nice!
