### ISSUE TITLE
Dealing with "g:polyglot_disabled should be at the top of .vimrc" warning

### ISSUE THREAD

**Issue by echasnovski** [sheerun/vim-polyglot#546]
**Does this bug happen when you install plugin without vim-polyglot?**
This is directly related to 'vim-polyglot'.

**Describe the bug:**
I have just updated my plugins and noticed "g:polyglot_disabled should be at the top of .vimrc" warning at the startup (which was introduced in the 46affb6). I roughly have the following Neovim setup:

```
" Source all plugins with Vim-plug
source $HOME/.config/nvim/vim-plug/plugins.vim
" Load several files with general settings
" Load files with plugin related settings, among which there is a file for 'vim-polyglot'
source $HOME/.config/nvim/plug-config/vim-polyglot.vim
```

I define `g:polyglot_disabled` in second file. As output of `:scriptnames` shows, 'ftdetect/polyglot.vim' is sourced before my file with settings, so warning is shown at startup.

So there are two questions:

- What is the reasoning behind including this warning? I didn't find any documentation about it.
- What is your recommended way of suppressing this warning? I can define `g:polyglot_disabled` inside 'init.vim' or any other file sourced before 'ftdetect/polyglot.vim', but I really don't want to.

Thanks.

**To Reproduce:**
Setup 'init.vim' in Neovim with:

```
source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/plug-config/vim-polyglot.vim
```

Where 'vim-plug/plugins.vim' loads 'vim-polyglot' using vim-plug and 'plug-config/vim-polyglot.vim' has `g:polyglot_disabled` defined.

**Comment by sheerun** [comment]
defining `g:polyglot_disabled` after polyglot is loaded has no effect at all so you might as well remove it from config

**Comment by sheerun** [comment]
also often configuration for plugins needs to be defined before they are loaded, so it would be best if you reversed the order:

```
source $HOME/.config/nvim/plug-config/vim-polyglot.vim
source $HOME/.config/nvim/vim-plug/plugins.vim
```

that's true not only for vim-polyglot but other plugins as well

**Comment by echasnovski** [comment]
OK, thank you. As I understand, this is definitely an intended feature forcing users to include this setting before polyglot is loaded.

My "problem" here is that, as far as I can tell, it seems to work the same in both cases: when put directly as first line of 'init.vim' and inside separate file. In particular, I have `let g:polyglot_disabled = ["csv"]` in favor of 'rainbow_csv'. In both cases the effect is the same:

- 'vim-polyglot/autoload/csv.vim' is not loaded. But without disabling, it is loaded.
- 'vim-polyglot/ftplugin/csv.vim' and 'vim-polyglot/syntax/csv.vim' are loaded.

And on top of that, user experience seems to be the same.

**Comment by sheerun** [comment]
the warning doesn't depend on whether `g:polyglot_disabled` is in separate file or not. it is shown if `g:polyglot_disabled` is modified after vim-polyglot used this variable while loading. in your case it happens to work because you don't mind ftdetect scripts behave differently. for example even you have `let g:polyglot_disabled = ["csv"]` defined, foo.tsv is recognized as `csv` filetype which is configured by vim-polyglot. it would not be configured if `let g:polyglot_disabled = ["csv"]` was defined before vim-polyglot is loaded.

**Comment by echasnovski** [comment]
Got it. So if no warning is displayed and I do have `g:polyglot_disabled` defined somewhere, I can be sure that it is used properly, right?

Maybe changing warning to something like `"vim-polyglot: g:polyglot_disabled should be defined before loading vim-polyglot"` will decrease possible confusion of what is actually going on here?

For other people with the same issue: in my case moving its definition just before `Plug 'sheerun/vim-polyglot'` line also removed the warning.

**Comment by sheerun** [comment]
That's true, I've changed it
