### ISSUE TITLE
eRuby files incorrectly indentified as Mason

### ISSUE THREAD

**Issue by goronfreeman** [sheerun/vim-polyglot#547]
From `v4.9.9`+, all eRuby files are now being identified as Mason files. Disabling polyglot and installing the latest version of the vim-ruby plugin does not exhibit this behavior.

**To Reproduce:**
1. Install polyglot `v4.9.9`+
2. Open any file with the extension `.erb`

**Comment by sheerun** [comment]
there's no mason in vim-polyglot

**Comment by sheerun** [comment]
if you mean meson, then vim-polyglot doesn't associate it with .etc, here's the code:

```vim
if !has_key(s:disabled_packages, 'meson')
  au BufNewFile,BufRead meson.build setf meson
  au BufNewFile,BufRead meson_options.txt setf meson
  au BufNewFile,BufRead *.wrap setf dosini
endif

```

**Comment by goronfreeman** [comment]
I actually did mean mason, not meson. Here is the result of running `:set filetype?` without polyglot:

<img width="796" alt="Screen Shot 2020-09-12 at 12 49 21 AM" src="https://user-images.githubusercontent.com/5210483/92988568-42b85280-f492-11ea-9f6a-8479e1f41a5d.png">

Here is the same file after enabling polyglot:

<img width="796" alt="Screen Shot 2020-09-12 at 12 50 00 AM" src="https://user-images.githubusercontent.com/5210483/92988570-4b108d80-f492-11ea-8992-c7a4f15f5a4f.png">

This issue appeared in `4.9.9`, as rolling back to `4.8.8` fixes the issue.

**Comment by goronfreeman** [comment]
I did also notice that it's not all files this happens with. The screenshot above is for a file named `index.html.erb`. Another file with the name `show.html.erb` seemed to work as expected.

**Comment by sheerun** [comment]
what happens if you disable all other plugins than polyglot?

**Comment by goronfreeman** [comment]
That's what I did for the screenshots above. Here is my `init.vim` I'm using to try to help debug this:

```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'sheerun/vim-polyglot'
call plug#end()
```

This is using the latest stable neovim release v0.4.4 and vim plug.

After digging into this a little more, I think I found the issue. It seems that if a file with the extension `.html.erb` does not contain any HTML and only ERB, this is when this happens. For instance, here is one of the files that is identified incorrectly:

```erb
<%= render partial: 'shared/games', locals: { games: @games, ajax: false, pagy: @pagy, show_links: true, view: :list } %>
```

Here is one that is identified correctly:

```erb
<div class="container">
  <div class="card">
    <div class="card-image has-background-grey-light video-responsive">
      <iframe width="560"
              height="315"
              src="<%= @game.trailer %>"
              title="<%= @game.title %> Trailer"
              frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen></iframe>
    </div>

    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <figure class="image is-96x96">
            <%= image_tag @game.front_box_art, alt: @game.title %>
          </figure>
        </div>

        <%= render partial: 'price_info', locals: { game: @game } %>
      </div>

      <div class="content">
        <% if @game.on_sale? %>
          <%= render partial: 'countdown', locals: { game: @game } %>
        <% end %>

        <div class="button-container">
          <%= render partial: 'shared/button', locals: { game: @game } %>
          <%= link_to 'Buy Digital', @game.purchase_link, target: '_blank', class: 'button is-link' %>
          <%= link_to 'Game Info', @game.url, target: '_blank', class: 'button is-link' %>
        </div>
        <br>

        <%= render partial: 'footer', locals: { game: @game } %>
      </div>
    </div>
  </div>
</div>
```

I confirmed this opening other `.html.erb` templates that only render partials, and they all exhibit the same behavior. I also tested this same thing installing the `vim-ruby` plugin directly using vim-plug, and it works fine with every file. This seems strange, since as far as I could tell, that's what polyglot uses for Ruby.

Let me know if I can provide any more information to help with this issue.

**Comment by sheerun** [comment]
Thank you it was very helpful. It seems vim native ftdetect scripts are hard-setting filetype: https://github.com/vim/vim/blob/master/runtime/scripts.vim#L210-L211 (they use `set ft=` instead of `setf`). Because vim-polyglot uses `setf` it doesn't override what `set ft=` set. vim-ruby doesn't have this issue because it uses `let &filetype = a:filetype` which is essentially the same as `set ft=`. While it seems like a bug on vim side, I need to fix it on vim-polyglot side because we can't control what version of vim user has installed. 

The ultimate solution is to disable all filetypedetection on vim side and make vim use only vim-polyglot defined ftdetect, but I cannot do it until I migrate all filetypes from vim. For now a hack will suffice, similar to what vim-ruby does.
