### ISSUE TITLE
Missing tmp dir breaks the build

### ISSUE THREAD

**Issue by sstutz** [sheerun/vim-polyglot#548]
(I am not a ruby dev)

https://github.com/sheerun/vim-polyglot/blob/c842cbcb59ba734d803dfe149ae6246d9056539d/scripts/build#L143

the missing tmp directory seems to break the build and throws this error:
scripts/build:143:in `write': No such file or directory @ rb_sysopen - tmp/languages.yml (Errno::ENOENT)
 
so locally I've just added the following line above the File.write() to fix it
`Dir.mkdir('tmp') unless File.exists?('tmp')`

**Comment by sheerun** [comment]
should be fixed, thank you for reporting
