### ISSUE TITLE
Are there any plans on supporting C/C++ syntax highlighting again in the future?

### ISSUE THREAD

**Issue by kostiskalkounos** [sheerun/vim-polyglot#549]
Title

**Comment by sheerun** [comment]
It would need to be more lightweight, enhanced c++ syntax loaded in 300ms on my computer

**Comment by bluz71** [comment]
@kostiskalkounos,

Slightly out-of-project scope, but I have been toying with Neovim's upcoming [Treesitter](https://github.com/nvim-treesitter/nvim-treesitter) integration, and the C++ highlighting is very good. Noting that it will be true language-aware semantic highlighting, not dumb regex based highlighting.

Not ready now, lots of issues, but it will be worth it once it matures. This is the true solution to your issue.

Same goes for Java which has currently also has awful highlighting as well (not the fault of vim-polyglot).

Best regards.

P.S. I have no affiliation with the project, just an interested observer.

**Comment by sheerun** [comment]
It would be interesting to integrate treesitter with vim-polyglot as well (as post-loading syntax highlighting enhancement)

**Comment by AndysonDK** [comment]
Writing here again just so the author gets notified: Seems Syntax support for c/c++ is back in version v4.13.0 nice!

**Comment by kostiskalkounos** [comment]
Yes indeed! I never uninstalled the plugin and I saw it in the commits. I like this version even more!
