### ISSUE TITLE
Error in the php syntax file

### ISSUE THREAD

**Issue by Yavor-Ivanov** [sheerun/vim-polyglot#55]
There seems to be an error in the php syntax file. I've tried updating the plugin; to no avail.
Here's an excerpt of the error I get whenever I open a php file:

```
Error detected while processing /home/ppm/.vim/bundle/vim-polyglot/syntax/php.vim:
line  196:
E714: List required
line  200:
E714: List required
line  204:
E714: List required
line  208:
E714: List required
line  212:
E714: List required
line  216:
E714: List required
line  220:
E714: List required
line  224:
E714: List required
line  228:
E714: List required
...
```

At the moment I've renamed the offending syntax file, and use ```StanAngeloff/php.vim``` in it's place, as a temporary workaround.

**Comment by sheerun** [comment]
vim-polyglot actually uses `StanAngeloff/php.vim`. I don't know how to fix it :)

**Comment by Yavor-Ivanov** [comment]
Okay, now I'm scared.

**Comment by Yavor-Ivanov** [comment]
The syntax files are identical, but renaming the one used by polyglot (as a means of disabling it) and loading ```StanAngeloff/php.vim``` after polyglot magically makes everything work.

**Comment by sheerun** [comment]
Could you send .php file that reproduces this issue? What's your vim
version?

**Comment by Yavor-Ivanov** [comment]
I've reinstalled vim and now the problem only appears when I run ```vim somefile.php``` directly. If I run vim first, then open the same file with ```:e somefile.php``` everything works as expected.

**Comment by sheerun** [comment]
You probably need to provide a way to reproduce, or a fix.. I don't know what's wrong.

Maybe send offending file.

**Comment by Yavor-Ivanov** [comment]
I fixed it by accident when reordering my plugin load order. I would provide the fix for posterity, but then I have no idea which plugin was clashing with it. I guess you can close this.
