### ISSUE TITLE
Perl files are recognized as Raku

### ISSUE THREAD

**Issue by ferki** [sheerun/vim-polyglot#550]
**Does this bug happen when you install plugin without vim-polyglot?**

As far as I can tell, no.

**Describe the bug:**

It looks pretty much like #524 reappearing. Some Perl files, like `*.pm`, `*.pl`, and `*.t`, are recognized as Raku instead of Perl since v4.10.1 of vim-polyglot, while v4.10.0 works as expected. There might be other extensions affected.

**To Reproduce:**

Open a `*.pm`, `*.pl`, or `*.t` file that contains Perl code.

**Comment by sheerun** [comment]
Yeah, this and https://github.com/sheerun/vim-polyglot/issues/547 are hard to fix at the same time... On one hand I need to override what vim sets in some case and on the other hand I need to respect what it sets in others...

I guess the solution is to just write proper heuristics for perl in vim-polyglot

**Comment by ferki** [comment]
I can confirm correctness of v4.10.2 in this regard based on first few tries :+1: Thank you very much for the quick fix! :tada:
