### ISSUE TITLE
Nim raw string syntax

### ISSUE THREAD

**Issue by nu8** [sheerun/vim-polyglot#554]
This is a valid Nim program:

~~~nim
let s = r"May\"
echo s
~~~

https://nim-lang.org/docs/manual.html#lexical-analysis-raw-string-literals

However using this:

https://github.com/sheerun/vim-polyglot/blob/master/syntax/nim.vim

The highlighting treats the string as if it is not terminated.

**Comment by nu8** [comment]
As a workaround, I have gone back to using the syntax I created:

~~~vim
syn keyword Boolean true false
syn keyword Keyword break echo let var items
syn keyword Statement elif else for if import in
syn match Number /\<\d\d*/
syn region Comment start=/# / end=/$/
" single must be first
syn region String start=/"/ end=/"/
syn region String start=/"""/ end=/"""/
~~~

**Comment by sheerun** [comment]
Hello and thank you. You need to contribute this to plugin we use, or suggest new one (that will be maintained)

https://github.com/zah/nim.vim

**Comment by nu8** [comment]
the version here is newer than the version you linked...

**Comment by sheerun** [comment]
It seems exactly the same:

```
diff <(curl -s https://raw.githubusercontent.com/zah/nim.vim/master/syntax/nim.vim) <(curl -s https://raw.githubusercontent.com/sheerun/vim-polyglot/master/syntax/nim.vim)
0a1,2
> if !exists('g:polyglot_disabled') || index(g:polyglot_disabled, 'nim') == -1
>
204a207,208
>
> endif
```

**Comment by nu8** [comment]
https://github.com/zah/nim.vim/issues/101
