### ISSUE TITLE
Valid arguments for g:polyglot_disabled

### ISSUE THREAD

**Issue by nomasprime** [sheerun/vim-polyglot#555]
From the readme:

```
let g:polyglot_disabled = ['css']
```

But there's no CSS language pack listed and doesn't look like arguments are validated so could be failing silently.

How can I get a complete list of args for `g:polyglot_disabled`, is it a case of scanning through `ft…` folders?

**Comment by sheerun** [comment]
they are listed in the readme. the example is bug, I can change it

**Comment by nomasprime** [comment]
Ah OK, thanks.
