### ISSUE TITLE
Integrating with Treesitter

### ISSUE THREAD

**Issue by nomasprime** [sheerun/vim-polyglot#556]
I'm currently using Polyglot and recently discovered [Treesitter](https://github.com/nvim-treesitter/nvim-treesitter).

Trying to figure out a few things:

1. What does Polyglot offer that Treesitter doesn't?
2. What does Treesitter offer that Polyglot doesn't?
3. Can they be integrated with existing configuration options or would Polyglot need to be modified to work with Treesitter?

**Comment by sheerun** [comment]
Treesitter is more advanced, supports less languages, supports just neovim, requres server (more memory), and compiler while installing. Possibly slower, but more accurate. I guess it's up to vim/vim to implement this, not vim-polyglot.

**Comment by nomasprime** [comment]
The only thing I can think to do is disable packs in Polyglot. However, it looks like the main downside of this is loss of good ftdetect, unelss you can think of anything else?

I'm guessing the rest of a pack can't be disabled independently of ftdetect?

**Comment by nomasprime** [comment]
Seems to work OK if both are enabled at the same time. Don't know either project well but I'm guessing this introduces some unnecessary overhead because of the duplication.

Think next step would be to try forking Polyglot and adding extra flags so I can toggle features independently.

**Comment by sheerun** [comment]
most languages are duplicated as vim-native syntaxes anyway. the overhead shoudn't be great

**Comment by sheerun** [comment]
I've added feature that allows to leave only filetype detection and disables filetype-related features like syntax highlighting. I hope this resolves this issue (i.e. you can use treesitter along vim-polyglot).

**Comment by nomasprime** [comment]
Thanks a lot @sheerun.

Does this change only disable syntax or other settings like compiler and indent too? Ideally would retain as much of the other settings from Polyglot as possible.

**Comment by sheerun** [comment]
what settings treesitter is configuring? only syntax and indent? also compiler?

**Comment by akinsho** [comment]
@sheerun it's basically only syntax and indent, not compiler or any others. I guess `foldtext` can be set by the user but that doesn't affect this plugin I think.

What would be the easiest way to turn of syntax and indent for all the languages treesitter supports but leave everything else alone? I know about using `g:polyglot_disabled = ['indent', 'syntax']` but that means for all files. Would it be something like `g:polyglot_disabled = ['supported_ftype.syntax', 'supported_ftype.indent']` and so on and so forth for all the languages treesitter covers?

**Comment by sheerun** [comment]
I've decided to not implement this function (i.e. disabling sub-features), because it adds too much complexity. Set of plugins by vim-polyglot should serve as initial syntax highlighting engine, before LSP is fully loaded
