### ISSUE TITLE
No syntax highlighting

### ISSUE THREAD

**Issue by mihneagogu** [sheerun/vim-polyglot#557]
Hello, I had vim polyglot on my desktop, installed 4 months ago working perfectly. Now I have downloaded vim and installed a bunch of plugins on my laptop, including polyglot but there is no syntax highlighting. 

My vimrc (identical to the one on my desktop):
----------------------------------------------------------------------------------

" Terminal build: Tilda terminal emulator
" Tilda color pallete: base16:
" Link: https://github.com/Gwyki/base16-tilda
syntax on
filetype plugin indent on

set hidden
set noerrorbells visualbell t_vb=

" No ringing
if has('autocmd')
  autocmd GUIEnter * set visualbell t_vb=
endif

if has('nvim')
    set nohlsearch!
endif

set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set rnu
set nu
set nowrap
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
"
" Give more space for displaying messages.
set cmdheight=2

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=50

" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

set colorcolumn=80
highlight ColorColumn ctermbg=0 guibg=lightgrey

call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline-themes'
Plug 'tomasiser/vim-code-dark'
Plug 'vimoxide/vim-cinnabar'
Plug 'bignimbus/pop-punk.vim'
Plug 'neoclide/coc.nvim', { 'branch' : 'release' }
Plug 'alx741/vim-rustfmt'
Plug 'dense-analysis/ale'
Plug 'rust-lang/rust.vim'
"Plug 'jaspervdj/stylish-haskell'
Plug 'chrisdone/hindent'
Plug 'urso/haskell_syntax.vim'
"Plug 'neovimhaskell/haskell-vim'
" For the low bar
Plug 'vim-airline/vim-airline'
" Repo with a shit ton of colorschemes
" Link : https://github.com/rafi/awesome-vim-colorschemes
Plug 'rafi/awesome-vim-colorschemes'
Plug 'artanikin/vim-synthwave84'
" Monokai theme
Plug 'sickill/vim-monokai'
" Palenight theme
Plug 'drewtempelmeyer/palenight.vim'

Plug 'sheerun/vim-polyglot'
"Plug 'Valloric/YouCompleteMe'
Plug 'jremmen/vim-ripgrep'
Plug 'tpope/vim-fugitive'
Plug 'leafgarland/typescript-vim'
Plug 'vim-utils/vim-man'
Plug 'lyuts/vim-rtags'
Plug 'mbbill/undotree'
Plug 'scrooloose/nerdtree'
call plug#end() 

colorscheme Atelier_DuneDark
syntax on
set background=dark

if (has("nvim"))
  "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif

"For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
"Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
" < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
if (has("termguicolors"))
  set termguicolors
endif

"let g:haskell_enable_quantification = 1   
"let g:haskell_enable_recursivedo = 1      
"let g:haskell_enable_arrowsyntax = 1      
"let g:haskell_enable_pattern_synonyms = 1 
"let g:haskell_enable_typeroles = 1        
"let g:haskell_enable_static_pointers = 1  
"let g:haskell_backpack = 1                

let g:termguicolors=256
let mapleader = " "
let g:rustfmt_on_save = 0

let g:netrw_browse_split = 2
let g:netrw_banner = 0
let g:netrw_winsize = 25

let g:ctrlp_use_caching = 0
 

nnoremap <Space><Space> <ESC>/<++><Enter>"_c4l

" Enter to add new line, brackets to look for brackets
map <Enter> o<ESC>
nnoremap  <leader>{ /{<ESC>
nnoremap  <leader>} /}<ESC>

nnoremap <leader>[ /[<ESC>
nnoremap <leader>] /]<ESC>
nnoremap <leader>( /(<ESC>
nnoremap <leader>) /)<ESC>

" Open new window on right and then open a NERDTree window
nnoremap <leader>vs :vsplit<ESC>:wincmd l<CR>:NERDTree<CR>

nnoremap <leader>j :wincmd j<CR>
nnoremap <leader>k :wincmd k<CR>
nnoremap <leader>h :wincmd h<CR>
nnoremap <leader>l :wincmd l<CR>
nnoremap <leader>u :UndotreeShow<CR>
nnoremap <leader>al :ALEToggle<CR>
nnoremap <leader>nd :NERDTree<CR>
nnoremap <leader>pv :wincmd v<bar> :Ex <bar> :vertical resize 30<CR>
nnoremap <Leader>ps :Rg<SPACE>
nnoremap <silent> <Leader>+ :vertical resize +5<CR>
nnoremap <silent> <Leader>- :vertical resize -5<CR>
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv
vnoremap <C-p> "+p<CR>
 

function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
endfunction

fun! RsPrintln()
    nnoremap <buffer> <leader>p iprintln!("{}", );<ESC>
endfun

fun! RustFmt()
    nnoremap <leader>rs :Rustfmt<ESC>
endfun

fun! TSCompile()
    nnoremap <leader>ts :!tsc<ESC>
endfun

fun! GoCoc()
    inoremap <buffer> <silent><expr> <TAB>
                \ pumvisible() ? "\<C-n>" :
                \ <SID>check_back_space() ? "\<TAB>" :
                \ coc#refresh()

    inoremap <buffer> <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
    inoremap <buffer> <silent><expr> <C-space> coc#refresh()

    " GoTo code navigation.
    nmap <buffer> <leader>gd <Plug>(coc-definition)
    nmap <buffer> <leader>gy <Plug>(coc-type-definition)
    nmap <buffer> <leader>gi <Plug>(coc-implementation)
    nmap <buffer> <leader>gr <Plug>(coc-references)
    nnoremap <buffer> <leader>cr :CocRestart
endfun

" autocmd FileType cpp,cxx,h,hpp,c :colorscheme gruvbox
autocmd FileType cpp,cxx,h,hpp,c :call GoCoc()

autocmd FileType javascript,typescript :syntax on
autocmd FileType javascript,typescript :call GoCoc()

autocmd FileType typescript,javascript,html :colorscheme pop-punk 
autocmd FileType typescript :call TSCompile()

autocmd FileType vimscript :colorscheme Atelier_DuneDark

autocmd FileType rust :call GoCoc()
autocmd FileType rust :call RsPrintln()
autocmd FileType rust :call RustFmt()

autocmd FileType haskell :syntax on
autocmd FileType haskell :colorscheme molokai

" Making automated <tag></tag>s for html documents
autocmd FileType javascript,typescript,html inoremap ;b <b></b><Enter><++><Esc>kf/hi
autocmd FileType javascript,typescript,html inoremap ;p <p></p><Enter><++><Esc>kf/hi
autocmd FileType javascript,typescript,html inoremap ;h1 <h1></h1><Enter><++><Esc>kf/hi
autocmd FileType javascript,typescript,html inoremap ;h2 <h2></h2><Enter><++><Esc>kf/hi

----------------------------------------------------------------------------------

Was wondering if polyglot was the problem, so i deleted plugged/vim-polyglot on my desktop, then reopened vim, called PlugInstall, quit vim, opened it again, and there was no highlighting, even on my desktop. I tried the alt version as well, cloning the repository itself. It's really weird, since I've had no problems at all with other plugins, and polyglot used to work on my desktop, but after reinstalling it today via plugged it doesn't work anymore (neither does cloning it). Since today's version (23 Sept 2020) doesn't work on either my laptop or desktop (on which it used to work) I am tempted to think that maybe there's a bug in today's live version? Need help please, I love polyglot I legit can't stand vim without it

**Comment by sheerun** [comment]
I tried your .vimrc and highlighting works for me for some simple Rust file

**Comment by sheerun** [comment]
Maybe try to update vim. If it still doesn't work, please prepare docker image that reproduces this issue

**Comment by mihneagogu** [comment]
> Maybe try to update vim. If it still doesn't work, please prepare docker image that reproduces this issue

Vim version for desktop is 8.1 and on laptop is the latest, I built from source today from vim’s git. I’ll try to plug it with vundle and see if that works

**Comment by sheerun** [comment]
vim-plug works with me

**Comment by mihneagogu** [comment]
So, this is what was happening. Polyglot mostly works fine actually, I just thought it didn't because I had only opened .c files (and .h files). It definitely didn't work for C source files and header files, however it did work on Rust files and javascript files. Very odd, so it's not that the plugin didn't work or had some trouble with the plugin manager, there's something going on with C files. Just to make things clear, I pulled an older release version (4.4.1) from May 2020 and threw it in my ~/.vim/plugged and now highlighting works for C files as well. I believe there might a be bug with them, please check it out. Try it on an empty VM with freshly installed linux (I used ubuntu 18.04.5 with latest vim version) and install polyglot, you might be able to see if there's a problem with the C files. This is very odd and unexpected

**Comment by sheerun** [comment]
.c and .h highlighting works for me as well. maybe you want to install separately octol/vim-cpp-enhanced-highlight which has been removed recently from vim-polyglot because of performance issues

**Comment by sheerun** [comment]
I've added bfrg/vim-cpp-modern to vim-polyglot which is more lightweight than octol/vim-cpp-enhanced-highlight and supports modern c/c++ syntax. by the way what is the output of `set filetype` when you open such files?

**Comment by sheerun** [comment]
Also what is the vim version you're using?

**Comment by mihneagogu** [comment]
> I've added bfrg/vim-cpp-modern to vim-polyglot which is more lightweight than octol/vim-cpp-enhanced-highlight and supports modern c/c++ syntax. by the way what is the output of `:verbose set ft` when you open such files?
It says:
![Screenshot from 2020-09-24 09-21-53](https://user-images.githubusercontent.com/28712673/94108132-6d69ba00-fe47-11ea-913d-35f883c61b8d.png)
On desktop 8.1.2269 (preinstalled by ubuntu 20.04 and possibly updated, I can't remember) and on laptop the commit version of 24 Sept 2020 (built from source), both have --with-features=huge tags

**Comment by mihneagogu** [comment]
I've just pulled again from the current version of polyglot via plugged, and highlighting does work for C files now, I suppose you've fixed it. Thanks a lot for being so responsive and dedicated. You can close this pull request if you ask me, there are no further problems

**Comment by sheerun** [comment]
glad to hear that :)
