### ISSUE TITLE
How do I disable defined CSS colors being highlighted with their respective colors?

### ISSUE THREAD

**Issue by winahey483** [sheerun/vim-polyglot#561]
I've noticed defined CSS colors are being highlighted with their respective colors but cannot seem to find the plugin causing this.
How do I disable this behaviour and what's causing it?
![csscolors](https://user-images.githubusercontent.com/71844642/94181219-ca955800-fea7-11ea-91da-758422512c05.png)

**Comment by sheerun** [comment]
It's not something that vim-polyglot does

**Comment by winahey483** [comment]
Could you have an idea of what's happening? You have extensive experience in the syntax files field...
Is vim doing this?
I don't have any other syntax files apart from vim-polyglot.

**Comment by sheerun** [comment]
probably you're using some other plugin than vim-polyglot, try following vimrc:

```
call plug#begin()

Plug 'sheerun/vim-polyglot'

call plug#end()
```

**Comment by winahey483** [comment]
Thanks for the reply.
I've found the issue.
It's with [coc.nvim](https://github.com/neoclide/coc.nvim)
Apparently it somehow loads this extension [coc-highlight](https://github.com/neoclide/coc-highlight) that does the highlighting.
**For future people**
To disable it, place this entry in coc-settings.json
```
"coc.preferences.colorSupport": false
```
