### ISSUE TITLE
Syntax highlighting for .gitignore files

### ISSUE THREAD

**Issue by winahey483** [sheerun/vim-polyglot#562]
My .gitignore files don't seem to have any syntax highlighting. 
Is there a fix for this?

**Comment by sheerun** [comment]
I've added support for it just now, with https://github.com/rdolgushin/gitignore.vim

**Comment by winahey483** [comment]
Thanks

**Comment by winahey483** [comment]
Could you switch to this [maintained fork](https://github.com/gisphm/vim-gitignore)?
The other one was archive way back

**Comment by sheerun** [comment]
I've reviewed fork you're linking and it doesn't seem much better, it doesn't even highlight globs, just defines directories as constants and files as types... don't know why

**Comment by sheerun** [comment]
I've switched to https://github.com/fszymanski/fzf-gitignore which should be nicer

**Comment by winahey483** [comment]
Oh! Yeah...
Thats' way better
