### ISSUE TITLE
Error when processing ftdetect

### ISSUE THREAD

**Issue by eturkes** [sheerun/vim-polyglot#563]
Thank you for this very helpful plugin. Here is the issue I am facing:

**Does this bug happen when you install plugin without vim-polyglot?**

No, this bug only happens when vim-polyglot is installed. I am using the dein plugin manager and all plugins are up-to-date.

**Describe the bug:**

When opening any file with neovim (v0.4.3) I get the following error:

```
Error detected while processing /home/eturkes/.cache/dein/.cache/init.vim/.dein/ftdetect/ftdetect.vim:
line   18:
E746: Function name does not match script file name: polyglot#Observe
Press ENTER or type command to continue
```

**To Reproduce:**

Open any file in neovim with vim-polyglot installed. Removing vim-polyglot using dein (comment out `call dein#add('sheerun/vim-polyglot')` followed by `:call dein#check_clean()` and `:call dein#recache_runtimepath()`), fixes the issue. Reinstalling vim-polyglot (uncomment line and run `:call dein#install()`) restores the issue.

**Comment by sheerun** [comment]
I think it should be ok now

**Comment by eturkes** [comment]
It is, thank you very much :)
