### ISSUE TITLE
autoindent settings applied globally (instead of using `setlocal`)

### ISSUE THREAD

**Issue by infokiller** [sheerun/vim-polyglot#564]
**Describe the bug:**

It seems that the autoindent settings are applied "globally", instead of using `setlocal`, for example:

https://github.com/sheerun/vim-polyglot/blob/33b86476b63f7fc2286336eb488a149a85cb08cb/autoload/polyglot.vim#L612

https://github.com/sheerun/vim-polyglot/blob/33b86476b63f7fc2286336eb488a149a85cb08cb/autoload/polyglot.vim#L599

Why does it not set these options locally?

Also, why is there code duplicated between https://github.com/sheerun/vim-polyglot/blob/master/autoload/polyglot.vim and https://github.com/sheerun/vim-polyglot/blob/master/polyglot.vim?

**To Reproduce:**

- Open some file with indentation that will be detected by autoindent
- Open another file with different indentation
- The new file has the same indentation settings as set for the first file

**Comment by sheerun** [comment]
polyglot.vim is source file, autoload/polyglot.vim is generated file. Thank you for noticing, I'll fix it
