### ISSUE TITLE
v4.10.0 seems to break some plugin's autocmd

### ISSUE THREAD

**Issue by ZSaberLv0** [sheerun/vim-polyglot#566]
**Does this bug happen when you install plugin without vim-polyglot?**
no

**Describe the bug:**
see below

**To Reproduce:**

minimal vim config:
```
filetype plugin on
syntax on
set nocompatible
let g:plug_home = $HOME . '/.vim/bundle'
let g:plug_url_format = 'https://github.com/%s'
execute 'source ' . g:plug_home . '/vim-plug/plug.vim'
silent! call plug#begin()
Plug 'junegunn/vim-plug'
Plug 'cohama/agit.vim'
Plug 'sheerun/vim-polyglot'
call plug#end()
```

* the right and expected behavior
1. **do not** install `vim-polyglot`
1. `cd` to some git repo, use `Agit` to see git log, and use `j` or `k` in left panel to navigate git log
1. **expected behavior**: the right panel would update as expected, which was implemented by `CursorMoved` autocmd

* the issue:
1. **do** install `vim-polyglot`
1. `cd` to some git repo, use `Agit` to see git log, and use `j` or `k` in left panel to navigate git log
1. **the issue**: the right panel won't update

**NOTE**: after a bunch of test, `vim-polyglot`'s v4.10.0 seems to cause the issue

**Comment by sheerun** [comment]
Indeed it was broken in 4.10.0 but it seems it was fixes in 4.12.0  :) Please update

**Comment by ZSaberLv0** [comment]
@sheerun 94ec9c38e744241e48fb8d75ae6e8811bc73fc59 seems to reproduce the issue?

**Comment by sheerun** [comment]
This should work now, thanks for reporting
