### ISSUE TITLE
conf files aren't detected correctly

### ISSUE THREAD

**Issue by AoHiyuki** [sheerun/vim-polyglot#569]
After commit 9ff714c some file types aren't detected correctly. In my case those are "*.conf" files and files named "config". They should be in conf type.

**Comment by sheerun** [comment]
thanks for noticing

**Comment by kenken17** [comment]
I found .org file also not detected. Any chance to take a look?

**Comment by sheerun** [comment]
![](https://i.imgur.com/XOBpGNB.gif)

**Comment by sheerun** [comment]
@kenken17 What is the contents of this .org file? Are you sure it should be conf not something like https://github.com/jceb/vim-orgmode ?

**Comment by kenken17** [comment]
My apologies. I thought I can ride on this thread to check the file detect issue for orgmode files. Since the title was named: `Some conf files aren't detected correctly`. Should i create a new issue instead?

**Comment by sheerun** [comment]
yes, please describe what happens and what is expected
