### ISSUE TITLE
Improper install of vim-polyglot. Please add 'packload' to .vimrc but vim-polyglot is not installed as opt package

### ISSUE THREAD

**Issue by ahmedelgabri** [sheerun/vim-polyglot#571]
**Does this bug happen when you install plugin without vim-polyglot?**
No

**Describe the bug:**
I'm using https://github.com/k-takata/minpac to install packages & I'm installing `vim-polyglot` as a `start` package that will get loaded automatically when neovim starts not as an `opt` one. So I shouldn't get this message.

**To Reproduce:**
- `git clone --depth 1 https://github.com/sheerun/vim-polyglot ~/.vim/pack/plugins/start/sheerun/vim-polyglot`
- open neovim

**Comment by sheerun** [comment]
The message is correct. Vim-polyglot requires that its filetype.vim is loaded before vim's (you can verify it's not the case with `--startuptime vim.log`. Putting any of `packadd vim-polyglot`, `packload`, or `filetype off` in ~/.vimrc should fix this

**Comment by sheerun** [comment]
This is a quirk that is present only with vim 8 packages: https://github.com/vim/vim/issues/4698

**Comment by sheerun** [comment]
I tried minpac and I don't get this error. Here's mine ~/.vimrc:

```
set nocompatible
packadd minpac
call minpac#init()
call minpac#add('sheerun/vim-polyglot')
```

Maybe you're using old version of minpac?

**Comment by sheerun** [comment]
btw. packload loads start packages, not opt packages :)

**Comment by sheerun** [comment]
Okay, it seems it works on vim, but not on neovim...

**Comment by sheerun** [comment]
I'll need to write patch for minpac, until then you need to use packload at the end of vimrc

**Comment by sheerun** [comment]
to be honest minpac is one big mess when it comes to loading plugins: https://github.com/k-takata/minpac/pull/118

if you want you can use my fork, or continue using packload (remember that it loads packages in alphabetical order, instead of defined order, just like minpac by default)

**Comment by johnstephens** [comment]
Same issue here, and I still see the same error message after adding `packload` at the end of my init.vim file.

**Comment by sheerun** [comment]
packload should be at the beginning, not end of init.vimfile. packload loads starutp files, packadd adds optional files

**Comment by ferki** [comment]
Hmm, if I add `packload` at the top of my `.vimrc` it makes the warning go away, but it also seems to break (some?) other plugins and/or interferes with file recognition (e.g. for `*.xml`, probably others). If I test the behavior commit-by-commit, 449bb882486ee69cc63f812120218ed5c17a1ef7 (v4.13.0) is the first one with the wrong behavior.

Perhaps it's a compound problem, so I'm happy to open another issue - I just struggled with fixing it for a while because of the new message complaining about `packload`, and I found this already open.

**Comment by sheerun** [comment]
could you post output of --startuplog vim.log ?

**Comment by sheerun** [comment]
and ~/.vimrc

**Comment by johnstephens** [comment]
Thanks! Adding `packload` at the beginning of my init.vim didn't get rid of the error message either. I have confirmed that downgrading to v4.12.1 causes the error message to go away.

**Comment by sheerun** [comment]
If you'd like this fixed, please post your `.vimrc` and output of `vim --startuplog vim.log FILE`

**Comment by johnstephens** [comment]
Posting my init.vim feels too intimate for a first date. But if it helps, here goes: [init.vim][1]

[1]: https://gist.github.com/johnstephens/44bfcfb18c36b6018b4236c8e01f8756

The command `nvim --startuplog vim.log FILE` hangs indefinitely, though.

**Comment by ferki** [comment]
Had to add `.txt` extension to make GitHub happy about attaching the files. I also don't seem to have `vim --startuplog`, only `--startuptime` - hope that's good/close enough.

[vimrc.txt](https://github.com/sheerun/vim-polyglot/files/5306723/vimrc.txt)
[vim.log.txt](https://github.com/sheerun/vim-polyglot/files/5306722/vim.log.txt)

I also have this in my `.bashrc`, which I needed for putting all the various vim files into standard XDG directories:

```
export VIMINIT='set runtimepath^=~/.config/vim | let $MYVIMRC="~/.config/vim/vimrc" | source $MYVIMRC'
```

**Comment by ahmedelgabri** [comment]
> to be honest minpac is one big mess when it comes to loading plugins: [k-takata/minpac#118](https://github.com/k-takata/minpac/pull/118)
> 
> if you want you can use my fork, or continue using packload (remember that it loads packages in alphabetical order, instead of defined order, just like minpac by default)

I tried using your fork & I was still getting the warning. But I use minpac slightly different, it's only loaded inside an autoloaded function when I need to install/update/clean plugins. other than that, I let neovim handle the loading of the plugins.

https://github.com/ahmedelgabri/dotfiles/blob/10db893d978aa56d7f503d95caf8d4aaed05a516/roles/vim/files/.vim/autoload/plugins.vim#L10-L12

Adding `packload` works, but I dunno… it feels like a hack to me 🤔

**Comment by sheerun** [comment]
@johnstephens *looks slowly up and down the vimrc* ... nice dotfiles! but seriously something like `nnoremap ; : | nnoremap : ;` should be banned. As for bug I'm unable to reproduce. You can try it yourself by running `docker run --rm -it sheerun/vim:johnstephens nvim foo.m` and seeing that `set ft` return octave (it is sign vim-polyglot was properly loaded)

**Comment by johnstephens** [comment]
@sheerun, thanks! Yeah, it works without error because I reverted to an earlier version of vim-polyglot:
(Line 249) `call minpac#add('sheerun/vim-polyglot', { 'rev': 'v4.12.1' })`

**Comment by johnstephens** [comment]
Sorry, I should have uploaded the error version. 🤦

**Comment by sheerun** [comment]
@ferki Your dotfiles also are nice, but please do yourself a favor and remove `cmap w!! %!sudo tee > /dev/null %`, as it makes `:wq` really unresponsive. something like `cnoremap sudow w !sudo tee % >/dev/null` should work better. As ofo the bug I  also cannot reproduce... you can try this environment yourself with `docker run --rm -it sheerun/vim:ferki` and running `nvim foo.m` and then `:set ft` (filetype is again octave)

**Comment by sheerun** [comment]
@johnstephens `docker run -it sheerun/vim:johnstephens2` has most recent version of vim-polyglot and there is no warning as well

**Comment by ferki** [comment]
> Your dotfiles also are nice, but please do yourself a favor and remove `cmap w!! %!sudo tee > /dev/null %`, as it makes `:wq` really unresponsive. something like `cnoremap sudow w !sudo tee % >/dev/null` should work better.

I might consider it, thanks.

> As ofo the bug I also cannot reproduce... you can try this environment yourself with `docker run --rm -it sheerun/vim:ferki` and running `nvim foo.m` and then `:set ft` (filetype is again octave)

Oh, could it be that because I use `vim` and not `nvim`?

**Comment by sheerun** [comment]
@ahmedelgabri OK, I've reproduced it. vim 8 packages are loading in alphabetical order, and vim-polyglot expects to be the first to be loaded The same happens with your setup @ahmedelgabri (because you are hidding `minpac#add` commands inside function, my fork cannot discover their order, so vim loads all your packages in alphabetical order, instead of the order in which they were defined in.

If I were you I'd consider dropiing vim8 packages and minpac, and just use vim-plug. Much better solution with predictable loads... Maybe you can add flag like `{ "name": "aaaa-vim-polyglot" }` so it is loaded first...

**Comment by sheerun** [comment]
@ferki Solution for you is to put vim-polylot inside `opt` pack directory instead of `start`, and `packadd vim-polyglot` somewhere in ~/.vimrc

@ahmedelgabri solution for you is to use `{'type': 'opt'}` for vim-polyglot and also call  `packadd vim-polyglot` somewhere in ~/.vimrc. This prevents vim-polyglot to be loaded in random alphabetical way.

I'll update warning message to recommend this solution instead (as well as readme)

**Comment by sheerun** [comment]
@ahmedelgabri "The same happens with your setup ..." was addressed at you, I've edited my message

**Comment by sheerun** [comment]
btw. Any reasons you are all using minpac instead of vim-plug?

**Comment by sheerun** [comment]
Also there is a bug in my fork that skips loading after files, so please don't use it

**Comment by ahmedelgabri** [comment]
> btw. Any reasons you are all using minpac instead of vim-plug?

Personally, I didn't see the reason why use a pluging manager that handles `rtp` anymore if vim can do this for me. When I chose `minpac` – you can see from the way I set it up – it's just a way to manage installation, update & clean up of plugins. 

Right now, I'm thinking about trying [`packer.nvim`](https://github.com/wbthomason/packer.nvim) or just go full vanilla with git submodules.

**Comment by jandamm** [comment]
Can't speak for the others but I use the native package loading because it is faster and habt another dependency (vim-plug).

I personally use `vim-packager` but `minpack` is basically the same. They both make it just easier to clone and update a bunch of git repos into a folder and optionally run a command afterwards.

**Comment by sheerun** [comment]
The thing is vim 8 package don't handle rtp or loading order for you if you're not using packadd  or packadd! in .vimrc (and minpac doesn't run it even once, it just leaves all plugins to be loaded in alphabetical order). I think I saw blogpost somewhere where they recommended naming plugins something like 0_something 1_something to ensure loading order..

**Comment by ferki** [comment]
> @ferki Solution for you is to put vim-polylot inside `opt` pack directory instead of `start`, and `packadd vim-polyglot` somewhere in ~/.vimrc

Ok, it's better:
- still shows the warning message, but my other plugins seems to get loaded again
- if I revert d33e6f3da725864271e900907effffb306467bbd, then it recognizes XML again correctly with vim-polyglot in `opt`, nad the `packadd` line in place (which is good, but the file recognition issue sounds like a different topic then)

Thanks for the debugging and help!

> I'll update warning message to recommend this solution instead (as well as readme)

I assume it also means checking for `packadd` in `vimrc`, right? So eventually the warning message will go away if I use `packadd`.

**Comment by ahmedelgabri** [comment]
> The thing is vim 8 package don't handle rtp or loading order for you if you're not using packadd or packadd! in .vimrc (and minpac doesn't run it even once, it just leaves all plugins to be loaded in alphabetical order). I think I saw blogpost somewhere where they recommended naming plugins something like 0_something 1_something to ensure loading order..

This is funny because one of my reasons to use `packages` also that I assumed that it will be more consistent in behavior than plugin managers. I'll try to follow this suggestion to see if this will help.

**Comment by sheerun** [comment]
To give you some preview what I need to deal with I've filled issue on vim that explains it in more detail: https://github.com/vim/vim/issues/7056 

@ferki You'd need to create docker image for reproduction (you can run the one I've provided  stop it, and run `docker commit` + `docker tag` + `docker push`)

packer.vim has practically the same code as minpac, only different UI. Both let plugins load in alphabetical order. With only submodules you again cannot easily control loading order (except using few packages like priority_1_package, priority_2_package etc, priority_3_package etc.). And pure vim 8 modules have other loading issues as described in issue I've linked and for example https://github.com/vim/vim/issues/7051 and https://github.com/vim/vim/issues/4698 So the only thing you gain is harder updates and inconsistent loading order.

I'm not convinced at all vim8 packages are stable and anything created on them is bound to cause issues.

**Comment by ahmedelgabri** [comment]
> packer.vim has practically the same code as minpac, only different UI. Both let plugins load in alphabetical order. With only submodules you again cannot easily control loading order (except using few packages like priority_1_package, priority_2_package etc, priority_3_package etc.). And pure vim 8 modules have other loading issues as described in issue I've linked and for example [vim/vim#7051](https://github.com/vim/vim/issues/7051) and [vim/vim#4698](https://github.com/vim/vim/issues/4698) So the only thing you gain is harder updates and inconsistent loading order.

Thanks for the explanation, but isn't making the loading order depending on how you order your plugins in .vimrc, in general, is also not a good thing? (I understand that for vim-polyglot it might be needed) but I'm talking in general.

**Comment by sheerun** [comment]
Yes I'm going to change that, that warning will go away soon

**Comment by sheerun** [comment]
OK, I've pushed new version that ensures order of loading doesn't matter at all. In worst case you get worse performance because first vim's filetype.vim is loaded, and then polyglot's. If polyglot's ftdetect.vim is loaded first, it prevents vim's from being loaded so we have no double-load time.

Because of this in the future vim-polyglot will actually make vim startup time faster than using vim without any plugins :)

**Comment by johnstephens** [comment]
I can confirm, installing the new version completely resolves the issue as far as I can tell.

**Comment by ahmedelgabri** [comment]
Same here, the issue is resolved. Thanks @sheerun

**Comment by ferki** [comment]
Thanks @sherun, now it works again correctly on my end too, and with the exact same setup I used for years now! :heart:
