### ISSUE TITLE
Error detected while processing BufWritePost Autocommands for "<buffer=X>"

### ISSUE THREAD

**Issue by ravexina** [sheerun/vim-polyglot#573]
**Does this bug happen when you install plugin without vim-polyglot?**
No

**Describe the bug:**
While trying to save a newly created `Html` file, vim saves the file but also gives these errors:

    "test.html" [New] 1L, 15C written
    Error detected while processing BufWritePost Autocommands for "<buffer=1>":
    E492: Not an editor command: ++once call polyglot#detect#Html()

**To Reproduce:**

- Open vim.
- `:e test.html`
- Write something in the buffer.
- `:w`

**Additional data:**
- I just updated `vim-polyglot`.
- I tried disabling all other plugins and I got the same result.
- `VIM - Vi IMproved 8.1`

**Comment by sheerun** [comment]
I don't get this error. Do you get it with vim 8.2?

**Comment by sheerun** [comment]
Hmm I think you're using vim before patch 8.1.1113  at which ++once was introduced, I'll fix this

**Comment by sheerun** [comment]
94ec9c38e744241e48fb8d75ae6e8811bc73fc59 should have fixed this

**Comment by ravexina** [comment]
Thanks for your response.

I'm actually using version `8.1.1401 ` (The default version on Debian Buster's stable repository).

    Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401

After updating `vim-polyglot` I'm still getting the errors. However with vim version `8.1.2269` and patches `1-2269` I don't get any errors.

**Comment by sheerun** [comment]
huh sorry, I've refactored half of the code to be able remove, but not removed `++once`. It should be fixed now

**Comment by bstaint** [comment]
vim version: 8.2.1783.
when save twice, command line will echo current line:
![GIF](https://user-images.githubusercontent.com/5853792/95019298-28d7ed00-0697-11eb-963f-a65ef30d8ca2.gif)

**Comment by sheerun** [comment]
I took different approach which should work, and should work even for Vim with tiny features set

**Comment by bstaint** [comment]
Tks.
