### ISSUE TITLE
Conflict with context.vim

### ISSUE THREAD

**Issue by ipod825** [sheerun/vim-polyglot#575]
Starting from bc97579, `vim-polyglot` conflicts with  [wellle/context.vim](https://github.com/wellle/context.vim), possiblyt due to the newly added file `context.vim`.
https://github.com/sheerun/vim-polyglot/commit/bc9757916ed09763d96283ee62dbed58bd713a11#r43016476

Error message:
```
Error detected while processing BufEnter Autocommands for "*":
E117: Unknown function: context#update
Error detected while processing VimEnter Autocommands for "*":
E117: Unknown function: context#activate
```

**Comment by sheerun** [comment]
weird. vim includes the same file

**Comment by sheerun** [comment]
it seems vim-plug adds plugins to rtp in reverse order they were defined in ~/.vimrc... man I hate package managers for vim

**Comment by ipod825** [comment]
The bug regressed on af3ebda

**Comment by sheerun** [comment]
thank you it's fixed again, I'll add tests so it doesn't happen again. btw. are you updating vim-polyglot every 5 minutes or something? :))
