### ISSUE TITLE
NeoVim man pager cannot handle colours correctly after enabling vim-polyglot

### ISSUE THREAD

**Issue by Frederick888** [sheerun/vim-polyglot#576]
**Does this bug happen when you install plugin without vim-polyglot?**
No.

**Describe the bug:**
With vim-polyglot enabled, nvim manpager cannot handle colours correctly. See screenshot:
<img width="797" alt="Screen Shot 2020-10-07 at 6 17 01 pm" src="https://user-images.githubusercontent.com/4507647/95299920-2d381c00-08ca-11eb-939f-48f7571101bf.png">
And nvim warns that file's been modified when `:q`.

If I open nvim first then `:Man man`, the colours are ok but it somehow still modifies the `[No Name]` buffer and I can see a warning when `:qa`.

**To Reproduce:**

1. Using NeoVim v0.4.4, macOS or Linux
0. `export MANPAGER='nvim +Man!'`
0. Use the `init.vim` below
0. `man man`

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

call plug#begin()
Plug 'sheerun/vim-polyglot'
call plug#end()
```

**Comment by sheerun** [comment]
I can't reproduce colors issue, but I can reproduce warning when trying to exit

**Comment by Frederick888** [comment]
@sheerun After updating vim-polyglot both my issues were fixed. Thank you!

**Comment by vokar** [comment]
@sheerun, I just pulled the last changes and now have the same problem. Looking through the commit history, I found that you returned the man plugin in af3ebda, so that's the reason.

I have NVIM v0.4.4 too.

**Comment by sheerun** [comment]
Man, I was supposed to add only filetypes detection, thank you!

**Comment by vokar** [comment]
No problem. Thank you for the quick reaction and for adding a regression test :smile:
