### ISSUE TITLE
No syntax highlighting for Java

### ISSUE THREAD

**Issue by huyhoang8398** [sheerun/vim-polyglot#577]
**Does this bug happen when you install plugin without vim-polyglot?**

**Describe the bug:**

Error detected while processing /home/huyhoang8398/.vim/plugged/vim-polyglot/syntax/java.vim:
line  159:
E108: No such variable: "b:current_syntax"

`NVIM v0.4.4`

**To Reproduce:**

**Comment by sheerun** [comment]
Thanks, it seems the tests are broken
