### ISSUE TITLE
Files with remind in the name are being set to ft remind

### ISSUE THREAD

**Issue by akinsho** [sheerun/vim-polyglot#579]
**Does this bug happen when you install plugin without vim-polyglot?**
This issue occurs specifically due to a line in this plugin. I don't think the original dart plugin has any logic to set a remind filetype.

**Describe the bug:**
I have a file called `reminders.dart` in a project, the file is a `dart` file. Recently, in the last few days or weeks. Whenever I open this file, it's filetype has been set by polyglot to `remind`

I think this is because of this check [here](https://github.com/sheerun/vim-polyglot/blob/bb3de8fa5e509d5f5faf173fd1a92635a0023274/ftdetect/polyglot.vim#L3992). I think the regex may be too aggressive (not a regex expert, so just guessing)

**To Reproduce:**
* Create a `reminders.dart` file (it might not need to be dart but mine is)
* run `:echo &ft` or `verbose set filetype?`
* output is `ftdetect/polyglot.vim line 113`

__Note__: this file needs to very specifically be called *reminders* if it is called *reminder* that works fine

**Comment by sheerun** [comment]
Thank you for noticing, I've just fixed whole class of such problems, it should be fine now

**Comment by akinsho** [comment]
Awesome 👍🏿 thanks for the quick fix
