### ISSUE TITLE
Open xxx.xpt.vim echom E688: More targets than List items

### ISSUE THREAD

**Issue by bstaint** [sheerun/vim-polyglot#58]
When use vim-polyglot and xptemplate , open one xpt.vim file will echom:
```
Error detected while processing  D:\\...\xptemplate\ftplugin\xpt\xpt.xpt.vim:
line  31:
E688: More targets than List items
```
I think `ftplugin\scala.xpt.vim` should be move to `ftplugin\scala\scala.xpt.vim`.

**Comment by sheerun** [comment]
Could you provide example file that causes this error?

**Comment by bstaint** [comment]
command:
`:e test.xpt.vim`

message:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"[No Name]" --No lines in buffer--
Error detected while processing D:\\...\xptemplate\ftplugin\xpt\xpt.xpt.vim:
line   31:
E688: More targets than List items
```

**Comment by sheerun** [comment]
Yup. Could you paste `tst.xpt.vim` somewhere?

**Comment by bstaint** [comment]
It's just empty file.

**Comment by sheerun** [comment]
Are you sure it's because if vim-polyglot? I can't reproduce. I get no error.

**Comment by bstaint** [comment]
screenshot:
![1](https://cloud.githubusercontent.com/assets/5853792/8768780/13c606a6-2ebe-11e5-89cc-ba110c64a110.gif)

I think xptemplate load scala.xpt.vim but can't split filetype, some code:
```
let [ ft, snip ] = split( v, '/' ) 
```
The v should be `scala/scala.xpt.vim`.

**Comment by sheerun** [comment]
What happens when you uninstall `vim-polyglot`, and install `derekwyatt/vim-scala` instead?

**Comment by bstaint** [comment]
The same problem.

**Comment by sheerun** [comment]
Well, it's not vim-polyglot issue then. Please report it to vim-scala :)

**Comment by sheerun** [comment]
Please note I can't reproduce you problem, so it's quite likely problem with your setup, and not vim-scala.

**Comment by bstaint** [comment]
OK, I found https://github.com/derekwyatt/vim-scala/issues/28
