### ISSUE TITLE
Please consider supporting todo.txt syntax

### ISSUE THREAD

**Issue by ferki** [sheerun/vim-polyglot#581]
**What is the name of this language in Linguist?**

Not sure if it's a language per se, did not find it in Linguist.

**Link to GitHub repository of Vim plugin**

[Main repo on GitLab](https://gitlab.com/dbeniamine/todo.txt-vim)
[GitHub mirror](https://github.com/dbeniamine/todo.txt-vim) (seems to lag behind a bit though)

**Is this plugin well maintained?**

Looks like this is the most maintained fork of the now unmaintained [original plugin](https://github.com/freitass/todo.txt-vim), improving on that in several ways.

**Is this plugin lightweight? (no advanced functionality, just indent and syntax support)**

Compared to the original version's rejection on #307, this fork seems to have removed the python dependency at least.

**Comment by sheerun** [comment]
This isn't really syntax-only plugin, so I'd rather not, sorry!

**Comment by ferki** [comment]
No problem, one may continue to use it directly then :)

For next time, is there any written down criteria/guidelines on how to decide which plugins would be a good fit for potential inclusion?

**Comment by sheerun** [comment]
Well, just like written :) "Is this plugin lightweight? (no advanced functionality, just indent and syntax support)". todo.txt is far more than just indent and syntax
