### ISSUE TITLE
Neovim syntax files for vimscript break highlighting in Vim

### ISSUE THREAD

**Issue by reneegyllensvaan** [sheerun/vim-polyglot#582]
**Does this bug happen when you install plugin without vim-polyglot?**
(not really applicable since it's vim's runtime files, but it does not happen without vim-polyglot)

**Describe the bug:**
Polyglot recently started breaking vimscript highlighting for me on vanilla vim. It looks like it changed with the fix for #578, where the vimscript files were swapped for neovim's. These don't seem to work with regular vim, causing unhighlighted command names, and highlighting most function calls in command definitions as errors.

I use Vim8 packages, without a wrapper, as an `opt` package, that I manually load before setting `filetype` and `syntax`.

**To Reproduce:**
Grab this minimal self-installing vimrc (or just don't load polyglot some other way)
```vim
" vim: ft=vim
call system('mkdir -p '.$HOME.'/pack/plugins/opt')
if empty(glob('~/.vim/pack/plugins/opt/polyglot'))
  call system('git clone https://github.com/sheerun/vim-polyglot ~/.vim/pack/plugins/opt/polyglot')
end

if $USE_POLYGLOT == "yes"
  packadd polyglot
end

filetype plugin indent on
syntax on

command! Foo call split(expand('%'), '/')

augroup edcon
  autocmd!
  autocmd FileType special echo expand(':e')

augroup END
```

Running two vim instances, the one on the left with just `vim ~/.vimrc`, the other one with `USE_POLYGLOT=yes vim ~/.vimrc` gives:
![image](https://user-images.githubusercontent.com/10882831/95678267-d3866900-0bcb-11eb-9873-e00fb893eb34.png)

**Comment by ghifarit53** [comment]
I haven't updated my vim plugins for months. Today I updated all of them and realized I got this issue too when editing my `vimrc`. Also, changing the color of `vimOption` group seems gave no effect

It looks like this
![null](https://user-images.githubusercontent.com/59758342/95964504-64da2300-0df8-11eb-85bc-711dae2b6f9d.png)

When normally, it looks like this
![null](https://user-images.githubusercontent.com/59758342/95964570-7a4f4d00-0df8-11eb-93b1-52fda8026d0b.png)

**Comment by reneegyllensvaan** [comment]
@ghifarit53 You can add `let g:polyglot_disabled = ['vim.plugin']` to your vimrc before you load vim-polyglot to fall back to the bundled runtime highlighting (which is what it seems like it used previously anyway) as a workaround until this is fixed.

**Comment by sheerun** [comment]
Thanks. I'll just remove vim syntax from polyglot for now.
