### ISSUE TITLE
Error when idle in netrw

### ISSUE THREAD

**Issue by xerocole** [sheerun/vim-polyglot#584]
**Does this bug happen when you install plugin without vim-polyglot?**
No

**Describe the bug:**
After sitting idle with netrw as a new buffer the following error appears on my status bar.

"Error detected while processing CursorHold Autocommands for "<buffer=4>":                                                                                                                                                            
E121: Undefined variable: b:polyglot_observe"

Not sure what to make of it.
**To Reproduce:**
Open netrw via :Texplore
Wait for about 20 seconds'=
The error appears.

**Comment by sheerun** [comment]
I can't reproduce with following .vimrc and vim 8.2:

```vim
set nocompatible

call plug#begin('~/.vim/plugged')

Plug 'sheerun/vim-polyglot'

call plug#end()
```

**Comment by sheerun** [comment]
I've changed the implementation. I hope it helps, could you confirm?

**Comment by jjmurre** [comment]
Came across this same issue. Just upgrade vim-polyglot (to `4c10562d2cc9b084518284c49a158558da5180a7`). Now the error is gone.
