### ISSUE TITLE
*.pl file detection doesn't respect g:filetype_pl

### ISSUE THREAD

**Issue by mwgkgk** [sheerun/vim-polyglot#586]
There's a rather obscure way to hard set the .pl files to be detected as the filetype of your choosing.

Here's where the `dist#ft#FTpl()` function is called for *.pl files:

https://github.com/vim/vim/blob/master/runtime/filetype.vim#L1178

Here's the function itself, hard setting the value from `g:filetype_pl` if it exists:

https://github.com/vim/vim/blob/master/runtime/autoload/dist/ft.vim#L339

Current behavior: for empty *.pl files, it's straight up `raku` regardless of `g:filetype_pl`. With raku added to `g:polyglot_disabled`, it's `perl`. With both added to `g:polyglot_disabled`, it's equal to `g:filetype_pl` (or `perl` by default).

Desired behavior: follow the upstream and allow globally setting *.pl filetype with `g:filetype_pl`. This is useful for cases where heuristics are inapplicable.

**Comment by sheerun** [comment]
This should already work as you describe. Here's .vimrc I use:

```vim
let g:filetype_pl = 'asf'

call plug#begin('~/.vim/plugged')

Plug 'sheerun/vim-polyglot'

call plug#end()
```

Now if you open .pl file it sets filetype to asf

**Comment by mwgkgk** [comment]
Indeed it does! Thanks for looking into it.
