### ISSUE TITLE
Typescript auto-indent incorrectly in some cases.

### ISSUE THREAD

**Issue by lcdsmao** [sheerun/vim-polyglot#590]
**Does this bug happen when you install plugin without vim-polyglot?**
No

**Describe the bug:**
Typescript file auto-indent incorrectly when the first code block that contains indention is a generic type with more than two type parameters.

**To Reproduce:**

Open a ts file that has this content:
```typescript
type Bar = Foo<
  {
    x: string
  },
  {
    y: string
  }
>
```

The `shiftwidth` was expected to be 2 but get 4.

**Comment by sheerun** [comment]
thanks, it should be better now
