### ISSUE TITLE
Vim can't detect markdown syntax if the file starts with a heading h1-h6

### ISSUE THREAD

**Issue by gerardbm** [sheerun/vim-polyglot#591]
The bug appeared after the last updates of the plugin `vim-polyglot`.

Vim can't detect the markdown syntax if you disable markdown syntax from the plugin and the file starts with a heading `h`.

Steps to reproduce:
1. Add this line to your `.vimrc` → `let g:polyglot_disabled = ['markdown']`
2. Make a markdown file with a heading h1-h6 → `## Something`
3. Open that file with vim. Now the syntax is `Something` instead of `markdown`.

I don't understand some changes of this plugin, since it worked perfectly for the last years.

**Comment by sheerun** [comment]
I mean, you disabled markdown syntax. You want vim-native highlighting, right/

**Comment by gerardbm** [comment]
Yes, I disable markdown syntax only from the `vim-polyglot` using this line: `let g:polyglot_disabled = ['markdown']`

**Comment by sheerun** [comment]
Gotcha. It should be fine now
