### ISSUE TITLE
nocompatible conflict options

### ISSUE THREAD

**Issue by bstaint** [sheerun/vim-polyglot#593]
**Does this bug happen when you install plugin without vim-polyglot?**

**Describe the bug:**
vimrc
```
filetype plugin on
syntax on
set nocompatible

silent! call plug#begin($VIM.'/vimfiles/plugged')
Plug 'sheerun/vim-polyglot'
Plug 'Shougo/echodoc.vim'
set noshowmode

call plug#end()

let g:echodoc#enable_at_startup = 1
```
It 's will overwrite `showmode`
`verbose set showmode`:
```
showmode
    Last set from D:\Portable\gvim\vimfiles\plugged\vim-polyglot\ftdetect\polyglot.vim line 14
```

**To Reproduce:**

**Comment by sheerun** [comment]
you're totally right, I overdid it. I need to find minimal options needed for polyglot to work and enable only them

**Comment by sheerun** [comment]
btw. polyglot enables syntax and filetype plugin on by itself, which is faster because it prevents loading ftdetect files two times: one of native vim, and one of vim-polyglot

**Comment by sheerun** [comment]
I've made vim-polyglot to be able to load in non-compatible mode and added defaults from vim-sensible

**Comment by bstaint** [comment]
Tks.
