### ISSUE TITLE
/etc/hosts not detected as conf

### ISSUE THREAD

**Issue by subnut** [sheerun/vim-polyglot#595]
**Does this bug happen when you install plugin without vim-polyglot?**
No plugin for `conf` file is mentioned in the README, so... :shrug: 

**Describe the bug:**
If you open /etc/hosts file without vim-polyglot, it is detected as a `conf` file, which is correct.
But after installing vim-polyglot, the filetype is not detected (i.e. `set ft?` returns ` filetype= `)

**To Reproduce:**
See above description

**Minimal vimrc**
```vim
call plug#begin('~/.vim/plugged')
Plug 'sheerun/vim-polyglot'
call plug#end()
```

**Comment by sheerun** [comment]
native vim sets conf filetype if one of first 5 lines begins with `#`... I've chosen to be more specific so conf would be set for files even if they don't have `#` in them. Also in this case filetype should be hostconf not conf

**Comment by sheerun** [comment]
sorry, not hostconf

**Comment by sheerun** [comment]
For now I've set it to conf but I wonder if there's better syntax for /etc/hosts somewhere there

**Comment by subnut** [comment]
> native vim sets conf filetype if one of first 5 lines begins with #...

Well.. TBH my file had a `#` right at the start, 1st character of 1st line :smile: 

<br>

> better syntax for /etc/hosts somewhere

Actually, /etc/hosts is not a syntax, it is a particular file called `hosts`, located at `/etc/hosts` in linux, and `C:\Windows\System32\drivers\etc\hosts` in Windows :sweat_smile:

**Comment by sheerun** [comment]
if this will happen often enough I re-enable this behavior, but for now I'd like to improve list of such files
