### ISSUE TITLE
Tex files set their indent to expandtab, sw=2

### ISSUE THREAD

**Issue by Groctel** [sheerun/vim-polyglot#596]
**Does this bug happen when you install plugin without vim-polyglot?**

No

**Describe the bug:**

I always use hard tabs in tex files.
When I updated to the latest version, Polyglot started changing the indent style to expandtab, sw=2.

**To Reproduce:**

Open a .tex file without disabling autoindent.

**Comment by sheerun** [comment]
Tex filed I've found use spaces, not tabs. Could you send yours?

**Comment by Groctel** [comment]
I have lots in this repo: https://github.com/Groctel/ugr-informatica/blob/main/2%C2%BA%202%C2%BA%20cuatrimestre/Arquitectura%20de%20computadores/Teoria/EvaluacionPrestacionesArquitectura.tex (this one's an example).

Are you planning on adding a way to disable (or enable) autoindent per filetype?

**Comment by sheerun** [comment]
This should be fixed now. I won't add it unless really necessary. You you want you set it manually with something like `au FileType tex set noexpandtab ts=4 sw=2` etc, but I aim it to work, not to be overridden
