### ISSUE TITLE
extras/menu.vim not exist

### ISSUE THREAD

**Issue by zzs213** [sheerun/vim-polyglot#598]
**Does this bug happen when you install plugin without vim-polyglot?**
NO

**Describe the bug:**
After I disble "rst" using the flowwing setting:

    let g:polyglot_disabled = ['rst']

vim report this message:

    Can't open file ....../vim-bundle/vim-polyglot/extras/menu.vim

**To Reproduce:**

**Comment by sheerun** [comment]
This should be fixed now, thank you
