### ISSUE TITLE
Breaks expandtab for Makefiles

### ISSUE THREAD

**Issue by mirosval** [sheerun/vim-polyglot#599]
**Does this bug happen when you install plugin without vim-polyglot?**
AFAIK vim-polyglot does not have a plugin for Makefiles

**Describe the bug:**
When vim-polyglot is loaded, it sets expandtab on makefiles.

**To Reproduce:**
1. Have vim-polyglot in .vimrc
2. Open a makefile
3. Tab inserts spaces instead of tabs
4. Running `:verbose set expandtab?` shows this:

<img width="954" alt="Screenshot 2020-10-22 at 09 20 38" src="https://user-images.githubusercontent.com/1315417/96838418-296ad480-1448-11eb-8b58-655047df4c2d.png">

**Comment by mirosval** [comment]
So after some investigation, it seems that the makefile config relies on tabs already being in the file. 
If I create a new file, initially there are neither spaces nor tabs, so it defaults to spaces. 
But if the file already has tabs, then it works.

**Comment by jrudess** [comment]
Makefiles use both tabs and spaces.   Setting expandtab for a make file make it impossible to write valid syntax.   For now, it seems necessary to disable the autoindent feature of polyglot if you regularly edit makefiles.

https://stackoverflow.com/questions/28712585/when-to-use-space-or-tab-in-makefile

> Recipes (the commands that run compilers, echo, etc.) are written in shell script syntax.
> 
> The rest of the makefile that is not in a recipe is written in makefile syntax.
> 
> In order for make to tell the difference between a recipe and things that are not a recipe, it uses TAB characters. So, lines that begin with TAB are assumed to be part of a recipe (so they are shell scripts and passed to the shell for parsing), and lines that do not begin with TAB cannot be part of a recipe (so they cannot be shell scripts: they must be make syntax).

**Comment by sheerun** [comment]
Weird, for me it defaults to tabs

**Comment by sheerun** [comment]
what is the output of `:echo b:sleuth_culprit` for you?
