### ISSUE TITLE
tabstop reset from 8 to 2 for Makefiles

### ISSUE THREAD

**Issue by mjturner** [sheerun/vim-polyglot#600]
**Does this bug happen when you install plugin without vim-polyglot?**
N/A. Removing vim-polyglot results in `tabstop` not being reset.

**Describe the bug:**
I have `tabstop` set to `8` in `~/.vim/ftplugin/make.vim` but it is being reset to `2` by vim-polyglot.

![capture_2020-10-22_03-30-44_pm](https://user-images.githubusercontent.com/8258/96887258-53d68500-147c-11eb-8fd4-db5e91c642a1.png)

The stanza in question in `polyglot.vim` does the following:

    if &tabstop == 8
        let &l:tabstop = 2
    endif

**To Reproduce:**
1. Install vim-polyglot
2. Set `tabstop` to `8`. I have this in `~/.vim/ftplugin/make.vim`, but doing so in `vimrc` will probably have the same effect.
3. Edit an existing Makefile containing tabs. `tabstop` has been reset from `8` to `2`.

**Comment by mjturner** [comment]
I thought trying the following would help:

    let g:polyglot_disabled = ['make']

Unfortunately it didn't. Setting `tabstop` to `7` in `ftplugin/make.vim` works fine, it's only `8` that results in it being reset.

**Comment by sheerun** [comment]
`let g:polyglot_disabled = ['autoindent']` should help. What do you think should be default for makefiles? tabs or spaces?

**Comment by sheerun** [comment]
what is the output of `:echo b:sleuth_culprit` for you? what is the content of this file?

**Comment by sheerun** [comment]
```
      if &tabstop == 8
        let &l:tabstop=shiftwidth
      endif
```

should be executed only if expandtab is set which should not happen in the first place

**Comment by sheerun** [comment]
I removed this `if` and setting only softtabstop as per vim's help:

```
	There are four main ways to use tabs in Vim:
	1. Always keep 'tabstop' at 8, set 'softtabstop' and 'shiftwidth' to 4
	   (or 3 or whatever you prefer) and use 'noexpandtab'.  Then Vim
	   will use a mix of tabs and spaces, but typing <Tab> and <BS> will
	   behave like a tab appears every 4 (or 3) characters.
	2. Set 'tabstop' and 'shiftwidth' to whatever you prefer and use
	   'expandtab'.  This way you will always insert spaces.  The
	   formatting will never be messed up when 'tabstop' is changed.
	3. Set 'tabstop' and 'shiftwidth' to whatever you prefer and use a
	   |modeline| to set these values when editing the file again.  Only
	   works when using Vim to edit the file.
	4. Always set 'tabstop' and 'shiftwidth' to the same value, and
	   'noexpandtab'.  This should then work (for initial indents only)
	   for any tabstop setting that people use.  It might be nice to have
	   tabs after the first non-blank inserted as spaces if you do this
	   though.  Otherwise aligned comments will be wrong when 'tabstop' is
	   changed.
```

**Comment by mjturner** [comment]
Perfect, thanks - it's working as expected now (without `polyglot_disabled` set). Makefiles typically have a mix of tabs and spaces and those that I work with typically assume a tab width of 8.
