### ISSUE TITLE
order of g:polyglot_disabled options affects settings

### ISSUE THREAD

**Issue by mtklr** [sheerun/vim-polyglot#602]
**Does this bug happen when you install plugin without vim-polyglot?**

No

**Describe the bug:**

The order of settings given in `let g:polyglot_disabled = ['...', '...']` affects whether they (or just "sensible"?) are disabled or not.

**To Reproduce:**

``` vim
" disables 'sensible' (checking with 'incsearch', incsearch is off)
`let g:polyglot_disabled = ['sensible', 'autoindent']`

vs.

" does not disable 'sensible' ('incsearch' still set via vim-polyglot)
let g:polyglot_disabled = ['autoindent', 'sensible']
```

Sorry if I'm misunderstanding how this should work.

Thank you!

**Comment by sheerun** [comment]
This should be now fixed. May I know why you're disabling sensible settings? Is it because of incsearch?

**Comment by mtklr** [comment]
I was surprised that polyglot changed some settings automatically, so I fooled around with disabling things (as you show in your documentation). I'm also just not used to setting 'incsearch', for some reason. :)

Thank you.

**Comment by sheerun** [comment]
Got it. I've just made you able to override incsearch if it's set after vim-polyglot is loaded. If more users will complain here, I'll consider disabling it all together

**Comment by sheerun** [comment]
For example: 

```
set nocompatible

call plug#begin()

Plug 'sheerun/vim-polyglot'

call plug#end()

set noincsearch
```

**Comment by mtklr** [comment]
> For example: 
> 
> 
> 
> ```vim
> 
> set nocompatible
> 
> call plug#begin()
> 
> Plug 'sheerun/vim-polyglot'
> 
> call plug#end()
> 
> set noincsearch
> 
> ```

That makes sense... thanks for taking the time to work on these issues.
-Matt
