### ISSUE TITLE
error detecting shell filetypes

### ISSUE THREAD

**Issue by mtklr** [sheerun/vim-polyglot#603]
**Does this bug happen when you install plugin without vim-polyglot?**

no

**Describe the bug:**

Editing a shell filetype with `let g:polyglot_disabled = ['option']` in `~/.vimrc` gives errors.

**To Reproduce:**

add `let g:polyglot_disabled = ['option' ...] to `~/.vimrc`

edit a shell file

vim returns:

```
Error detected while processing BufRead Auto commands for ".bashrc":
E117: Unknown function: dist#ft#SetFileTypeSH
```

Thanks again.

**Comment by sheerun** [comment]
probably should be fine now, thank you
