### ISSUE TITLE
Custom C/C++ syntax broken after commit cbde2571d4f79770ac552fe75440de72893bc73a

### ISSUE THREAD

**Issue by kostiskalkounos** [sheerun/vim-polyglot#608]
I use a custom function to highlight C/C++ objects and it was working perfectly before the aforementioned commit: 'Respect symlinks for resolving vim-polyglot as fallback, closes #601'

The problem seems to be that the custom `.vim/after/syntax/c.vim` is the only file read , where before, the custom changes were applied on top of `bfrg/vim-cpp-modern/after/syntax/c.vim`

Before:

<img width="354" alt="Screen Shot 2020-10-25 at 12 22 54" src="https://user-images.githubusercontent.com/27889580/97105683-1b71b980-16bd-11eb-8cb2-16c31bc840e0.png">

After:
<img width="342" alt="Screen Shot 2020-10-25 at 12 22 30" src="https://user-images.githubusercontent.com/27889580/97105687-275d7b80-16bd-11eb-845a-d25252fc1a48.png">

**Comment by sheerun** [comment]
Could you send your .vimrc ?

**Comment by kostiskalkounos** [comment]
https://github.com/kostiskalkounos/dotfiles/blob/main/vim/.vimrc

The custom syntax is here:

https://github.com/kostiskalkounos/dotfiles/blob/main/vim/.vim/after/syntax/c.vim

**Comment by sheerun** [comment]
Here are two screenshots, one with `Plug 'sheerun/vim-polyglot'` commented, and second one uncommented. There's no difference. Maybe you need to update or something? I can try to fix it but I cannot reproduce

**Comment by sheerun** [comment]
https://imgur.com/a/xMynyou

**Comment by sheerun** [comment]
Okay, I see the difference, but only when using neovim, I'll try to fix it

**Comment by kostiskalkounos** [comment]
I never disabled your plugin, I just reverted back to an older commit to show the expected behavior.
I have this issue both in ViM and Neovim, so it's not Neovim specific.

I'll try to explain the issue better:

My first screenshot shows everything working as expected. I have my custom types highlighted in yellow, the function name is blue and the const keyword is purple.

In order to have const be highlighted with purple I need to enable the behavior through the `bfrg/vim-cpp-modern/`, which you support, with this line in my .vimrc `let g:cpp_simple_highlight = 1`.

After the introduction of the aforementioned commit, things broke. To be precise the function name stopped being blue and the const keyword is yellow.

My types are correctly highlighted though, which makes me think that the syntax file of the plugin is ignored in favor of my custom syntax file.

**Comment by sheerun** [comment]
Your custom file should be named `after/syntax/cpp.vim`, not `after/syntax/c.vim`, because `vim-cpp-modern` is loaded as `after/cpp.vim`. It's hard to guarantee that `after/cpp.vim` of other plugins will always load before yours `after/c.vim`. This only works because vim-plug cares about loading order which would not be the case for example for vim 8 packages

**Comment by kostiskalkounos** [comment]
If I do this it works as expected for C++ syntax highlighting but if breaks for C.
Before this commit it was working correctly for both.

**Comment by sheerun** [comment]
Ok I guess I'll need to ensure loading order is preserved even though Bram says otherwise: https://github.com/vim/vim/issues/7056#issuecomment-702166962

**Comment by kostiskalkounos** [comment]
If I understood what I read correctly, Bram believes that we should be able to add new things on top of the preexisting ones without overriding them, hence why my syntax file was working correctly before. Am I missing something?

**Comment by sheerun** [comment]
Bram says that plugins should not depend order of loading of each other. In your case you're depending on after files of vim-cpp-modern to load before your after files. It seems recent changes of vim-polyglot changed this order, I'll try to revert that

**Comment by kostiskalkounos** [comment]
Ah I see, it's clear now, thanks for the explanation!

**Comment by sheerun** [comment]
Should be fine now, the loading order is as follows:

1. All paths until $VIMRUNTIME
2. Vim-polyglot
3. $VIMRUNTIME 
4. vim-polyglot after
5. all other after files

**Comment by kostiskalkounos** [comment]
Now it's more broken than before. The `bfrg/vim-cpp-modern` plugin isn't called at all, unless I have to call it in a different way.

If it's tricky to fix, you can revert the changes and I will maintain a hacky version to have the expected output.

Actual:
<img width="358" alt="Screen Shot 2020-10-25 at 20 47 39" src="https://user-images.githubusercontent.com/27889580/97117399-d329ba00-1703-11eb-8782-e92b4b3d59c8.png">


Expected:

<img width="365" alt="Screen Shot 2020-10-25 at 20 50 27" src="https://user-images.githubusercontent.com/27889580/97117394-cad17f00-1703-11eb-86f7-000a7add6762.png">

**Comment by sheerun** [comment]
Sorry, not should work. I made silly mistake

**Comment by kostiskalkounos** [comment]
It's perfect, thanks a ton!
