### ISSUE TITLE
Polyglot is breaking preservim/tagbar

### ISSUE THREAD

**Issue by matheusfillipe** [sheerun/vim-polyglot#609]
**Does this bug happen when you install plugin without vim-polyglot?**
The bug happens if both tagbar and polyglot are sourced. It breaks functionality of tagbar.
https://github.com/preservim/tagbar

**Describe the bug:**
Tagbar stops working properly if polyglot is sourced.

**To Reproduce:**
When I have both lines:
```
Plug 'sheerun/vim-polyglot'
Plug 'preservim/tagbar'

```

On my init.vim (I am using neovim), tagbar wont load at first, will generate a blank buffer. Then it works normally after second attempt.
This log is generating by opening vim and launching :tagbar.
[myvim.log](https://github.com/sheerun/vim-polyglot/files/5436649/myvim.log)

**Comment by Frederick888** [comment]
Not sure whether this is related but I just noticed 45a7512 broke https://github.com/antoinemadec/coc-fzf under both Linux and macOS.

Could you please try `git -C /path/to/vim-polyglot reset --hard 45a7512~` to see if your problem is gone? If not I'll file another issue.

**Comment by matheusfillipe** [comment]
No. Resenting it to 45a7512 didn't help. Still same issue.

**Comment by Frederick888** [comment]
@matheusfillipe I meant the commit before 45a7512, so not `git reset --hard 45a7512` but `git reset --hard 45a7512~` :)

**Comment by matheusfillipe** [comment]
Oh my bad. I mean I am on  81ada11 and the issue still happens. Bad pasting :P

**Comment by Frederick888** [comment]
Thanks for the confirmation!

**Comment by matheusfillipe** [comment]
Since it works after second attempt I suspect can be some variable that shouldn't be touched problem or so. I am printing the variables to a file and diffing them. Before is just when I open nvim, after is after i tried twice (:TagbarToggle) and it finally worked fine.

[diff.txt](https://github.com/sheerun/vim-polyglot/files/5436703/diff.txt)
[after.txt](https://github.com/sheerun/vim-polyglot/files/5436704/after.txt)
[before.txt](https://github.com/sheerun/vim-polyglot/files/5436705/before.txt)

**Comment by sheerun** [comment]
could you show output of `:echo &rtp` without vim-polyglot, and after adding it?

**Comment by sheerun** [comment]
I think it should be fixed now

**Comment by matheusfillipe** [comment]
Thanks! It's fixed!
