### ISSUE TITLE
Plugin breaks snippets

### ISSUE THREAD

**Issue by delminskii** [sheerun/vim-polyglot#612]
With `vim-polyglot` installed `vim-snipmate` (with `vim-snippets`) doesn't work. W/o it installed snippets work as expected.

**Does this bug happen when you install plugin without vim-polyglot?**
No

**Describe the bug:**
But everything is fine with polyglot tagged `v4.15.1`.

**To Reproduce:**
Install:
" Snippets
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'garbas/vim-snipmate'
Plug 'honza/vim-snippets'

and try some snippets (pressing `tab`) for language you like.

**Comment by sheerun** [comment]
could you show output of `:echo &rtp` without vim-polyglot, and after adding it?

**Comment by delminskii** [comment]
Sure.
1. An output with polyglot v4.15.1
[rtp_polyglot_v4.15.1.txt](https://github.com/sheerun/vim-polyglot/files/5439357/rtp_polyglot_v4.15.1.txt)

2. An output without polyglot
[rtp_wo_polyglot.txt](https://github.com/sheerun/vim-polyglot/files/5439361/rtp_wo_polyglot.txt)

3. An output with the latest polyglot
[rtp_polyglot_latest.txt](https://github.com/sheerun/vim-polyglot/files/5439363/rtp_polyglot_latest.txt)

**Comment by sheerun** [comment]
Should be ok now, yes?
