### ISSUE TITLE
Error detected while processing vim-polyglot/autoload/go/config.vim

### ISSUE THREAD

**Issue by Tonkpils** [sheerun/vim-polyglot#613]
**Does this bug happen when you install plugin without vim-polyglot?**

No

**Describe the bug:**

When starting vim, I am receiving this error message

```
Error detected while processing vim-polyglot/autoload/go/config.vim:
line    1:
E121: Undefined variable: g:polyglot_is_disabled
E116: Invalid arguments for function has_key
E15: Invalid expression: has_key(g:polyglot_is_disabled, 'go')
```

**To Reproduce:**

This started happening when I updated `vim-polyglot` to master. It seems that https://github.com/sheerun/vim-polyglot/commit/45a7512dea0599efaf96e8a2cad3fac7be61cf5d introduced the changes mentioned.

I am using `neovim 0.4.4` and `minpac` for plugin management. Removing `vim-polyglot` from the plugin list causes vim to start up fine.

**Comment by sheerun** [comment]
Could I see your init.vim?

**Comment by Tonkpils** [comment]
```
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source $HOME/.config/nvim/plugins.vim
source $HOME/.vim/vimrc
```

**Comment by citizen428** [comment]
I'm was seeing the same error. 

* nvim v0.5.0-nightly (`HEAD-ce5a260`). 
* [minpac](https://github.com/k-takata/minpac) as plugin manager: 
`init.vim` [here](https://github.com/citizen428/nvim-config/blob/master/init.vim).

As a workaround for now I explicitly set the following in my `init.vim` which gets rid of the error:

```viml
let g:polyglot_is_disabled={}
```

**Comment by theodelrieu** [comment]
I was using the old variable `g:polyglot_disabled`... took me 15mins to figure out :facepalm:

**Comment by sheerun** [comment]
you should not use `g:polyglot_is_disabled` it's internal variable...

**Comment by citizen428** [comment]
That's why I called it a workaround. Explicitly setting it makes the error on startup disappear that a recent update introduced, which is all I want until a proper fix shows up.

**Comment by zb140** [comment]
In case it helps, i have this same issue with Vim 8.2 (rather than neovim).  I am also using minpac -- I wonder if there's a bad interaction with that.

**Comment by sheerun** [comment]
It's because minpac loads plugins alphabetically, and not in the order defined in init.vim / .vimrc (the same as vim 8 packages)

Because of this go plugin is loaded before polyglot (because "g" is before "p"). Go plugin calls `go#config` but polyglot hasn't been loaded yet (and it needs to be loaded first so runtime path is rewritten properly), and because of this polyglot's "autoload" files are loaded instead of Go's. I guess the workaround in this case is to add code to polyglot's autoload files that try to source non-bundled plugins code first..

**Comment by sheerun** [comment]
I think it should work now even for vim 8 packages

**Comment by wookayin** [comment]
I think checking of `g:polyglot_disabled` is too early (on VimEvent). I had `let g:polyglot_disabled = ...` **after** `plug#begin() ... Plug 'sheerun/vim-polyglot' plug#end()`, but at this moment polyglot checking is already run. Not sure why polyglot was loaded so early.

**Comment by zdutta** [comment]
Hello, I'm seeing same issue after updating the package. Any suggestions on how to triage? Thanks!
