### ISSUE TITLE
Error detected while processing function <SNR>11_process_rtp

### ISSUE THREAD

**Issue by benliepert** [sheerun/vim-polyglot#616]
**Does this bug happen when you install plugin without vim-polyglot?**
No
**Describe the bug:**
Loading vim produces the following error to the command line (before entering vim):

Error detected while processing function <SNR>11_process_rtp:
line   22:
E121: Undefined variable: i:
E15: Invalid expression: rtp[i:-1]
line   32:
E121: Undefined variable: i:
E15: Invalid expression: rtp[i:-1]

**To Reproduce:**
Once vim-polyglot is installed, the error is output every time vim is loaded, and there's no syntax highlighting

I'm using vim 7.4

**Comment by sheerun** [comment]
very weird, `i` is definitely defined there

**Comment by benliepert** [comment]
I should add that this happened after a plug update. The last time I did a plug update was about a week ago.
This is also on a development server for work (hence the old version of vim), but I can try to get versions/logs if you want to look at anything specific.
It's working fine on my arch linux system (everything up to date)

**Comment by ZSaberLv0** [comment]
got same issue

I think vim 7.4 does not support `array[i:-1]` syntax

**Comment by sheerun** [comment]
> change default editor behavior, such as tabstop, it should be configured by user or editor config

It should be the case, if it's not then it's a bug. Vim-polyglot should override tabstop only if it's not defined by user

> use tricks to achieve some complex features, if anything wrong occurred, it's quite hard to locate the issue

Unfortunately it's necessary to support different package managers :( Wspecially vim 8 packages

**Comment by ZSaberLv0** [comment]
@sheerun issue still occurrs

```
Error detected while processing function <SNR>42_process_rtp:
line   22:
E117: Unknown function: i:len
E15: Invalid expression: rtp[i:len(rtp)-1]
line   32:
E117: Unknown function: i:len
E15: Invalid expression: rtp[i:len(rtp)-1]
```

vim version:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 28 2019 13:59:14)
Included patches: 1-160, 399, 402-403, 1099
```

**Comment by billyyoung** [comment]
@ZSaberLv0 upgrading to vim 8 solved the issue for me
