### ISSUE TITLE
Highlighting

### ISSUE THREAD

**Issue by PouriDev** [sheerun/vim-polyglot#617]
How can I change the highlightings for C++ file or other files? And how can I disable polyglot for C++ files?
Tried: 
`let g:polyglot_disables = ['c++']`
`let g:polyglot_disables = ['cpp']`
`let g:polyglot_disables = ['cplucplus']`
but none of them worked

**Comment by alex-shamshurin** [comment]
I try to  disable it for typescript and I see that it doesn't work too.  
let g:polyglot_disabled = ['sensible', 'typescript', 'javascript']

**Comment by sheerun** [comment]
what do you mean?

**Comment by sheerun** [comment]
correct one is `g:polyglot_disabled = ['c/c++']`

**Comment by sheerun** [comment]
@alex-shamshurin just curious, why do you disable sensible config of vim-polyglot?

**Comment by alex-shamshurin** [comment]
> @alex-shamshurin just curious, why do you disable sensible config of vim-polyglot?

Because I have it already in my config and it loaded before! Also I have noticed that polyglot do much more than syntax and for years I had different issues with that. My opinion that software must do just one thing and do it well.

**Comment by sheerun** [comment]
Ok. Vim-Polyglot only included subset of sensible needed for editing any
language. Actually I should stop advertising it as sensible, because it
seems it annoys users

**Comment by alex-shamshurin** [comment]
So how to disable any plugin ? It seems to be a bug there, it doesn't work.  (in my case I'm disabling typescript temporarily to try out different syntax )

**Comment by PouriDev** [comment]
Is there any way to change the highlighting settings for c++ or other files? I mean I don't want functions be something like green. I want to change it to some colors else

**Comment by alex-shamshurin** [comment]
> Is there any way to change the highlighting settings for c++ or other files? I mean I don't want functions be something like green. I want to change it to some colors else

I think it's not related to polyglot it's just use other projects

**Comment by pi-rho** [comment]
> Ok. Vim-Polyglot only included subset of sensible needed for editing any language. Actually I should stop advertising it as sensible, because it seems it annoys users

"subset" as in most of it (4 set commands?). Maybe take it all out and recommend vim-sensible?

**Comment by sheerun** [comment]
i tried to keep it to minimum

**Comment by alex-shamshurin** [comment]
Hmm, it's closed, ok, bit how to actually disable some file types ? It doesn't work how it's described in docs

**Comment by sheerun** [comment]
@alex-shamshurin What's your vimrc?

**Comment by alex-shamshurin** [comment]
```
let g:polyglot_disabled = ['sensible', 'typescript']

Plug 'sheerun/vim-polyglot'
  " for typescript polyglot uses the desired yats by default
  "
  "" ruby support (vim-ruby)
  let g:ruby_indent_block_style='do'
  let g:ruby_indent_assignment_style='variable'
  let g:rubycomplete_rails=1
  let g:rubycomplete_classes_in_global=1
  let g:rubycomplete_include_object=1
  let g:rubycomplete_include_objectspace=1
  let g:rubycomplete_use_bundler=1

  "" haskell support (neovimhaskell/haskell-vim)
  " indent 'where' block two spaces under previous body
  let g:haskell_indent_before_where=2
  " allow a second case indent style (see haskell-vim README)
  let g:haskell_indent_case_alternative=1
  " only next under 'let' if there's an equals sign
  let g:haskell_indent_let_no_in=0

  "" elm support (ElmCast/elm-vim)
  let g:elm_format_autosave=1
  let g:elm_detailed_complete=1
  let g:elm_syntastic_show_warnings=1
  let g:elm_format_fail_silently=1
  let g:elm_browser_command='open'
  let g:elm_make_show_warnings=1
  let g:elm_setup_keybindings=1

  "" rust support (rust-lang/rust.vim)
  let g:rustfmt_autosave=1

  "" python support (vim-python/python-syntax)
  let g:python_highlight_class_vars=1
  let g:python_highlight_indent_errors=1

  "" terraform support (hashivim/vim-terraform)
  let g:terraform_align=1

  "" markdown (plasticboy/vim-markdown)
  let g:vim_markdown_folding_disabled=1



```
