### ISSUE TITLE
Error detected while processing E121: Undefined variable: s:cpo_save

### ISSUE THREAD

**Issue by kabirz** [sheerun/vim-polyglot#619]
**Does this bug happen when you install plugin without vim-polyglot?**

**Describe the bug:**
latest update cause neovim startup error everytime on ubuntu 20.04
···
Error detected while processing /home/zhp/.cache/dein/.cache/init.vim/.dein/ftdetect/ftdetect.vim:
line 3606:
E121: Undefined variable: s:cpo_save
E15: Invalid expression: s:cpo_save
line 3607:
E108: No such variable: "s:cpo_save"
Press ENTER or type command to continue
···
**To Reproduce:**

**Comment by cookie-s** [comment]
I'm seeing the same error.
I could make steps to reproduce: https://gist.github.com/cookie-s/bfcee76f24e36cd49a66b0ec55f26569

In this environment, the bundled file `/root/.cache/dein/.cache/init.vim/.dein/ftdetect/ftdetect.vim` is like
```
"""
""" vim-go https://github.com/fatih/vim-go/blob/master/ftdetect/gofiletype.vim
"""

let s:cpo_save = &cpo
set cpo&vim

let &cpo = s:cpo_save
unlet s:cpo_save

"""
""" vim-polyglot https://github.com/sheerun/vim-polyglot/blob/master/ftdetect/polyglot.vim
"""

if exists("did_load_polyglot")
  finish
endif

let did_load_polyglot = 1

let s:cpo_save = &cpo
set cpo&vim

augroup filetypedetect
  runtime! filetype.vim
  runtime! ftdetect/*.vim
augroup END

let &cpo = s:cpo_save
unlet s:cpo_save
```

So I think the error flow is
1. vim-go `let s:cpo_save = &cpo`
1. vim-go `unlet s:cpo_save`
1. In vim-polyglot, `exists("did_load_polyglot")` is not 1.
1. vim-polyglot `let did_load_polyglot = 1`
1. vim-polyglot `let s:cpo_save = &cpo " vim-polyglot`
1. vim-polyglot `runtime! ftdetect/*.vim` recursively loads self. 
   1. vim-go `let s:cpo_save = &cpo`
   1. vim-go `unlet s:cpo_save`
   1. In vim-polyglot, `exists("did_load_polyglot")` is 1.
   1. vim-polyglot `finish`
1. vim-polyglot `let &cpo = s:cpo_save` **No such value!**

**Comment by sheerun** [comment]
I guess renaming this variable will help?

**Comment by DanielPower** [comment]
I'm still experiencing the issue on the latest release.
![Screen Shot 2020-11-02 at 2 39 21 PM](https://user-images.githubusercontent.com/12166320/97903244-4b523a00-1d19-11eb-8996-3356f567922c.jpg)

**Comment by DanielPower** [comment]
This seems to have been resolved for me in https://github.com/sheerun/vim-polyglot/pull/623
