### ISSUE TITLE
Undefined variable: s:cpo_save

### ISSUE THREAD

**Issue by narajaon** [sheerun/vim-polyglot#622]
**Does this bug happen when you install plugin without vim-polyglot?**
no

**Describe the bug:**
This commit
https://github.com/sheerun/vim-polyglot/commit/ff35c02445813b253b9cb76ba7fe2fabac71a01c

causes
![poly](https://user-images.githubusercontent.com/26607946/97904902-73ee2a00-1d41-11eb-8cf5-057e8d0d00ad.png)

**To Reproduce:**
NVIM v0.4.4
Update polyglot

**Comment by mckelly2833** [comment]
Same for vim 8.2

**Comment by narajaon** [comment]
Opened https://github.com/sheerun/vim-polyglot/pull/623, hope it helps

**Comment by DanielPower** [comment]
That solved the issue for me. Thanks!

**Comment by sheerun** [comment]
thank you
