### ISSUE TITLE
Macvim-specific menu items disabled

### ISSUE THREAD

**Issue by douglascook** [sheerun/vim-polyglot#624]
Macvim has various mac-specific commands added to its menus (`cmd-c` for copy etc) that are configured in [menu.vim](https://github.com/macvim-dev/macvim/blob/master/runtime/menu.vim#L78) in the macvim source. The changes in the fix for https://github.com/sheerun/vim-polyglot/issues/597 mean that these items no longer exist and lead to fun behaviour like cutting out everything you have selected when you try to copy it 😬 

I think this is related to the changes in https://github.com/sheerun/vim-polyglot/commit/518d733369fb6f2e4652e9649a78546ce6493079 and then the fix for https://github.com/sheerun/vim-polyglot/issues/597 which changes how `menu.vim` is loaded.

To reproduce:

* install macvim
* install polyglot
* open macvim from the command line and you'll get an error like the one below

```
Error detected while processing /Applications/MacVim.app/Contents/Resources/vim/runtime/menu.vim:
line 1278:
E334: Menu not found: File.New\ Window
```

**Comment by sheerun** [comment]
This is probably fixed now. If not, please comment
