### ISSUE TITLE
Terraform disappeared (just from readme?) but not in vim/vim repo

### ISSUE THREAD

**Issue by OJFord** [sheerun/vim-polyglot#625]
a96c420e14becb9be406fe9991c9e1ace868ba56 removed many languages from the readme that are in https://github.com/vim/vim/tree/master/runtime/syntax - but `terraform` is not and was also removed.

**Comment by sheerun** [comment]
The readme says "On top of all language packs from vim repository, vim-polyglot includes:"

**Comment by OJFord** [comment]
Yes, but terraform is not in that repository.

**Comment by sheerun** [comment]
It was indeed an issue. Amazing that you noticed it, thanks
