### ISSUE TITLE
Please update latest commits from baskerville/sxhkdrc

### ISSUE THREAD

**Issue by subnut** [sheerun/vim-polyglot#627]
It includes an `set cms=#%s` in the latest commit.

**Comment by subnut** [comment]
Ping @sheerun

**Comment by sheerun** [comment]
I've pushed updates yesterday

**Comment by subnut** [comment]
See, this line from upstream contains a `set cms=#%s` -
https://github.com/baskerville/vim-sxhkdrc/blob/c44f0f5fc17389ce3f909cfaaa0bc6d5418454cc/ftdetect/sxhkdrc.vim#L5

Whereas this line (your repo) does not contain it -
https://github.com/sheerun/vim-polyglot/blob/c228e993ad6a8b79db5a5a77aecfdbd8e92ea31f/ftdetect/polyglot.vim#L1897

**Comment by sheerun** [comment]
polyglot generates its own ftdetect and setting options, like `cms`, belongs to ftplugin which is imported

see for example: https://github.com/vim/vim/blob/master/runtime/syntax/fortran.vim

**Comment by subnut** [comment]
I am sorry.. I don't quite follow you .... :sweat_smile: 
I am new to vim and don't yet know about these files...

I only wanted to say this -
- even after updating vim-polyglot to the latest version, on doing `:set cms?` in a file with `ft=sxhkdrc` it returns `commentstring=/*%s*/`
- do you mean that setting `cms` is not the job of vim-polyglot? (I didn't understand you previous comment)

**Comment by sheerun** [comment]
Author needs to merge this: https://github.com/baskerville/vim-sxhkdrc/pull/3

**Comment by subnut** [comment]
@sheerun Has been merged! Please update the changes in this repo too.

Thank you very much! :smile:
