### ISSUE TITLE
Running gq on typescript files causes vim to freeze

### ISSUE THREAD

**Issue by fsouza** [sheerun/vim-polyglot#629]
This is fixed upstream: https://github.com/HerringtonDarkholme/yats.vim/pull/216

Running `make` locally fixes it, not sure if you take PRs with that though? x)

**Comment by sheerun** [comment]
Fix should now be here as well

**Comment by fsouza** [comment]
Oh, this was actually a misreport, the issue I was observing is not fixed upstream yet: https://github.com/HerringtonDarkholme/yats.vim/issues/218

The workaround is to set formatexpr to an empty string (or some other value), since the expression defined in yats.vim is just broken.

**Comment by sheerun** [comment]
this needs to be fixed upstream
