### ISSUE TITLE
Error when opening a Haskell file

### ISSUE THREAD

**Issue by samvv** [sheerun/vim-polyglot#63]
Related to issue travitch/hasksyn#10, the following error occurs when opening a Haskell file:

    Error detected while processing /Users/samvv/.vim/plugged/vim-polyglot/syntax/haskell.vim:
    line   85:
    E59: invalid character after \@
    E475: Invalid argument: hsOperator "\(\%^\#\!\)\@!\(\(\<[A-Z]\w*\)\@64<=\.\)\@!\(--\+\([^.%\~\&\*/\$\^|@:+<!>=#!\?]\|$\)\)\@![-.%\~\&\*/\$\^|@:+<!>=#!\?]\+"

Maybe time to switch to another syntax highlighter?

**Comment by sheerun** [comment]
Please suggest some :) Preferably only syntax + indentation

**Comment by samvv** [comment]
Hmm ... as far as I can tell [haskell-vim](https://github.com/raichoo/haskell-vim) looks like the best alternative.
