### ISSUE TITLE
Autocmds listed when saving F# (fsharp) file

### ISSUE THREAD

**Issue by drk-mtr** [sheerun/vim-polyglot#634]
Thanks for the great software!

**Does this bug happen when you install plugin without vim-polyglot?** Not sure.

**Describe the bug:**

When I save an fsharp file, I see the following:

```
filetypedetect  BufReadPost
    *.fs      call polyglot#detect#Fs()
    *.fs      call polyglot#detect#Fs()
    *.fs      call polyglot#detect#Fs()
filetypedetect  BufNewFile
    *.fs      call polyglot#detect#Fs()
    *.fs      call polyglot#detect#Fs()
    *.fs      call polyglot#detect#Fs()
```

**To Reproduce:**

- Neovim 0.5.0
- Open an F# file and save
- Commit `d221139` shows this error, `94ec9c3` doesn't

**Comment by sheerun** [comment]
I cannot reproduce on newest vim-polyglot, could you check again?
