### ISSUE TITLE
g:polyglot_is_disabled gets overwritten in ftdetect/polyglot.vim

### ISSUE THREAD

**Issue by pjio** [sheerun/vim-polyglot#637]
**Does this bug happen when you install plugin without vim-polyglot?**
No

**Describe the bug:**
`g:polyglot_is_disabled` gets overwritten in `ftdetect/polyglot.vim` (See PR)

**To Reproduce:**
Set in your `init.vim` or `vimrc`
```
set noincsearch
let g:polyglot_is_disabled = {'sensible': 1}
```
Then load any file and `incsearch` was enabled

**Pull Request**
https://github.com/sheerun/vim-polyglot/pull/636

**Comment by magras** [comment]
I think `polyglot_is_disabled` is not intended to be set by a user. Readme recommends using [`polyglot_disabled`](https://github.com/sheerun/vim-polyglot#default-settings) instead.

**Comment by pjio** [comment]
You're right, I closed the PR. I will open a new one to discuss if setting `noincsearch` is really necessary or an out-of-scope change.
