### ISSUE TITLE
Commit bb3de8fa5e509d5f5faf173fd1a92635a0023274 breaks html script indent

### ISSUE THREAD

**Issue by jacobmischka** [sheerun/vim-polyglot#643]
**Does this bug happen when you install plugin without vim-polyglot?**

N/A

**Describe the bug:**

Script tag indentation is broken.

**To Reproduce:**

Update to a commit after bb3de8fa5e509d5f5faf173fd1a92635a0023274 (including the most recent commit in master), attempt editing JavaScript in a `<script>` tag

bb3de8fa5e509d5f5faf173fd1a92635a0023274:
![broken](https://user-images.githubusercontent.com/3939997/100942199-84b8c980-34c0-11eb-98df-5114869c685f.gif)

b3763a917a6a3ca85ae51086fc8d29b28f66fc88: (Highlighting is broken in the commit, but indentation works)
![broken differently](https://user-images.githubusercontent.com/3939997/100942246-9a2df380-34c0-11eb-979a-ede188261b87.gif)

As a workaround, I'm currently using 5bd9f16476dbefc44ad23df08268d66bb938107f, which has working indentation and highlighting for my uses.

I'm using neovim v0.4.4.

**Comment by kbwo** [comment]
I'm facing with same issue using vim v8.2 and neovim v0.5.0

**Comment by sheerun** [comment]
This seems to be issue with pangloss/vim-javascript, not vim-polyglot. I'll move this issue there

**Comment by sheerun** [comment]
Please let me know if you'll find workaround, then I can maybe patch it here https://github.com/pangloss/vim-javascript/issues/1226

**Comment by jacobmischka** [comment]
After forgetting about this for a while, I just updated vim-polyglot and it seems to be fine now. So whatever the issue was, it looks to be fixed.

**Comment by jacobmischka** [comment]
Ah sorry, it's actually still an issue, I was mistaken.
