### ISSUE TITLE
Invalid  expression: submenu_items->has_key(bufnum)

### ISSUE THREAD

**Issue by vfbiby** [sheerun/vim-polyglot#646]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/5847699/101569059-b674e780-3a0e-11eb-822b-4399a452d52c.png">

**Does this bug happen when you install plugin without vim-polyglot?**
no
**Describe the bug:**
when use vim-polyglot in vimR, the problem will happen
**To Reproduce:**

**Comment by sheerun** [comment]
I can't reproduce this with latest SNAPSHOT-20201224.200216 vimR. Please comment with steps to reproduce if this still happens
