### ISSUE TITLE
TypeScript JSDoc / DocBlock comment continuation indent broken

### ISSUE THREAD

**Issue by jchook** [sheerun/vim-polyglot#647]
**Does this bug happen when you install plugin without vim-polyglot?**

No.

**Describe the bug:**

When continuing JSDoc comments to the next line with only [yats](https://github.com/HerringtonDarkholme/yats.vim) installed, I see the correct behavior:

![Peek 2020-12-12 12-54 vim with yats](https://user-images.githubusercontent.com/193530/101991221-38684900-3c79-11eb-9c44-daa1c61516b6.gif)

However when I have polyglot installed, I see this strange JSDoc indent behavior:

![Peek 2020-12-12 12-53 vim with polyglot](https://user-images.githubusercontent.com/193530/101991224-3c946680-3c79-11eb-8057-a57ca7b3c262.gif)

**To Reproduce:**

This configuration works:

```vimscript
call plug#begin()
Plug 'HerringtonDarkholme/yats.vim'
call plug#end()
set nocompatible
set number
```

This configuration exhibits the JSDoc indent bug (note I tried with autoindent and sensible enabled/disabled):

```vimscript
call plug#begin()
Plug 'sheerun/vim-polyglot'
call plug#end()
let g:polyglot_disabled = ['autoindent', 'sensible']
set nocompatible
set number
```

**Comment by brainkim** [comment]
I started noticing this, thanks for making me feel not insane. It seems like `gq` formatting for comments is also broken. Using yats.vim instead fixes the issue.

**Comment by jchook** [comment]
I tried profiling but so far I'm too much of a vim n00b to decipher the output.

**Comment by juneidysoo** [comment]
FWIW, I found the last commit that worked was `05e21a9e252b283b2d71568ad3b671d7f28fe0bc`.

Hope it helps.

**Comment by sheerun** [comment]
I can't reproduce this with latest update, please comment if you still experience it

**Comment by jchook** [comment]
@sheerun thanks! Works for me now.
