### ISSUE TITLE
Indentation doesn't work for Crystal

### ISSUE THREAD

**Issue by KevinSjoberg** [sheerun/vim-polyglot#651]
**Does this bug happen when you install plugin without vim-polyglot?**

No.

**Describe the bug:**

The indentation for Crystal doesn't work. Let's look at an example:

```crystal
class Whatever
  end
```

I'd expect `end` to automatically being indented as it's being typed, but it doesn't. For comparison, do the the same thing in Ruby.

**To Reproduce:**

Open a file and set the filetype to `crystal`. Type the following:

```crystal
class Whatever
  end
```

**Comment by KevinSjoberg** [comment]
I've debugged this a bit further and it looks like the `indentexpr` for Crystal is expecting some variables to be set in order to work. For instance, running `:call GetCrystalIndent(v:lnum)` generates the following error:

```console
Error detected while processing function GetCrystalIndent[20]..crystal#indent#DeindentingKeyword:                                                                                                                                                                                                                                                                         
line   41:                                                                                                                                                                                                                                                                                                                                                                
E121: Undefined variable: g:crystal_indent_block_style  
````

Looking at the [vim-crystal](https://github.com/vim-crystal/vim-crystal) plugin, it looks like they [bootstrap](https://github.com/vim-crystal/vim-crystal/blob/bc4f115de69fdeb4419e2cbef1981f0b39c6d972/plugin/crystal.vim#L22-L30) variables with default values.

I'd be happy to submit a pull request, but not sure where to place the bootstrapping code, given we don't want to put things in the `plugin/` directory.

**Comment by KevinSjoberg** [comment]
I've submitted a pull request to vim-crystal to move the indentation settings to `indent/crystal.vim` instead.

See https://github.com/vim-crystal/vim-crystal/pull/109/files.

**Comment by KevinSjoberg** [comment]
Looks like https://github.com/vim-crystal/vim-crystal/pull/109 got accepted. Could we get this update into polyglot? 🙂

**Comment by sheerun** [comment]
Thank you for debugging this! Crystal has been updated here as well
