### ISSUE TITLE
Is -depth in the makefile suposed to be -maxdepth

### ISSUE THREAD

**Issue by NICHTJ3** [sheerun/vim-polyglot#652]
**Does this bug happen when you install plugin without vim-polyglot?**
The bug is to do with the dev script in the makefile not polygot itself

**Describe the bug:** 
run the find command shown in the make file it returns nothing.

**To Reproduce:** 
run the find command shown in the make file it returns nothing. And now run it with -maxdepth instead

**Comment by sheerun** [comment]
I guess so, thank you
