### ISSUE TITLE
Tabstop is set to 8 for javascript files (.js, .es6)

### ISSUE THREAD

**Issue by tchar** [sheerun/vim-polyglot#654]
**Does this bug happen when you install plugin without vim-polyglot?**

No

**Describe the bug:**

In vim for js files (also es6, did not try all of them) tabstop is forced to 8.

I also tried setting  `let g:polyglot_disabled = ['javascript']` before the plugin loads and it still forces my tabstop to 8.
If the polyglot_disabled option works for javascript this means that tabstop is forced by polyglot.

According to [this](https://github.com/pangloss/vim-javascript/issues/468) they don't force any tabstop so it should be from `polyglot`
With .py files tabstop is forced to 4 (not set) (which is expected).

**To Reproduce:**

In case you need it
```
Vim version: version 8.1.2269
OS: Ubuntu 20.04
```

Here is the .vimrc that can reprodue the issue
```
set nocompatible
set tabstop=4

" The following line does not resolve the issue so I commented it out
"let g:polyglot_disabled = ['javascript']

call plug#begin('~/.vim/plugged')

Plug 'sheerun/vim-polyglot'
"Plug 'pangloss/vim-javascript'

call plug#end()
```

Swaping the plugins issue is no more and tabstop is back to 4

**Comment by yujinyuz** [comment]
As far as I know, vim-polyglot uses vim-sleuth and it might be the case here. I also saw this in vim-sleuth's doc https://github.com/tpope/vim-sleuth#notes

> If your file is consistently indented with hard tabs, 'shiftwidth' will be set to your 'tabstop'. Otherwise, a 'tabstop' of 8 is enforced.

**Comment by tchar** [comment]
Looks like I had to set softtabstop/shiftwidth to make it work. Thanks for the suggestion.

**Comment by sheerun** [comment]
It can't have something to do with vim-polyglot because I've stopped changing setting tabstop long time ago. It's only sleuth that does that, not vim-polyglot's implementation of it. If you encounter this issue again, please attach file you are editing, and result of `:verbose set sw ts`, thank you!

**Comment by sheerun** [comment]
I've added change that automatically sets shiftwidth to tabstop if not set
