### ISSUE TITLE
How to disable filetype detection?

### ISSUE THREAD

**Issue by subnut** [sheerun/vim-polyglot#657]
I want to use vim-polyglot minus the filetype detection ability.. Is it possible?

I mean, I want to keep the ftplugins, syntax files, etc.. but don't want to use the filetype detection algorithm of vim-polyglot.
How to do that?

**Comment by sheerun** [comment]
I've committed change that allows you to disable it with `let g:polyglot_disabled = ['ftdetect']` at the top of .vimrc
