### ISSUE TITLE
I'd like to try out different C++ support plugins working with polyglot

### ISSUE THREAD

**Issue by Tafnab** [sheerun/vim-polyglot#658]
I like the all-in-one support of polyglot, but I'd like to try vim_cpp_modern, and possibly a few other things, only for C/C++, not for any of the other languages.

My options are to:
A) Edit polyglot somehow
B) Don't load polyglot
C) Try to clobber polyglot by loading the other syntax checker after polyglot
D) The authors of polyglot already have an elegant solution.

I'm hoping for D), but I haven't been able to find anyone addressing this issue. What do you suggest?

**Comment by sheerun** [comment]
You can just install these packages directly

**Comment by sheerun** [comment]
Also you can disable some vim-polyglot packages by using `polyglot_disabled`, as described in the README

**Comment by Tafnab** [comment]
> Also you can disable some vim-polyglot packages by using `polyglot_disabled`, as described in the README

Thanks.
