### ISSUE TITLE
Disable indentexpr

### ISSUE THREAD

**Issue by laktak** [sheerun/vim-polyglot#662]
I noticed that vim started indenting my code after I press `}` while editing a `.js` file.

I've set
```
let g:polyglot_disabled = ['autoindent']
```

But `:verbose setlocal indentexpr?` still says:

```
  indentexpr=GetJavascriptGraphQLIndent()
        Last set from ~/.vim/plugged/vim-polyglot/after/indent/javascript-2.vim line 37
```

It also sets `identkeys`.

I've found a workaround - not sure if this is the best option:
```
autocmd BufEnter * set indentexpr=
```

**Comment by sheerun** [comment]
Auto indent feature is not related to your issue. Does it happen when you
use only polyglot? Maybe some other plugin is interfering

**Comment by laktak** [comment]
I don't have the issue when I remove polyglot but it happens when I remove all other plugins.

I'm using `vim-plug` and noticed that it contains
```
  filetype plugin indent on
```

Which I disable after loading the plugins:
```
call plug#end()
filetype indent off  " enabled by vim-plug
```

But even if I change the code in vim-plug to `filetype plugin indent off` the issue remains.

**Comment by sheerun** [comment]
I can't reproduce, you'd need to show me whole vimrc and vim version you are using. I've updated all packages, maybe it works now?

**Comment by laktak** [comment]
I've reduced it down to this.

`~/.vimrc` without polyglot:
```
call plug#begin('~/.vim/plugged')
call plug#end()
filetype indent off
```

`:verbose setlocal indentexpr?` says:
```
  indentexpr=
```

Notice that if I don't do `filetype indent off` it would point to a vim function:
```
  indentexpr=GetJavascriptIndent()
        Last set from /usr/share/vim/vim82/indent/javascript.vim line 14
```


`~/.vimrc` with polyglot:
```
call plug#begin('~/.vim/plugged')
Plug 'sheerun/vim-polyglot'
call plug#end()
filetype indent off
```

`:verbose setlocal indentexpr?` says:
```
  indentexpr=GetJavascriptGraphQLIndent()
        Last set from ~/.vim/plugged/vim-polyglot/after/indent/javascript-2.vim line 37
```

But `identexpr` should not be set.

**Comment by sheerun** [comment]
indentexpr is expected to be set by vim-polyglot, you can unset it with autocommand like `au Filetype javascript set indentexpr=`

**Comment by laktak** [comment]
OK, I did not know that. I assumed that `filetype indent off` would turn it off just like it does for vim.

I tried `au Filetype javascript set indentexpr=` but this does not work for me:

```
call plug#begin('~/.vim/plugged')
Plug 'sheerun/vim-polyglot'
call plug#end()
filetype indent off  " enabled by vim-plug
au Filetype javascript set indentexpr=
```

Would it be possible to have someting like `let g:polyglot_disabled = ['indentexpr']`?

**Comment by sheerun** [comment]
Unfortunately not, this is not something to disable. It's best if I fixed this issue but I cannot reproduce. Could you send screencast or something that shows it? e.g. https://asciinema.org/

**Comment by laktak** [comment]
OK, I thought the minimal vimrc would be reproducible. I'll try to upload a small video later.

My VIM Version:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 14 2021 18:17:04)
Included patches: 1-2347

(latests version of the plugin, vim-plug and the OS; Arch)

**Comment by laktak** [comment]
Does this help? https://asciinema.org/a/4RKZlg2unpPIzRaxKVuF7yp2D
