### ISSUE TITLE
filetype in empty buffer changes to conf

### ISSUE THREAD

**Issue by aphiliplinell** [sheerun/vim-polyglot#663]
**Does this bug happen when you install plugin without vim-polyglot?**

The bug disappears when I uninstall vim-polyglot.

**Describe the bug:**

I've got an issue similar to #656.

When opening an empty buffer and changing the filetype the setting does not persist, and changes back to `filetype=conf`.

I've encountered the issue on `7bde552a463999897320a1899a6ca4f8806041ea` which as of this writing is the latest commit.

**To reproduce**

1. Open an empty buffer in vim, write a simple header

```
# hello
```

2. Check filetype

```
:set filetype?
```

Returns `filetype=conf`

3. Change filetype to markdown

```
:set filetype=markdown
```

Notice the filetype changes but will change back again (colorscheme flickers from markdown back to conf)

4. Check filetype

```
:set filetype?
```

Returns `filetype=conf`

Expects filetype to be `markdown` not `conf`.

## Other info

If I checkout `c228e993ad6a8b79db5a5a77aecfdbd8e92ea31f` (cd into `$HOME/.vim/plugged/vim-polyglot `and `git checkout c228e993ad6a8b79db5a5a77aecfdbd8e92ea31f` which might require an `git fetch --unshallow` first) the issue disappears.

The commit c228e993ad6a8b79db5a5a77aecfdbd8e92ea31f is taken rather arbitrarily. I got it from a friend who did not observe the same behavior and had an older version of vim-polyglot. The issue might therefore have been introduced later.

**Comment by sheerun** [comment]
Thank you for reporting this. Polyglot should no longer change filetype once it's set
