### ISSUE TITLE
Bug when using NVIM, appears related to f3b646fd6f6070072d9b4ec958815b74a8a333f2(#613)

### ISSUE THREAD

**Issue by CorbanR** [sheerun/vim-polyglot#664]
**Does this bug happen when you install plugin without vim-polyglot?**
This appears to be a bug with vim-polyglot, and not one of the plugins it uses.
**Describe the bug:**
```
commit 05b8bbc938bdeac4a5ee2d3ae5cf7a7f05e822d3
Author: Adam Stankiewicz <sheerun@sher.pl>
Date:   Fri Jan 1 22:30:41 2021 +0100

    Fix loading for vim 8 packages, closes #613
```
Appears to cause issues when loading `vim-polyglot` with nvim
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld1

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
``

Specifically the error is 
```
Error detected while processing /Users/<user>/.local/share/nvim/plugged/vim-polyglot/ftdetect/polyglot.vim:
line    1:
E117: Unknown function: polyglot#init#init
```
This happens when any file is loaded. If I checkout commit `f3b646fd6f6070072d9b4ec958815b74a8a333f2` the commit prior to `05b8bbc938bdeac4a5ee2d3ae5cf7a7f05e822d3`, `vim-polyglot` loads as expected.

**To Reproduce:**
Install `vim-polyglot` with `nvim`, via `vim-plug` and open a file.

**Comment by sheerun** [comment]
Everything works for me. If you still experience this issue, please create another issue with steps to reproduce (i.e. nvim version, package manager, and minimal init.vim that reproduces error)
