### ISSUE TITLE
Init error on vim 7.4 

### ISSUE THREAD

**Issue by ied206** [sheerun/vim-polyglot#665]
**Does this bug happen when you install plugin without vim-polyglot?**
No, the bug happens when vim-polyglot inits.

**Describe the bug:**
When I load the latest plugin (downloaded on 2021-01-25 / 2021-01-26) on vim 7.4.1099, the plugin fails with an error.
```
Error detected while processing function <SNR>12_process_rtp:
line   22:
E117: Unknown function: i:len
E15: Invalid expression: rtp[i:len(rtp)-1]
line   32:
E117: Unknown function: i:len
E15: Invalid expression: rtp[i:len(rtp)-1]
Press ENTER or type command to continue
```

The function [process_rtp](https://github.com/sheerun/vim-polyglot/blob/05b8bbc938bdeac4a5ee2d3ae5cf7a7f05e822d3/autoload/polyglot/init.vim#L3585) was introduced in commit 05b8bbc938bdeac4a5ee2d3ae5cf7a7f05e822d3.

**To Reproduce:**
Install latest vim-polyglot (master or v4.17.0) with vim-plug on CentOS 7 (vim 7.4.1099).
It can be also reproduced on CentOS 6 (7.4.629), and doesn't happen on v4.16.0.

**Comment by Nox-404** [comment]
Got the same problem:
```
vim-polyglot: v4.17.0
vim: 7.4.326-16.1
SLES 12 SP3
```

**Comment by meister** [comment]
Can also confirm this issue (although on a perhaps a bit unconventional Synology NAS system):
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  7 2020 08:05:30)
Included patches: 1-888
Compiled by Synology Inc.
```

`vim-polyglot@v4.17.0`: produced the exact error as the reporter had
After doing
```
~/.vim/bundle/vim-polyglot$ git switch -c v4.16.0
```
the issue disappeared.

**Comment by ied206** [comment]
The issue was solved in the latest master, thanks!
