### ISSUE TITLE
Support for g:filetype_m broken

### ISSUE THREAD

**Issue by jrwrigh** [sheerun/vim-polyglot#668]
**Does this bug happen when you install plugin without vim-polyglot?**
N/A, this is about heuristics (be it vim's or polyglot's)

**Describe the bug:**
In #498, you stated that polyglot would respect the `let g:filetype_m = 'FILETYPE'`. However, that appears to be broken now as setting `let g:filetype_m = 'matlab'` and opening an `*.m` file sets the filetype to Octave now.

**To Reproduce:**
Add `let g:filetype_m = 'matlab'` to vimrc/init.vim and open a matlab file. 

This would not be an issue for me (Octave is explicitly designed to be syntax compatible with Matlab), except for the octave plugin does not set the `commentstring` variable (which I'm working on getting [fixed in the Octave plugin](https://github.com/McSinyx/vim-octave/issues/2)). Thus, I'm more curious if the `g:filetype_m` functionality will be respected in the future with polglot's heuristics.

**Comment by sheerun** [comment]
It should be fixed now
