### ISSUE TITLE
anyway to do post adjustment?

### ISSUE THREAD

**Issue by ri-aje** [sheerun/vim-polyglot#669]
hi, I like polyglot and thanks for this great plugin. most of things work fine, but there are a few settings that I would like to set manually. for example, I would like to clear the sign and fold columns. I have `highlight clear FoldColumn/SignColumn` in my vimrc, but they don't seem working with polyglot. when I check where they are last set, vim reports it set [here](https://github.com/ri-aje/vim-polyglot/blob/8f0971d54b8fd780f05f0f93ca5e875515597542/plugin/polyglot.vim#L94), e.g.
```vim
:Verbose highlight FoldColumn
FoldColumn     xxx term=standout ctermfg=4 ctermbg=7 guifg=DarkBlue guibg=Grey
	Last set from ~/.vim/bundle/vim-polyglot/plugin/polyglot.vim line 94
```
if I issue the clear command inside vim, then it works. so it looks like its effect is overwritten by polyglot when the plugin loads (which I presume comes after parsing my vimrc?). is there anyway to add post-polyglot settings? I am thinking to inject my sign/fold column colors there. I checked out git repo readme and the issue history here but cannot seem to find anything. thanks.

**Comment by sheerun** [comment]
You can use autocommands, for example `au FileType javascript highlight clear FoldColumn/SignColumn` or `au BufEnter * highlight clear FoldColumn/SignColumn`
