### ISSUE TITLE
racket scheme filetype collision

### ISSUE THREAD

**Issue by zdszero** [sheerun/vim-polyglot#670]
When edting files with suffix .rkt, polygot recognize its filetype as scheme, which I think should be racket. I looked into the code and found the following code.

```
if !has_key(g:polyglot_is_disabled, 'scheme')
  au BufNewFile,BufRead *.rkt,*.scm,*.ss setf scheme
endif
if !has_key(g:polyglot_is_disabled, 'racket')
  au BufNewFile,BufRead *.rkt,*.rktd,*.rktl,*.scrbl setf racket
endif
```
*.rkt is used in both case

**Comment by cwfoo** [comment]
Possible solution:

```diff
diff --git a/autoload/polyglot/init.vim b/autoload/polyglot/init.vim
index 837515ee..3ec992d4 100644
--- a/autoload/polyglot/init.vim
+++ b/autoload/polyglot/init.vim
@@ -603,7 +603,11 @@ if !has_key(g:polyglot_is_disabled, 'screen')
 endif
 
 if !has_key(g:polyglot_is_disabled, 'scheme')
-  au BufNewFile,BufRead *.rkt,*.scm,*.ss setf scheme
+  if has_key(g:polyglot_is_disabled, 'racket')
+    au BufNewFile,BufRead *.rkt,*.scm,*.ss setf scheme
+  else
+    au BufNewFile,BufRead *.scm,*.ss setf scheme
+  endif
 endif
 
 if !has_key(g:polyglot_is_disabled, 'catalog')
```
---

Note to self — the lines mentioned by the OP are:

https://github.com/sheerun/vim-polyglot/blob/4c10562d2cc9b084518284c49a158558da5180a7/autoload/polyglot/init.vim#L605-L607
https://github.com/sheerun/vim-polyglot/blob/4c10562d2cc9b084518284c49a158558da5180a7/autoload/polyglot/init.vim#L2036-L2038

**Comment by cwfoo** [comment]
@zdszero Why did you close the issue? The problem has not been fixed.
