### ISSUE TITLE
open .vue file very slow.

### ISSUE THREAD

**Issue by seaweedman** [sheerun/vim-polyglot#671]
First, it's perfect in most file, but when I open a `.vue` file, whatever the file's size, it's used about 5s, `gg` or `G` also await a long time.

**Comment by Niekto350** [comment]
I can confirm this, here is an excerpt of the startup profile:
```
===================================================================================
1       2803.624   vim-polyglot
2        23.992   coc.nvim
```
I'm using https://github.com/sheerun/vim-polyglot to load the plugin (https://github.com/posva/vim-vue)

Setting this `let g:polyglot_disabled = ['vue']` in my vimrc resulted in:
```
===================================================================================
1       180.453   vim-polyglot
2        27.794   coc.nvim
```
The syntax highlighting of the file still works. Not sure if it's a problem with polyglot plugin (which basically just loads the vim-vue plugin) or vim-vue plugin itself.

Originally it was extremely slow, not just the startup but scrolling, typing etc as well. Now it's much more usable but still not perfect. I've posted this comment into threads for both repos.

**Comment by sheerun** [comment]
If this issue still happens, please post another issue that compares load times for vim-polyglot and posva/vim-vue loaded as standalone package
