### ISSUE TITLE
html highlight with i tags  on vue files not detect closed tag.

### ISSUE THREAD

**Issue by zodman** [sheerun/vim-polyglot#678]
**Does this bug happen when you install plugin without vim-polyglot?**
No

**Describe the bug:**

On vue filetype when you work with `<i />` the highlight does not detect the node will not need a tag close

**To Reproduce:**

![image](https://user-images.githubusercontent.com/44167/109193610-2c5f3400-775e-11eb-9529-bf819acf7afa.png)

**Comment by sheerun** [comment]
this seems to be working now
