### ISSUE TITLE
yajs isn't build correctly

### ISSUE THREAD

**Issue by edwardsmit** [sheerun/vim-polyglot#68]
When I look for instance at syntax/yajs/dom-event.vim it's contents is:
{ [Error: ENOENT, no such file or directory 'dom-event.yml']
  errno: -2,
  code: 'ENOENT',
  path: 'dom-event.yml',
  syscall: 'open' }

This doesn't look right, isn't the contents at https://github.com/othree/yajs.vim/blob/master/syntax/yajs/dom-event.vim and will throw errors at me when I'm opening a new file.

**Comment by ldong** [comment]
This is happening to me as well, when I `vim a.html`

**Comment by edwardsmit** [comment]
I disabled javascript within polyglot ```let g:polyglot_disabled = ['javascript']``` and install the ```othree/yajs.vim``` separately. No more problems ever since.
vim-polyglot uses a buidl script that I think is failing. But I'm afraid nobody is actively maintaining this repo, as I've had no response from anyone for over a month.

**Comment by sheerun** [comment]
Sorry guys for late reaction.. I've updated my yajs fork so it plays nicely with original yajs. I've also updated vim-polyglot, so v2.2.1 should work for you.

**Comment by othree** [comment]
Since sheerun/vim-polyglot#68 is closed. I think I don't need to do any change?

**Comment by sheerun** [comment]
It's probably ok now
