### ISSUE TITLE
ansible not detected

### ISSUE THREAD

**Issue by mosheavni** [sheerun/vim-polyglot#680]
**Does this bug happen when you install plugin without vim-polyglot?**
No

**Describe the bug:**
When opening an ansible file, the file is recognized as `yaml`, and soon I'm getting language-server related errors:
![image](https://user-images.githubusercontent.com/17252601/109795423-93c62980-7c1f-11eb-9d1e-d22866518654.png)

When installing the plugin directly:
```
Plug 'pearofducks/ansible-vim'
```
It's recognized correctly as `yaml.ansible` and yields no errors.

**To Reproduce:**
1. Create ansible dir structure, and task file:
```
mkdir -p ansible/roles/test/tasks
```

2. Create a simple task:
```
echo -e '- name: something\n  script: ls -l' > ansible/roles/test/tasks/main.yml
```

3. Open vim and check filetype:
```
vim ansible/roles/test/tasks/main.yml
:set filetype?
```
If it's `yaml`, ftdetect didn't work as expected.

**Comment by sheerun** [comment]
This is probably fixed as now it sets filetype to ansible.yaml

**Comment by danihodovic** [comment]
I can still reproduce this error.
