### ISSUE TITLE
Indententation detection does not detect indentation for python files correctly

### ISSUE THREAD

**Issue by adityasule** [sheerun/vim-polyglot#681]
**Does this bug happen when you install plugin without vim-polyglot?**
I believe the base plugin for this is `tpope/vim-sleuth` and this behaves correctly.

**Describe the bug:**
While editing a python3 file indented with 2 spaces, the automatic indentation detection detects 4 spaces.

**To Reproduce:**

Take this python file

```python3
"""
Foo
"""

def fact(n):
  if n == 0:
    return 1
  else:
    return n * fact(n - 1)    

def foo():
  v = fact(10)
  print(v)

foo()
```

When opened with vim and tested with `:set tabstop?`, vim prints `4` instead of `2`.

<img width="961" alt="image" src="https://user-images.githubusercontent.com/8867752/109860166-18d03380-7c5e-11eb-8b23-dbc50a1a557c.png">

**Comment by sheerun** [comment]
Nothing is detected by design: ftplugin/python.vim of native vim runtime files sets tabstop manually: https://github.com/vim/vim/blob/e3f50ad640fb30f27027f85a616280288bbc14ca/runtime/ftplugin/python.vim#L119
