### ISSUE TITLE
Filetype incorrectly set to "scheme" for Racket files

### ISSUE THREAD

**Issue by cwfoo** [sheerun/vim-polyglot#683]
**Does this bug happen when you install plugin without vim-polyglot?**

The problem is in vim-polyglot itself.

**Describe the bug:**

When a Racket file is opened, the filetype is set to `scheme`. The filetype should be `racket` instead.

(This issue is exactly the same as #670, but that issue was closed by its author even though the bug has not been fixed).

**To Reproduce:**

1. Open a new racket file: `vim myprogram.rkt`.
2. Observe that the filetype is incorrectly set to `scheme`.

**Comment by sheerun** [comment]
This is fixed now
