### ISSUE TITLE
vim-polyglot disables custom ftdetect hooks

### ISSUE THREAD

**Issue by onsails** [sheerun/vim-polyglot#684]
**Does this bug happen when you install plugin without vim-polyglot?**
no

**Describe the bug:**
when vim-polyglot is enabled, all custom files inside ftdetect dir are ignored.

**To Reproduce:**
create `ftdetect/myext.vim` with
```vim
au! BufRead,BufNewFile *.myext    set filetype=mytype
```
create `ftplugin/mytype.vim` with
```vim
if exists("b:did_ftplugin")
  finish
endif
let b:did_ftplugin = 1

setlocal shiftwidth=2 softtabstop=2 expandtab smartindent

" https://vi.stackexchange.com/questions/16470/setting-syntax-in-ftplugin
augroup pdeSyntax
   au!
   autocmd Syntax          <buffer> call SetPdeSyntax()
augroup END
function! SetPdeSyntax()
   " remove the augroup
   au! pdeSyntax
   set syntax=cpp
endfunction
```

and enable vim-polyglot as stated in readme.
mytype won't be highlighted with cpp syntax. Without vim-polyglot it works.

**Comment by sheerun** [comment]
I tried this exact setup and it works. If this still hapens for you, please open another issue with more details how to reproduce (vim/nvim, its version, package manager you are using, minimal .vimrc, and other files that are relevant)
