### ISSUE TITLE
No option to disable tab detection

### ISSUE THREAD

**Issue by ElArtista** [sheerun/vim-polyglot#688]
Currently polyglot counts spaces and tabs and turns on et/noet accordingly here:
https://github.com/sheerun/vim-polyglot/blob/cc63193ce82c1e7b9ee2ad7d0ddd14e8394211ef/autoload/polyglot/init.vim#L2890

Can we provide a configuration option to disable this?

**Comment by ElArtista** [comment]
Bump

**Comment by sheerun** [comment]
You can disable indent detection by `let g:polyglot_disabled = ['autoindent']`

**Comment by ElArtista** [comment]
This is not about disabling the whole `autoindent` functionality, its about disabling this 'smart tab/spaces detection' indicated above and respecting the user's 'et/noet' configuration
