### ISSUE TITLE
BufWritePost Autocommands load /ftplugin/

### ISSUE THREAD

**Issue by squm** [sheerun/vim-polyglot#689]
hello, I have this function which calls `update`, as I figure from this error message it triggers chain of autocommands which lead back to recursive reloading of my updating function, which is an error

**Does this bug happen when you install plugin without vim-polyglot?**

**Describe the bug:**

**To Reproduce:**

> Error detected while processing function <SNR>55_SyntaxCheck[5]..BufWritePost Autocommands for "*.h"..function polyglot#detect#H[19]..FileType Autocommands for "*"..function <SNR>10_LoadFTPlugin[17]..script /usr/local/Cellar/macvim/8.2-169_2/MacVim.app/Contents/Resources/vim/runtime/ftplugin/cpp.vim[12]../.vim/ftplugin/c.vim:
> 
> E127: Cannot redefine function <SNR>55_SyntaxCheck: It is in use
> Press ENTER or type command to continue

**Comment by sheerun** [comment]
I don't get any errors when using following vimrc and vim:

```
call plug#begin()

Plug 'sheerun/vim-polyglot'

call plug#end()
```

Could you explain how to reproduce this error? What is the minimal vimrc that reproduces this error?

**Comment by squm** [comment]
glad you tested with empty vimrc, but I don't have empty vimrc

> Could you explain how to reproduce this error? What is the minimal vimrc that reproduces this error?
I will not debug error anymore than already did

**Comment by sheerun** [comment]
Unfortunately I cannot reproduce
