### ISSUE TITLE
jsonc `&comments` setting gets reset

### ISSUE THREAD

**Issue by infokiller** [sheerun/vim-polyglot#690]
**Describe the bug:**

When vim-polyglot is enabled, `&comments` is reset to an empty string

**To Reproduce:**

Set `&comments` for jsonc, open jsonc file, use `echo &comments`.

**Comment by sheerun** [comment]
Seems to work for me. If this still happens for you, please provide more details instructions to reproduce. Here's the .vimrc to use:

```
call plug#begin()

Plug 'sheerun/vim-polyglot'

call plug#end()
```
