### ISSUE TITLE
JSX syntax not working properly

### ISSUE THREAD

**Issue by masylum** [sheerun/vim-polyglot#696]
**Does this bug happen when you install plugin without vim-polyglot?**
No

**Describe the bug:**
Since commit a81756029291d6e21295687515a3e58499c19b33, files that end in `jsx` do not get proper highlighting.

**To Reproduce:**

`git checkout a81756029291d6e21295687515a3e58499c19b33`
![image](https://user-images.githubusercontent.com/28248/112753336-7c3c4f80-8fd7-11eb-84f2-26375432bb77.png)

`git checkout fb7cf8a9ab782d67db5aa71bffac67e63fcc0c4c`
![image](https://user-images.githubusercontent.com/28248/112753377-ac83ee00-8fd7-11eb-8611-b616583149fe.png)

Notice that the first detects `javascriptreact` while the later detects `javascript`.

**Comment by sheerun** [comment]
Could you paste contents of example file? Does it happen if you update polyglot?
