### ISSUE TITLE
Pull request Nim syntax to vim/vim

### ISSUE THREAD

**Issue by 89z** [sheerun/vim-polyglot#698]
Currently Vim does not have Nim syntax:

https://github.com/vim/vim/tree/f6bdd82c/runtime/syntax

I raised the issue with the Vim developers, and they say a maintainer from this repo needs to make a pull request on the Vim repo, before any change can be made.

Would the maintainers here be interested in doing that?

**Comment by sheerun** [comment]
Why you won't do it?

**Comment by 89z** [comment]
I have tried it before. Here is what happens:

~~~
me: does pull request
them: are you the author?
me: no
them: *closes pull request*
~~~

its such a dumb system, but its the system.

**Comment by sheerun** [comment]
we are not the authors of nim plugin as well, you need to ping https://github.com/zah/nim.vim
