### ISSUE TITLE
polyglot does not work well with Ubuntu 20.04

### ISSUE THREAD

**Issue by KihongHeo** [sheerun/vim-polyglot#704]
Hi.

I moved my vim setting from Ubuntu 18.04 to 20.04. But syntax highlighting suddenly does not work properly.
Here is a source file in 18.04.
![스크린샷 2021-04-21 오후 7 33 11](https://user-images.githubusercontent.com/1281633/115541317-f3fd5180-a2d9-11eb-8d6a-a2e3f03899b9.png)

The following is the same file but looks different in 20.04.
![스크린샷 2021-04-21 오후 7 32 58](https://user-images.githubusercontent.com/1281633/115541439-14c5a700-a2da-11eb-8e2d-33aeeadedd9a.png)

Could you give some idea or suggestion?

[UPDATE] If I directly copy `.vim` from 18.04 to 20.04 then it works. But it does not work if I install it using `plug`.

**Comment by cwfoo** [comment]
1. What is the version of Vim you are using?

2. Look for differences in syntax highlight groups where the colors are different. You can do this by placing your cursor on the positions where the coloring is different, and run `:echon map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')` to print the syntax highlight group of the cursor position.

**Comment by KihongHeo** [comment]
I tried several vim versions (8.0, 8.1, 8.2) but all have the same behavior.

I came to know that it works well with polyglot <= 4.5.5 but does not work with >= 4.6.
I got the following messages at line 5 of the above example using the command you suggested:
4.5.5: ['cBlock', 'cAnsiFunction']
4.6: ['cBlock']

**Comment by cwfoo** [comment]
`after/syntax/c.vim` changed between the polyglot versions you mentioned. `malloc` is no longer highlighted as a keyword.

**Comment by sheerun** [comment]
Vim-polyglot no longer uses https://github.com/octol/vim-cpp-enhanced-highlight because it is not very performant. You can install it as separate package if you want syntax highlighting like before
