### ISSUE TITLE
Causing weird indents in lua

### ISSUE THREAD

**Issue by jsatk** [sheerun/vim-polyglot#705]
**Does this bug happen when you install plugin without vim-polyglot?**

Not sure.

**Describe the bug:**

Lua indents 8 spaces rather than 2. Even if I put `let g:polyglot_disabled = ['indent']` at the very top of my vimrc it doesn't respect it.

**To Reproduce:**

* Install vim-polyglot
* Open a lua file and type the following:
```lua
-- foo
```
and press <enter> at the end of the comment and it will auto indent to this:
```lua
-- foo
        -- 
```

**Comment by sheerun** [comment]
This seems to work now
