### ISSUE TITLE
Conflict with org.vim

### ISSUE THREAD

**Issue by bodograumann** [sheerun/vim-polyglot#708]
**Does this bug happen when you install plugin without vim-polyglot?**
No

**Describe the bug:**
When vim-polyglot is installed, any `*.org` files are not detected as `ft=org` anymore.

**To Reproduce:**

- Have minimal `.vimrc`:

        syntax on
        filetype plugin indent on

- Put the vim.org and vim-polyglot plugins into `~/.vim/pack/minpac/start/`
- Open a file in org mode, having the `.org` extension.
- `:set ft`

Now it should say `filetype=org`, but it actually says `filetype=`.

Cf. https://github.com/axvr/org.vim/issues/6

**Comment by sheerun** [comment]
It should be fixed now

**Comment by bodograumann** [comment]
Yes! And I can even uninstall the separat org.vim plugin.
Thank you very much.
