### ISSUE TITLE
Non-stale sway plugin

### ISSUE THREAD

**Issue by rYR79435** [sheerun/vim-polyglot#709]
We are currently using https://github.com/ajouellette/sway-vim-syntax (per request in #697), which hasn't been updated in 5 years.
I suggest we instead use https://github.com/jamespeapen/swayconfig.vim/tree/i3sway.

*Note:* My suggestion is a fork of https://github.com/mboughaba/i3config.vim, which is the plugin we use for i3 syntax highlighting.
There is an [open pullrequest](https://github.com/mboughaba/i3config.vim/pull/37) trying to merge the two, but unfortunately @mboughaba hasn't been active on GitHub since ~1 year.

Maybe it makes sense to replace both i3 and our current sway plugin with my suggestion, but I'll let you be the judge of that.

@jamespeapen, do you have thoughts/comments on this?

**Comment by jamespeapen** [comment]
Sounds good to me. There are still a few bugs to sort out like swaylock syntax, but apart from that it's functional.
