### ISSUE TITLE
Python syntax highlighting problem？

### ISSUE THREAD

**Issue by sumengmsm** [sheerun/vim-polyglot#710]
After using the plug-in, the syntax highlighting effect of the python file makes the highlighted words be bold. Can this effect be eliminated?  It makes the interface very ugly.
like this:
def
**def**

**Comment by rYR79435** [comment]
This plugin only aggregates _other_ plugins that offer syntax highlighting. Search for the correct python plugin [here](https://github.com/sheerun/vim-polyglot#language-packs) and report it to them.

**Comment by sumengmsm** [comment]
ok
I will try it ! 
Thank you.
