### ISSUE TITLE
"text" keyword missing for sqltype?

### ISSUE THREAD

**Issue by rodhash** [sheerun/vim-polyglot#711]
Hello!

**Does this bug happen when you install plugin without vim-polyglot?**
Apparently only with this plugin, it seems to me it's missing one filetype declaration in [`syntax/sqloracle.vim`](https://github.com/sheerun/vim-polyglot/blob/730dcb02caab60a6ae5d8b4bdc16d290041061ec/syntax/sqloracle.vim#L59)

https://github.com/sheerun/vim-polyglot/blob/730dcb02caab60a6ae5d8b4bdc16d290041061ec/syntax/sqloracle.vim#L59-L62

**Describe the bug:**
When creating SQL (sqlite3 in my case) I noticed some keyword were not detected, one keyword to be more precise: "text"

**To Reproduce:**
1. In vim (nvim here) create any SQL Table declaration.. in my case using Python sqlite3
2. The datatype "text" won't get highlighted given the keyword was not detected. Print screen below.

I noticed that:

- In my case all other keyword seems to be detected just fine
- if I disable polyglot all keyword are not detected at all
- By enabling polyglot & adding "text" keyword (for sqltype), it fixes it

By simply adding "text" seems to fix it:
- this is my local 'git diff' output:
![image](https://user-images.githubusercontent.com/29671981/118379810-d27b4700-b5b3-11eb-9c09-a3a66cd6776e.png)

ps: I noticed my repo was a little bit outdated so I restored the changed file and just issued a git pull / log.. still no keyword "text" detected
![image](https://user-images.githubusercontent.com/29671981/118379976-07d46480-b5b5-11eb-9e87-9acb6f1de1ec.png)

I'm no expert in SQLite3 and unsure whether this is really a bug (missing "text") but I had to tweak it a little bit.

**Comment by sheerun** [comment]
This needs to be fixed at upstream repository: https://github.com/vim/vim/blob/master/runtime/syntax/sqloracle.vim
