### ISSUE TITLE
vim-json conceals not working

### ISSUE THREAD

**Issue by TurboCartPig** [sheerun/vim-polyglot#714]
**Does this bug happen when you install plugin without vim-polyglot?**
No.

**Describe the bug:**
elzr/vim-json has a feature where where some chars in json can be concealed when you are not editing them. This is enabled by default in the plugin. These conceals do not work when vim-json is used as part of polyglot, but it does work if g:polyglot_disable = ['json'] is set and elzr/vim-json is installed manually. I might be missing something here, but I expected this feature to just work in polyglot as well. There might also be an issue with my config, but it seems suspicious that it just works if I use the original plugin.

**To Reproduce:**
Install polyglot plugin, default settings should enable conceals but do not.

To reproduce expected behaviour; install elzr/vim-json manually, and disable json in polyglot.

**Comment by sheerun** [comment]
it's disabled by default when using from vim-polyglot, that's on purpose, to be consistent with other plugins
