### ISSUE TITLE
gitignore filetype not set automatically

### ISSUE THREAD

**Issue by anuvyklack** [sheerun/vim-polyglot#717]
**Does this bug happen when you install plugin without vim-polyglot?**
  The original [fzf-gitignore](https://github.com/fszymanski/fzf-gitignore) plugin is archived.

**Describe the bug:**
The `gitignore` filetype not set automatically.

**To Reproduce:**
  Open any `.gitignore` file and type `set ft?`. I either get nothing or `conf` filetype.

**Comment by anuvyklack** [comment]
[This fork ](https://github.com/SirJson/fzf-gitignore) of fzf-gitignore is newer than the original plugin, and unlike vim-polyglot it works.

**Comment by sheerun** [comment]
Works for me with following .vimrc:

```
set nocompatible

call plug#begin()

Plug 'sheerun/vim-polyglot'

call plug#end()
```

**Comment by anuvyklack** [comment]
I'm using neovim and `nocompatible` is set by default.

**Comment by rYR79435** [comment]
I'm on neovim 0.4.4 with `nocompatible` and it works.

**Comment by anuvyklack** [comment]
I'm using the latest neovim-nightly.

**Comment by sheerun** [comment]
I tried HEAD neovim and it works for me as well. Please share your full setup, including minimal init.vim, and package manager you are using
