### ISSUE TITLE
b:current_syntax not defined error in syntax/java.vim

### ISSUE THREAD

**Issue by Frederick888** [sheerun/vim-polyglot#723]
**Does this bug happen when you install plugin without vim-polyglot?**

**Describe the bug:**
When opening a Java file:
```
line  161:
E108: No such variable: "b:current_syntax"
```

**To Reproduce:**
Open a Java file.

**Bisect**

```
# bad: [4899585281beab51e5dff1d9ae4d3159244a8275] Add org mode, close #706
# good: [27756b129b7a1f9763a0062aafa8fd35b0181b19] Update
git bisect start 'HEAD' '27756b1'
# bad: [7c474e5c9218d870dabba00745220dff5aa671b2] Add OpenSCAD support, closes #702
git bisect bad 7c474e5c9218d870dabba00745220dff5aa671b2
# good: [b0416720e7fd4434d5b444e411d1ef904ebc6d28] Enable jsdoc highlighting by default, fixes #667
git bisect good b0416720e7fd4434d5b444e411d1ef904ebc6d28
# good: [f05dea8dd765b0ce5b6c6ea92b049a5ae7547180] Disable languages also from heuristics, fixes #673
git bisect good f05dea8dd765b0ce5b6c6ea92b049a5ae7547180
# bad: [1a096f0901264629947afb89436019895e5e7ef5] Fix script indentation inside html, closes #693
git bisect bad 1a096f0901264629947afb89436019895e5e7ef5
# good: [4dd1f8f2be6a9d10d13a594e1d81af8de1d0270a] Fix loading of rust autoload functions, fixes #686
git bisect good 4dd1f8f2be6a9d10d13a594e1d81af8de1d0270a
# first bad commit: [1a096f0901264629947afb89436019895e5e7ef5] Fix script indentation inside html, closes #693
```

**Potential Fix**
Not sure it should be fixed here or some upper layer?
```diff
diff --git a/syntax/java.vim b/syntax/java.vim
index c445e00e..d803a4c4 100644
--- a/syntax/java.vim
+++ b/syntax/java.vim
@@ -157,9 +157,11 @@ syn cluster javaTop add=javaComment,javaLineComment
 if !exists("java_ignore_javadoc") && main_syntax != 'jsp'
   syntax case ignore
   " syntax coloring for javadoc comments (HTML)
   syntax include @javaHtml <sfile>:p:h/html.vim
-  unlet b:current_syntax
+  if exists("b:current_syntax")
+    unlet b:current_syntax
+  endif
   " HTML enables spell checking for all text that is not in a syntax item. This
   " is wrong for Java (all identifiers would be spell-checked), so it's undone
   " here.
   syntax spell default
```

**Comment by davidjb** [comment]
Also affected me when opening/creating a new `*.rst` file; presumably because of syntax highlighting being enabled for code blocks (even though the file itself is empty / has no Java code present).  The workaround from from @Frederick888 solves the issue for me.

**Comment by mckellygit** [comment]
Same for me when editing an rst file.
Or a -
unlet! b:current_syntax
thx,
-m

**Comment by samuel-emrys** [comment]
I'm seeing this as well when opening or creating new `*.rst` files.

**Comment by c3n21** [comment]
I'm also seeing this with *.java

**Comment by ElArtista** [comment]
Same here

**Comment by DavisOwen** [comment]
This fixed my issue. Should open this fix as a PR @Frederick888

**Comment by mckellygit** [comment]
I created PR https://github.com/sheerun/vim-polyglot/pull/731

**Comment by kmoschcau** [comment]
> Oops, nvm yes, its already done.

I don't see it already done in master. The last commit is from 9 months ago and copied the entire file.

**Comment by Frederick888** [comment]
@kmoschcau For some reason #731 was closed since there was later #733.

Then @motorto [commented](https://github.com/sheerun/vim-polyglot/pull/733#issuecomment-875104849) on #733 telling the author that it's a duplicate of... itself???

> Already a PR for that #733

And you mentioned the last commit on this file was 9 month ago but from what i can see, the last one was 05b8bbc938bdeac4a5ee2d3ae5cf7a7f05e822d3 and it was 6 months ago????

Quite confusing but anyway we've got an open PR atm.

**Comment by kmoschcau** [comment]
Oh well yeah I meant the last commit in master that touched the relevant line. The lines at the start have been modified since.

**Comment by sheerun** [comment]
Submitted PRs were unfortunately wrong solutions as polyglot doesn't modify upstream code (changes need to be commited to the vim repository, not here). Until this is done I've just removed embedded upstream code so it's not loaded twice..
