### ISSUE TITLE
Support for repos outside of GitHub

### ISSUE THREAD

**Issue by McSinyx** [sheerun/vim-polyglot#734]
At the moment, vim-octave is the only repo that I maintain *on GitHub*.  I took a glance here and it seems that remotes are all assumed to be on GitHub, would there be support for other in the future?

**Comment by sheerun** [comment]
Unfortunately there is no support for non-GitHub repositories and I don't plan to add it

**Comment by McSinyx** [comment]
Thank you for the prompt response.
