### ISSUE TITLE
JSX indent with auto close tags

### ISSUE THREAD

**Issue by kibs** [sheerun/vim-polyglot#744]
When using auto closing of tags, and when in JSX contect, and having the cursor between start and end tags, indentation is a bit wierd

```
<div>|</div>
```
And hitting enter gives the following

```
<div>
|</div>
```

I would have expected

```
<div>
    |
</div>
```

**Comment by sheerun** [comment]
Please submit this issue to https://github.com/MaxMEllon/vim-jsx-pretty
