### ISSUE TITLE
Is it possible to use vim-polyglot only for indentation?

### ISSUE THREAD

**Issue by n1ghtmare** [sheerun/vim-polyglot#771]
I can't find another plugin that does the indentation the way `vim-polyglot` does it, however I'm getting syntax highlighting from elsewhere.

Is it possible to disable all vim-polyglot features except indentation?

**Comment by sheerun** [comment]
currently not

**Comment by n1ghtmare** [comment]
Thank you for the response, great job on the plugin, keep up the good work!
