### ISSUE TITLE
Source for zinit broken

### ISSUE THREAD

**Issue by HaleTom** [sheerun/vim-polyglot#772]
Please update to all `zinit` references to:

https://github.com/zdharma-continuum/zinit-vim-syntax

GitHub user zdharma pulled all his repositories from GitHub for the 2nd time, and this time, has not restored them.

History here:
https://www.reddit.com/r/zsh/comments/qinb6j/httpsgithubcomzdharma_has_suddenly_disappeared_i/hil4oww/

**Comment by sheerun** [comment]
You'd need to find a mirror

**Comment by HaleTom** [comment]
I provided the mirror above 😂

**Comment by sheerun** [comment]
Lol, I misunderstood
