### ISSUE TITLE
Why not use othree/yajs directly?

### ISSUE THREAD

**Issue by faceleg** [sheerun/vim-polyglot#80]
I see some other languages use the original syntax repo directly, I'm interested to know why this isn't the case with othree/yajs?

**Comment by sheerun** [comment]
It had too much "candy". For example it highlighted native JS functions like "find" or "map", even it they were't native..., the same for DOM functions. I've stripped down it a little, so it's more pleasant.

It not perfect though by any means.. For example indentation is still screwed up in many places.

I'd be glad to accept something more barebone and polished than othree/yajs

**Comment by pmpbar** [comment]
I don't care if you don't do the othree branch. But, the current version does not highlight else...

**Comment by sheerun** [comment]
@pmpbar It does in default setup

**Comment by craigp** [comment]
Wow, this destroyed working with javascript for me, highlighting is really much worse now (obviously entire a personal preference, will override).

**Comment by sheerun** [comment]
@craigp Could you send example file where highlighting is destroyed? Preferably with screenshots

**Comment by sheerun** [comment]
@craigp I am the repo owner by the way

**Comment by joeytwiddle** [comment]
I switched to pangloss a while back and have not regretted it.

Here are the updates I had to make to get highlighting how I expected it to be: https://github.com/joeytwiddle/rc_files/compare/cc6479e897b019553eb13784ca6561237c098255...57c2f563aaa88cd67495d9d0bcddaf247cc6dbf3#diff-24

**Comment by jgallen23** [comment]
After the latest update, my javascript syntax highlighting is much worse for me now too.  I ended up disabling and using othree/yajs.vim instead.
