### ISSUE TITLE
javascript syntax makes jade syntax unusable

### ISSUE THREAD

**Issue by icholy** [sheerun/vim-polyglot#83]
The javascript syntax makes editing jade files very slow. [Related Issue](https://github.com/digitaltoad/vim-jade/issues/33#issuecomment-20249308)

**Comment by smarquez1** [comment]
I can confirm. I have to disable javascript syntax highlighting to make jade usable:

```let g:polyglot_disabled = ['javascript']```

**Comment by icholy** [comment]
That's what I've done too.

**Comment by sheerun** [comment]
I can't notice any lag when editing with latest vim-polyglot. Can you confirm?

**Comment by smarquez1** [comment]
@sheerun: I have no lag in smaller files, but on bigger files it's still slow. You can try this example: https://gist.github.com/smarquez1/9e3b2a281b7a2679a5db

**Comment by sheerun** [comment]
It seems to be an issue vim vim-jade itself. It run javascript syntax for each parenthesis block:

```
syn region  jadeAttributes start="(" end=")" contains=@htmlJavascript
```

I'd gladly add more performant jade syntax repository if you'll find one. Or maybe you can contribute to jade.vim and make it faster :) Either way, it's not something I can solve here.

**Comment by smarquez1** [comment]
Related issue: https://github.com/digitaltoad/vim-jade/issues/80

**Comment by kevcenteno** [comment]
@smarquez1 @icholy Do y'all mind checking out my fix?  https://github.com/digitaltoad/vim-pug/pull/102
